/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.facebook.category;

import com.vanniktech.emoji.facebook.FacebookEmoji;

final class TravelAndPlacesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static FacebookEmoji[] get() {
    return new FacebookEmoji[] {
      new FacebookEmoji(0x1F30D, new String[]{"earth_africa"}, 5, 12, false),
      new FacebookEmoji(0x1F30E, new String[]{"earth_americas"}, 5, 13, false),
      new FacebookEmoji(0x1F30F, new String[]{"earth_asia"}, 5, 14, false),
      new FacebookEmoji(0x1F310, new String[]{"globe_with_meridians"}, 5, 15, false),
      new FacebookEmoji(new int[] { 0x1F5FA, 0xFE0F }, new String[]{"world_map"}, 32, 14, false),
      new FacebookEmoji(0x1F5FE, new String[]{"japan"}, 32, 18, false),
      new FacebookEmoji(0x1F9ED, new String[]{"compass"}, 53, 27, false),
      new FacebookEmoji(new int[] { 0x1F3D4, 0xFE0F }, new String[]{"snow_capped_mountain"}, 9, 60, false),
      new FacebookEmoji(new int[] { 0x26F0, 0xFE0F }, new String[]{"mountain"}, 57, 56, false),
      new FacebookEmoji(0x1F30B, new String[]{"volcano"}, 5, 10, false),
      new FacebookEmoji(0x1F5FB, new String[]{"mount_fuji"}, 32, 15, false),
      new FacebookEmoji(new int[] { 0x1F3D5, 0xFE0F }, new String[]{"camping"}, 10, 0, false),
      new FacebookEmoji(new int[] { 0x1F3D6, 0xFE0F }, new String[]{"beach_with_umbrella"}, 10, 1, false),
      new FacebookEmoji(new int[] { 0x1F3DC, 0xFE0F }, new String[]{"desert"}, 10, 7, false),
      new FacebookEmoji(new int[] { 0x1F3DD, 0xFE0F }, new String[]{"desert_island"}, 10, 8, false),
      new FacebookEmoji(new int[] { 0x1F3DE, 0xFE0F }, new String[]{"national_park"}, 10, 9, false),
      new FacebookEmoji(new int[] { 0x1F3DF, 0xFE0F }, new String[]{"stadium"}, 10, 10, false),
      new FacebookEmoji(new int[] { 0x1F3DB, 0xFE0F }, new String[]{"classical_building"}, 10, 6, false),
      new FacebookEmoji(new int[] { 0x1F3D7, 0xFE0F }, new String[]{"building_construction"}, 10, 2, false),
      new FacebookEmoji(0x1F9F1, new String[]{"bricks"}, 53, 31, false),
      new FacebookEmoji(0x1FAA8, new String[]{"rock"}, 54, 26, false),
      new FacebookEmoji(0x1FAB5, new String[]{"wood"}, 54, 36, false),
      new FacebookEmoji(0x1F6D6, new String[]{"hut"}, 38, 6, false),
      new FacebookEmoji(new int[] { 0x1F3D8, 0xFE0F }, new String[]{"house_buildings"}, 10, 3, false),
      new FacebookEmoji(new int[] { 0x1F3DA, 0xFE0F }, new String[]{"derelict_house_building"}, 10, 5, false),
      new FacebookEmoji(0x1F3E0, new String[]{"house"}, 10, 11, false),
      new FacebookEmoji(0x1F3E1, new String[]{"house_with_garden"}, 10, 12, false),
      new FacebookEmoji(0x1F3E2, new String[]{"office"}, 10, 13, false),
      new FacebookEmoji(0x1F3E3, new String[]{"post_office"}, 10, 14, false),
      new FacebookEmoji(0x1F3E4, new String[]{"european_post_office"}, 10, 15, false),
      new FacebookEmoji(0x1F3E5, new String[]{"hospital"}, 10, 16, false),
      new FacebookEmoji(0x1F3E6, new String[]{"bank"}, 10, 17, false),
      new FacebookEmoji(0x1F3E8, new String[]{"hotel"}, 10, 19, false),
      new FacebookEmoji(0x1F3E9, new String[]{"love_hotel"}, 10, 20, false),
      new FacebookEmoji(0x1F3EA, new String[]{"convenience_store"}, 10, 21, false),
      new FacebookEmoji(0x1F3EB, new String[]{"school"}, 10, 22, false),
      new FacebookEmoji(0x1F3EC, new String[]{"department_store"}, 10, 23, false),
      new FacebookEmoji(0x1F3ED, new String[]{"factory"}, 10, 24, false),
      new FacebookEmoji(0x1F3EF, new String[]{"japanese_castle"}, 10, 26, false),
      new FacebookEmoji(0x1F3F0, new String[]{"european_castle"}, 10, 27, false),
      new FacebookEmoji(0x1F492, new String[]{"wedding"}, 27, 33, false),
      new FacebookEmoji(0x1F5FC, new String[]{"tokyo_tower"}, 32, 16, false),
      new FacebookEmoji(0x1F5FD, new String[]{"statue_of_liberty"}, 32, 17, false),
      new FacebookEmoji(0x26EA, new String[]{"church"}, 57, 55, false),
      new FacebookEmoji(0x1F54C, new String[]{"mosque"}, 30, 29, false),
      new FacebookEmoji(0x1F6D5, new String[]{"hindu_temple"}, 38, 5, false),
      new FacebookEmoji(0x1F54D, new String[]{"synagogue"}, 30, 30, false),
      new FacebookEmoji(new int[] { 0x26E9, 0xFE0F }, new String[]{"shinto_shrine"}, 57, 54, false),
      new FacebookEmoji(0x1F54B, new String[]{"kaaba"}, 30, 28, false),
      new FacebookEmoji(0x26F2, new String[]{"fountain"}, 57, 58, false),
      new FacebookEmoji(0x26FA, new String[]{"tent"}, 58, 21, false),
      new FacebookEmoji(0x1F301, new String[]{"foggy"}, 5, 0, false),
      new FacebookEmoji(0x1F303, new String[]{"night_with_stars"}, 5, 2, false),
      new FacebookEmoji(new int[] { 0x1F3D9, 0xFE0F }, new String[]{"cityscape"}, 10, 4, false),
      new FacebookEmoji(0x1F304, new String[]{"sunrise_over_mountains"}, 5, 3, false),
      new FacebookEmoji(0x1F305, new String[]{"sunrise"}, 5, 4, false),
      new FacebookEmoji(0x1F306, new String[]{"city_sunset"}, 5, 5, false),
      new FacebookEmoji(0x1F307, new String[]{"city_sunrise"}, 5, 6, false),
      new FacebookEmoji(0x1F309, new String[]{"bridge_at_night"}, 5, 8, false),
      new FacebookEmoji(new int[] { 0x2668, 0xFE0F }, new String[]{"hotsprings"}, 57, 24, false),
      new FacebookEmoji(0x1F3A0, new String[]{"carousel_horse"}, 7, 35, false),
      new FacebookEmoji(0x1F3A1, new String[]{"ferris_wheel"}, 7, 36, false),
      new FacebookEmoji(0x1F3A2, new String[]{"roller_coaster"}, 7, 37, false),
      new FacebookEmoji(0x1F488, new String[]{"barber"}, 26, 34, false),
      new FacebookEmoji(0x1F3AA, new String[]{"circus_tent"}, 7, 45, false),
      new FacebookEmoji(0x1F682, new String[]{"steam_locomotive"}, 35, 34, false),
      new FacebookEmoji(0x1F683, new String[]{"railway_car"}, 35, 35, false),
      new FacebookEmoji(0x1F684, new String[]{"bullettrain_side"}, 35, 36, false),
      new FacebookEmoji(0x1F685, new String[]{"bullettrain_front"}, 35, 37, false),
      new FacebookEmoji(0x1F686, new String[]{"train2"}, 35, 38, false),
      new FacebookEmoji(0x1F687, new String[]{"metro"}, 35, 39, false),
      new FacebookEmoji(0x1F688, new String[]{"light_rail"}, 35, 40, false),
      new FacebookEmoji(0x1F689, new String[]{"station"}, 35, 41, false),
      new FacebookEmoji(0x1F68A, new String[]{"tram"}, 35, 42, false),
      new FacebookEmoji(0x1F69D, new String[]{"monorail"}, 36, 0, false),
      new FacebookEmoji(0x1F69E, new String[]{"mountain_railway"}, 36, 1, false),
      new FacebookEmoji(0x1F68B, new String[]{"train"}, 35, 43, false),
      new FacebookEmoji(0x1F68C, new String[]{"bus"}, 35, 44, false),
      new FacebookEmoji(0x1F68D, new String[]{"oncoming_bus"}, 35, 45, false),
      new FacebookEmoji(0x1F68E, new String[]{"trolleybus"}, 35, 46, false),
      new FacebookEmoji(0x1F690, new String[]{"minibus"}, 35, 48, false),
      new FacebookEmoji(0x1F691, new String[]{"ambulance"}, 35, 49, false),
      new FacebookEmoji(0x1F692, new String[]{"fire_engine"}, 35, 50, false),
      new FacebookEmoji(0x1F693, new String[]{"police_car"}, 35, 51, false),
      new FacebookEmoji(0x1F694, new String[]{"oncoming_police_car"}, 35, 52, false),
      new FacebookEmoji(0x1F695, new String[]{"taxi"}, 35, 53, false),
      new FacebookEmoji(0x1F696, new String[]{"oncoming_taxi"}, 35, 54, false),
      new FacebookEmoji(0x1F697, new String[]{"car", "red_car"}, 35, 55, false),
      new FacebookEmoji(0x1F698, new String[]{"oncoming_automobile"}, 35, 56, false),
      new FacebookEmoji(0x1F699, new String[]{"blue_car"}, 35, 57, false),
      new FacebookEmoji(0x1F6FB, new String[]{"pickup_truck"}, 38, 29, false),
      new FacebookEmoji(0x1F69A, new String[]{"truck"}, 35, 58, false),
      new FacebookEmoji(0x1F69B, new String[]{"articulated_lorry"}, 35, 59, false),
      new FacebookEmoji(0x1F69C, new String[]{"tractor"}, 35, 60, false),
      new FacebookEmoji(new int[] { 0x1F3CE, 0xFE0F }, new String[]{"racing_car"}, 9, 54, false),
      new FacebookEmoji(new int[] { 0x1F3CD, 0xFE0F }, new String[]{"racing_motorcycle"}, 9, 53, false),
      new FacebookEmoji(0x1F6F5, new String[]{"motor_scooter"}, 38, 23, false),
      new FacebookEmoji(0x1F9BD, new String[]{"manual_wheelchair"}, 46, 2, false),
      new FacebookEmoji(0x1F9BC, new String[]{"motorized_wheelchair"}, 46, 1, false),
      new FacebookEmoji(0x1F6FA, new String[]{"auto_rickshaw"}, 38, 28, false),
      new FacebookEmoji(0x1F6B2, new String[]{"bike"}, 36, 38, false),
      new FacebookEmoji(0x1F6F4, new String[]{"scooter"}, 38, 22, false),
      new FacebookEmoji(0x1F6F9, new String[]{"skateboard"}, 38, 27, false),
      new FacebookEmoji(0x1F6FC, new String[]{"roller_skate"}, 38, 30, false),
      new FacebookEmoji(0x1F68F, new String[]{"busstop"}, 35, 47, false),
      new FacebookEmoji(new int[] { 0x1F6E3, 0xFE0F }, new String[]{"motorway"}, 38, 14, false),
      new FacebookEmoji(new int[] { 0x1F6E4, 0xFE0F }, new String[]{"railway_track"}, 38, 15, false),
      new FacebookEmoji(new int[] { 0x1F6E2, 0xFE0F }, new String[]{"oil_drum"}, 38, 13, false),
      new FacebookEmoji(0x26FD, new String[]{"fuelpump"}, 58, 22, false),
      new FacebookEmoji(0x1F6A8, new String[]{"rotating_light"}, 36, 28, false),
      new FacebookEmoji(0x1F6A5, new String[]{"traffic_light"}, 36, 25, false),
      new FacebookEmoji(0x1F6A6, new String[]{"vertical_traffic_light"}, 36, 26, false),
      new FacebookEmoji(0x1F6D1, new String[]{"octagonal_sign"}, 38, 3, false),
      new FacebookEmoji(0x1F6A7, new String[]{"construction"}, 36, 27, false),
      new FacebookEmoji(0x2693, new String[]{"anchor"}, 57, 29, false),
      new FacebookEmoji(0x26F5, new String[]{"boat", "sailboat"}, 58, 0, false),
      new FacebookEmoji(0x1F6F6, new String[]{"canoe"}, 38, 24, false),
      new FacebookEmoji(0x1F6A4, new String[]{"speedboat"}, 36, 24, false),
      new FacebookEmoji(new int[] { 0x1F6F3, 0xFE0F }, new String[]{"passenger_ship"}, 38, 21, false),
      new FacebookEmoji(new int[] { 0x26F4, 0xFE0F }, new String[]{"ferry"}, 57, 60, false),
      new FacebookEmoji(new int[] { 0x1F6E5, 0xFE0F }, new String[]{"motor_boat"}, 38, 16, false),
      new FacebookEmoji(0x1F6A2, new String[]{"ship"}, 36, 5, false),
      new FacebookEmoji(new int[] { 0x2708, 0xFE0F }, new String[]{"airplane"}, 58, 25, false),
      new FacebookEmoji(new int[] { 0x1F6E9, 0xFE0F }, new String[]{"small_airplane"}, 38, 17, false),
      new FacebookEmoji(0x1F6EB, new String[]{"airplane_departure"}, 38, 18, false),
      new FacebookEmoji(0x1F6EC, new String[]{"airplane_arriving"}, 38, 19, false),
      new FacebookEmoji(0x1FA82, new String[]{"parachute"}, 53, 58, false),
      new FacebookEmoji(0x1F4BA, new String[]{"seat"}, 28, 17, false),
      new FacebookEmoji(0x1F681, new String[]{"helicopter"}, 35, 33, false),
      new FacebookEmoji(0x1F69F, new String[]{"suspension_railway"}, 36, 2, false),
      new FacebookEmoji(0x1F6A0, new String[]{"mountain_cableway"}, 36, 3, false),
      new FacebookEmoji(0x1F6A1, new String[]{"aerial_tramway"}, 36, 4, false),
      new FacebookEmoji(new int[] { 0x1F6F0, 0xFE0F }, new String[]{"satellite"}, 38, 20, false),
      new FacebookEmoji(0x1F680, new String[]{"rocket"}, 35, 32, false),
      new FacebookEmoji(0x1F6F8, new String[]{"flying_saucer"}, 38, 26, false),
      new FacebookEmoji(new int[] { 0x1F6CE, 0xFE0F }, new String[]{"bellhop_bell"}, 38, 0, false),
      new FacebookEmoji(0x1F9F3, new String[]{"luggage"}, 53, 33, false),
      new FacebookEmoji(0x231B, new String[]{"hourglass"}, 56, 14, false),
      new FacebookEmoji(0x23F3, new String[]{"hourglass_flowing_sand"}, 56, 27, false),
      new FacebookEmoji(0x231A, new String[]{"watch"}, 56, 13, false),
      new FacebookEmoji(0x23F0, new String[]{"alarm_clock"}, 56, 24, false),
      new FacebookEmoji(new int[] { 0x23F1, 0xFE0F }, new String[]{"stopwatch"}, 56, 25, false),
      new FacebookEmoji(new int[] { 0x23F2, 0xFE0F }, new String[]{"timer_clock"}, 56, 26, false),
      new FacebookEmoji(new int[] { 0x1F570, 0xFE0F }, new String[]{"mantelpiece_clock"}, 30, 57, false),
      new FacebookEmoji(0x1F55B, new String[]{"clock12"}, 30, 43, false),
      new FacebookEmoji(0x1F567, new String[]{"clock1230"}, 30, 55, false),
      new FacebookEmoji(0x1F550, new String[]{"clock1"}, 30, 32, false),
      new FacebookEmoji(0x1F55C, new String[]{"clock130"}, 30, 44, false),
      new FacebookEmoji(0x1F551, new String[]{"clock2"}, 30, 33, false),
      new FacebookEmoji(0x1F55D, new String[]{"clock230"}, 30, 45, false),
      new FacebookEmoji(0x1F552, new String[]{"clock3"}, 30, 34, false),
      new FacebookEmoji(0x1F55E, new String[]{"clock330"}, 30, 46, false),
      new FacebookEmoji(0x1F553, new String[]{"clock4"}, 30, 35, false),
      new FacebookEmoji(0x1F55F, new String[]{"clock430"}, 30, 47, false),
      new FacebookEmoji(0x1F554, new String[]{"clock5"}, 30, 36, false),
      new FacebookEmoji(0x1F560, new String[]{"clock530"}, 30, 48, false),
      new FacebookEmoji(0x1F555, new String[]{"clock6"}, 30, 37, false),
      new FacebookEmoji(0x1F561, new String[]{"clock630"}, 30, 49, false),
      new FacebookEmoji(0x1F556, new String[]{"clock7"}, 30, 38, false),
      new FacebookEmoji(0x1F562, new String[]{"clock730"}, 30, 50, false),
      new FacebookEmoji(0x1F557, new String[]{"clock8"}, 30, 39, false),
      new FacebookEmoji(0x1F563, new String[]{"clock830"}, 30, 51, false),
      new FacebookEmoji(0x1F558, new String[]{"clock9"}, 30, 40, false),
      new FacebookEmoji(0x1F564, new String[]{"clock930"}, 30, 52, false),
      new FacebookEmoji(0x1F559, new String[]{"clock10"}, 30, 41, false),
      new FacebookEmoji(0x1F565, new String[]{"clock1030"}, 30, 53, false),
      new FacebookEmoji(0x1F55A, new String[]{"clock11"}, 30, 42, false),
      new FacebookEmoji(0x1F566, new String[]{"clock1130"}, 30, 54, false),
      new FacebookEmoji(0x1F311, new String[]{"new_moon"}, 5, 16, false),
      new FacebookEmoji(0x1F312, new String[]{"waxing_crescent_moon"}, 5, 17, false),
      new FacebookEmoji(0x1F313, new String[]{"first_quarter_moon"}, 5, 18, false),
      new FacebookEmoji(0x1F314, new String[]{"moon", "waxing_gibbous_moon"}, 5, 19, false),
      new FacebookEmoji(0x1F315, new String[]{"full_moon"}, 5, 20, false),
      new FacebookEmoji(0x1F316, new String[]{"waning_gibbous_moon"}, 5, 21, false),
      new FacebookEmoji(0x1F317, new String[]{"last_quarter_moon"}, 5, 22, false),
      new FacebookEmoji(0x1F318, new String[]{"waning_crescent_moon"}, 5, 23, false),
      new FacebookEmoji(0x1F319, new String[]{"crescent_moon"}, 5, 24, false),
      new FacebookEmoji(0x1F31A, new String[]{"new_moon_with_face"}, 5, 25, false),
      new FacebookEmoji(0x1F31B, new String[]{"first_quarter_moon_with_face"}, 5, 26, false),
      new FacebookEmoji(0x1F31C, new String[]{"last_quarter_moon_with_face"}, 5, 27, false),
      new FacebookEmoji(new int[] { 0x1F321, 0xFE0F }, new String[]{"thermometer"}, 5, 32, false),
      new FacebookEmoji(new int[] { 0x2600, 0xFE0F }, new String[]{"sunny"}, 56, 40, false),
      new FacebookEmoji(0x1F31D, new String[]{"full_moon_with_face"}, 5, 28, false),
      new FacebookEmoji(0x1F31E, new String[]{"sun_with_face"}, 5, 29, false),
      new FacebookEmoji(0x1FA90, new String[]{"ringed_planet"}, 54, 2, false),
      new FacebookEmoji(0x2B50, new String[]{"star"}, 59, 24, false,
        new FacebookEmoji(new int[] { 0x2B50, 0xFE0F }, new String[0], 59, 24, false)
      ),
      new FacebookEmoji(0x1F31F, new String[]{"star2"}, 5, 30, false),
      new FacebookEmoji(0x1F320, new String[]{"stars"}, 5, 31, false),
      new FacebookEmoji(0x1F30C, new String[]{"milky_way"}, 5, 11, false),
      new FacebookEmoji(new int[] { 0x2601, 0xFE0F }, new String[]{"cloud"}, 56, 41, false),
      new FacebookEmoji(0x26C5, new String[]{"partly_sunny"}, 57, 47, false),
      new FacebookEmoji(new int[] { 0x26C8, 0xFE0F }, new String[]{"thunder_cloud_and_rain"}, 57, 48, false),
      new FacebookEmoji(new int[] { 0x1F324, 0xFE0F }, new String[]{"mostly_sunny", "sun_small_cloud"}, 5, 33, false),
      new FacebookEmoji(new int[] { 0x1F325, 0xFE0F }, new String[]{"barely_sunny", "sun_behind_cloud"}, 5, 34, false),
      new FacebookEmoji(new int[] { 0x1F326, 0xFE0F }, new String[]{"partly_sunny_rain", "sun_behind_rain_cloud"}, 5, 35, false),
      new FacebookEmoji(new int[] { 0x1F327, 0xFE0F }, new String[]{"rain_cloud"}, 5, 36, false),
      new FacebookEmoji(new int[] { 0x1F328, 0xFE0F }, new String[]{"snow_cloud"}, 5, 37, false),
      new FacebookEmoji(new int[] { 0x1F329, 0xFE0F }, new String[]{"lightning", "lightning_cloud"}, 5, 38, false),
      new FacebookEmoji(new int[] { 0x1F32A, 0xFE0F }, new String[]{"tornado", "tornado_cloud"}, 5, 39, false),
      new FacebookEmoji(new int[] { 0x1F32B, 0xFE0F }, new String[]{"fog"}, 5, 40, false)
    };
  }

  private TravelAndPlacesCategoryChunk0() {
    // No instances.
  }
}
