/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.ios.category

import com.vanniktech.emoji.ios.IosEmoji

internal object ObjectsCategoryChunk1 {
  val EMOJIS: Array<IosEmoji> = arrayOf(
    IosEmoji(intArrayOf(0x1F58B, 0xFE0F), arrayOf("lower_left_fountain_pen"), 31, 34, false),
    IosEmoji(intArrayOf(0x1F58A, 0xFE0F), arrayOf("lower_left_ballpoint_pen"), 31, 33, false),
    IosEmoji(intArrayOf(0x1F58C, 0xFE0F), arrayOf("lower_left_paintbrush"), 31, 35, false),
    IosEmoji(intArrayOf(0x1F58D, 0xFE0F), arrayOf("lower_left_crayon"), 31, 36, false),
    IosEmoji(intArrayOf(0x1F4DD), arrayOf("memo", "pencil"), 28, 52, false),
    IosEmoji(intArrayOf(0x1F4BC), arrayOf("briefcase"), 28, 19, false),
    IosEmoji(intArrayOf(0x1F4C1), arrayOf("file_folder"), 28, 24, false),
    IosEmoji(intArrayOf(0x1F4C2), arrayOf("open_file_folder"), 28, 25, false),
    IosEmoji(intArrayOf(0x1F5C2, 0xFE0F), arrayOf("card_index_dividers"), 32, 0, false),
    IosEmoji(intArrayOf(0x1F4C5), arrayOf("date"), 28, 28, false),
    IosEmoji(intArrayOf(0x1F4C6), arrayOf("calendar"), 28, 29, false),
    IosEmoji(intArrayOf(0x1F5D2, 0xFE0F), arrayOf("spiral_note_pad"), 32, 4, false),
    IosEmoji(intArrayOf(0x1F5D3, 0xFE0F), arrayOf("spiral_calendar_pad"), 32, 5, false),
    IosEmoji(intArrayOf(0x1F4C7), arrayOf("card_index"), 28, 30, false),
    IosEmoji(intArrayOf(0x1F4C8), arrayOf("chart_with_upwards_trend"), 28, 31, false),
    IosEmoji(intArrayOf(0x1F4C9), arrayOf("chart_with_downwards_trend"), 28, 32, false),
    IosEmoji(intArrayOf(0x1F4CA), arrayOf("bar_chart"), 28, 33, false),
    IosEmoji(intArrayOf(0x1F4CB), arrayOf("clipboard"), 28, 34, false),
    IosEmoji(intArrayOf(0x1F4CC), arrayOf("pushpin"), 28, 35, false),
    IosEmoji(intArrayOf(0x1F4CD), arrayOf("round_pushpin"), 28, 36, false),
    IosEmoji(intArrayOf(0x1F4CE), arrayOf("paperclip"), 28, 37, false),
    IosEmoji(intArrayOf(0x1F587, 0xFE0F), arrayOf("linked_paperclips"), 31, 32, false),
    IosEmoji(intArrayOf(0x1F4CF), arrayOf("straight_ruler"), 28, 38, false),
    IosEmoji(intArrayOf(0x1F4D0), arrayOf("triangular_ruler"), 28, 39, false),
    IosEmoji(intArrayOf(0x2702, 0xFE0F), arrayOf("scissors"), 58, 23, false),
    IosEmoji(intArrayOf(0x1F5C3, 0xFE0F), arrayOf("card_file_box"), 32, 1, false),
    IosEmoji(intArrayOf(0x1F5C4, 0xFE0F), arrayOf("file_cabinet"), 32, 2, false),
    IosEmoji(intArrayOf(0x1F5D1, 0xFE0F), arrayOf("wastebasket"), 32, 3, false),
    IosEmoji(intArrayOf(0x1F512), arrayOf("lock"), 29, 43, false),
    IosEmoji(intArrayOf(0x1F513), arrayOf("unlock"), 29, 44, false),
    IosEmoji(intArrayOf(0x1F50F), arrayOf("lock_with_ink_pen"), 29, 40, false),
    IosEmoji(intArrayOf(0x1F510), arrayOf("closed_lock_with_key"), 29, 41, false),
    IosEmoji(intArrayOf(0x1F511), arrayOf("key"), 29, 42, false),
    IosEmoji(intArrayOf(0x1F5DD, 0xFE0F), arrayOf("old_key"), 32, 7, false),
    IosEmoji(intArrayOf(0x1F528), arrayOf("hammer"), 30, 4, false),
    IosEmoji(intArrayOf(0x1FA93), arrayOf("axe"), 54, 5, false),
    IosEmoji(intArrayOf(0x26CF, 0xFE0F), arrayOf("pick"), 57, 50, false),
    IosEmoji(intArrayOf(0x2692, 0xFE0F), arrayOf("hammer_and_pick"), 57, 28, false),
    IosEmoji(intArrayOf(0x1F6E0, 0xFE0F), arrayOf("hammer_and_wrench"), 38, 11, false),
    IosEmoji(intArrayOf(0x1F5E1, 0xFE0F), arrayOf("dagger_knife"), 32, 9, false),
    IosEmoji(intArrayOf(0x2694, 0xFE0F), arrayOf("crossed_swords"), 57, 30, false),
    IosEmoji(intArrayOf(0x1F52B), arrayOf("gun"), 30, 7, false),
    IosEmoji(intArrayOf(0x1FA83), arrayOf("boomerang"), 53, 59, false),
    IosEmoji(intArrayOf(0x1F3F9), arrayOf("bow_and_arrow"), 10, 39, false),
    IosEmoji(intArrayOf(0x1F6E1, 0xFE0F), arrayOf("shield"), 38, 12, false),
    IosEmoji(intArrayOf(0x1FA9A), arrayOf("carpentry_saw"), 54, 12, false),
    IosEmoji(intArrayOf(0x1F527), arrayOf("wrench"), 30, 3, false),
    IosEmoji(intArrayOf(0x1FA9B), arrayOf("screwdriver"), 54, 13, false),
    IosEmoji(intArrayOf(0x1F529), arrayOf("nut_and_bolt"), 30, 5, false),
    IosEmoji(intArrayOf(0x2699, 0xFE0F), arrayOf("gear"), 57, 34, false),
    IosEmoji(intArrayOf(0x1F5DC, 0xFE0F), arrayOf("compression"), 32, 6, false),
    IosEmoji(intArrayOf(0x2696, 0xFE0F), arrayOf("scales"), 57, 32, false),
    IosEmoji(intArrayOf(0x1F9AF), arrayOf("probing_cane"), 45, 4, false),
    IosEmoji(intArrayOf(0x1F517), arrayOf("link"), 29, 48, false),
    IosEmoji(intArrayOf(0x26D3, 0xFE0F), arrayOf("chains"), 57, 52, false),
    IosEmoji(intArrayOf(0x1FA9D), arrayOf("hook"), 54, 15, false),
    IosEmoji(intArrayOf(0x1F9F0), arrayOf("toolbox"), 53, 30, false),
    IosEmoji(intArrayOf(0x1F9F2), arrayOf("magnet"), 53, 32, false),
    IosEmoji(intArrayOf(0x1FA9C), arrayOf("ladder"), 54, 14, false),
    IosEmoji(intArrayOf(0x2697, 0xFE0F), arrayOf("alembic"), 57, 33, false),
    IosEmoji(intArrayOf(0x1F9EA), arrayOf("test_tube"), 53, 24, false),
    IosEmoji(intArrayOf(0x1F9EB), arrayOf("petri_dish"), 53, 25, false),
    IosEmoji(intArrayOf(0x1F9EC), arrayOf("dna"), 53, 26, false),
    IosEmoji(intArrayOf(0x1F52C), arrayOf("microscope"), 30, 8, false),
    IosEmoji(intArrayOf(0x1F52D), arrayOf("telescope"), 30, 9, false),
    IosEmoji(intArrayOf(0x1F4E1), arrayOf("satellite_antenna"), 28, 56, false),
    IosEmoji(intArrayOf(0x1F489), arrayOf("syringe"), 26, 35, false),
    IosEmoji(intArrayOf(0x1FA78), arrayOf("drop_of_blood"), 53, 51, false),
    IosEmoji(intArrayOf(0x1F48A), arrayOf("pill"), 26, 36, false),
    IosEmoji(intArrayOf(0x1FA79), arrayOf("adhesive_bandage"), 53, 52, false),
    IosEmoji(intArrayOf(0x1FA7C), arrayOf("crutch"), 53, 55, false),
    IosEmoji(intArrayOf(0x1FA7A), arrayOf("stethoscope"), 53, 53, false),
    IosEmoji(intArrayOf(0x1FA7B), arrayOf("x-ray"), 53, 54, false),
    IosEmoji(intArrayOf(0x1F6AA), arrayOf("door"), 36, 30, false),
    IosEmoji(intArrayOf(0x1F6D7), arrayOf("elevator"), 38, 7, false),
    IosEmoji(intArrayOf(0x1FA9E), arrayOf("mirror"), 54, 16, false),
    IosEmoji(intArrayOf(0x1FA9F), arrayOf("window"), 54, 17, false),
    IosEmoji(intArrayOf(0x1F6CF, 0xFE0F), arrayOf("bed"), 38, 1, false),
    IosEmoji(intArrayOf(0x1F6CB, 0xFE0F), arrayOf("couch_and_lamp"), 37, 53, false),
    IosEmoji(intArrayOf(0x1FA91), arrayOf("chair"), 54, 3, false),
    IosEmoji(intArrayOf(0x1F6BD), arrayOf("toilet"), 37, 39, false),
    IosEmoji(intArrayOf(0x1FAA0), arrayOf("plunger"), 54, 18, false),
    IosEmoji(intArrayOf(0x1F6BF), arrayOf("shower"), 37, 41, false),
    IosEmoji(intArrayOf(0x1F6C1), arrayOf("bathtub"), 37, 48, false),
    IosEmoji(intArrayOf(0x1FAA4), arrayOf("mouse_trap"), 54, 22, false),
    IosEmoji(intArrayOf(0x1FA92), arrayOf("razor"), 54, 4, false),
    IosEmoji(intArrayOf(0x1F9F4), arrayOf("lotion_bottle"), 53, 34, false),
    IosEmoji(intArrayOf(0x1F9F7), arrayOf("safety_pin"), 53, 37, false),
    IosEmoji(intArrayOf(0x1F9F9), arrayOf("broom"), 53, 39, false),
    IosEmoji(intArrayOf(0x1F9FA), arrayOf("basket"), 53, 40, false),
    IosEmoji(intArrayOf(0x1F9FB), arrayOf("roll_of_paper"), 53, 41, false),
    IosEmoji(intArrayOf(0x1FAA3), arrayOf("bucket"), 54, 21, false),
    IosEmoji(intArrayOf(0x1F9FC), arrayOf("soap"), 53, 42, false),
    IosEmoji(intArrayOf(0x1FAE7), arrayOf("bubbles"), 55, 19, false),
    IosEmoji(intArrayOf(0x1FAA5), arrayOf("toothbrush"), 54, 23, false),
    IosEmoji(intArrayOf(0x1F9FD), arrayOf("sponge"), 53, 43, false),
    IosEmoji(intArrayOf(0x1F9EF), arrayOf("fire_extinguisher"), 53, 29, false),
    IosEmoji(intArrayOf(0x1F6D2), arrayOf("shopping_trolley"), 38, 4, false),
    IosEmoji(intArrayOf(0x1F6AC), arrayOf("smoking"), 36, 32, false),
    IosEmoji(intArrayOf(0x26B0, 0xFE0F), arrayOf("coffin"), 57, 42, false),
    IosEmoji(intArrayOf(0x1FAA6), arrayOf("headstone"), 54, 24, false),
    IosEmoji(intArrayOf(0x26B1, 0xFE0F), arrayOf("funeral_urn"), 57, 43, false),
    IosEmoji(intArrayOf(0x1F5FF), arrayOf("moyai"), 32, 19, false),
    IosEmoji(intArrayOf(0x1FAA7), arrayOf("placard"), 54, 25, false),
    IosEmoji(intArrayOf(0x1FAAA), arrayOf("identification_card"), 54, 28, false),
  )
}
