/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SmileysAndPeopleCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F600), 0, 1), listOf("grinning"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F603), 0, 1), listOf("smiley"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F604), 0, 1), listOf("smile"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F601), 0, 1), listOf("grin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F606), 0, 1), listOf("laughing", "satisfied"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F605), 0, 1), listOf("sweat_smile"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F923), 0, 1), listOf("rolling_on_the_floor_laughing"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F602), 0, 1), listOf("joy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F642), 0, 1), listOf("slightly_smiling_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F643), 0, 1), listOf("upside_down_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE0), 0, 1), listOf("melting_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F609), 0, 1), listOf("wink"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60A), 0, 1), listOf("blush"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F607), 0, 1), listOf("innocent"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F970), 0, 1), listOf("smiling_face_with_3_hearts"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60D), 0, 1), listOf("heart_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F929), 0, 1), listOf("star-struck", "grinning_face_with_star_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F618), 0, 1), listOf("kissing_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F617), 0, 1), listOf("kissing"), false),
    GoogleCompatEmoji(String(intArrayOf(0x263A, 0xFE0F), 0, 2), listOf("relaxed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61A), 0, 1), listOf("kissing_closed_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F619), 0, 1), listOf("kissing_smiling_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F972), 0, 1), listOf("smiling_face_with_tear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60B), 0, 1), listOf("yum"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61B), 0, 1), listOf("stuck_out_tongue"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61C), 0, 1), listOf("stuck_out_tongue_winking_eye"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92A), 0, 1), listOf("zany_face", "grinning_face_with_one_large_and_one_small_eye"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61D), 0, 1), listOf("stuck_out_tongue_closed_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F911), 0, 1), listOf("money_mouth_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F917), 0, 1), listOf("hugging_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92D), 0, 1), listOf("face_with_hand_over_mouth", "smiling_face_with_smiling_eyes_and_hand_covering_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE2), 0, 1), listOf("face_with_open_eyes_and_hand_over_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE3), 0, 1), listOf("face_with_peeking_eye"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92B), 0, 1), listOf("shushing_face", "face_with_finger_covering_closed_lips"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F914), 0, 1), listOf("thinking_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE1), 0, 1), listOf("saluting_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F910), 0, 1), listOf("zipper_mouth_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F928), 0, 1), listOf("face_with_raised_eyebrow", "face_with_one_eyebrow_raised"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F610), 0, 1), listOf("neutral_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F611), 0, 1), listOf("expressionless"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F636), 0, 1), listOf("no_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE5), 0, 1), listOf("dotted_line_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F636, 0x200D, 0x1F32B, 0xFE0F), 0, 4), listOf("face_in_clouds"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60F), 0, 1), listOf("smirk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F612), 0, 1), listOf("unamused"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F644), 0, 1), listOf("face_with_rolling_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62C), 0, 1), listOf("grimacing"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62E, 0x200D, 0x1F4A8), 0, 3), listOf("face_exhaling"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F925), 0, 1), listOf("lying_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60C), 0, 1), listOf("relieved"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F614), 0, 1), listOf("pensive"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62A), 0, 1), listOf("sleepy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F924), 0, 1), listOf("drooling_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F634), 0, 1), listOf("sleeping"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F637), 0, 1), listOf("mask"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F912), 0, 1), listOf("face_with_thermometer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F915), 0, 1), listOf("face_with_head_bandage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F922), 0, 1), listOf("nauseated_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92E), 0, 1), listOf("face_vomiting", "face_with_open_mouth_vomiting"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F927), 0, 1), listOf("sneezing_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F975), 0, 1), listOf("hot_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F976), 0, 1), listOf("cold_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F974), 0, 1), listOf("woozy_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F635), 0, 1), listOf("dizzy_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F635, 0x200D, 0x1F4AB), 0, 3), listOf("face_with_spiral_eyes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92F), 0, 1), listOf("exploding_head", "shocked_face_with_exploding_head"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F920), 0, 1), listOf("face_with_cowboy_hat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F973), 0, 1), listOf("partying_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F978), 0, 1), listOf("disguised_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F60E), 0, 1), listOf("sunglasses"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F913), 0, 1), listOf("nerd_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9D0), 0, 1), listOf("face_with_monocle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F615), 0, 1), listOf("confused"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE4), 0, 1), listOf("face_with_diagonal_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61F), 0, 1), listOf("worried"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F641), 0, 1), listOf("slightly_frowning_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2639, 0xFE0F), 0, 2), listOf("white_frowning_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62E), 0, 1), listOf("open_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62F), 0, 1), listOf("hushed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F632), 0, 1), listOf("astonished"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F633), 0, 1), listOf("flushed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F97A), 0, 1), listOf("pleading_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F979), 0, 1), listOf("face_holding_back_tears"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F626), 0, 1), listOf("frowning"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F627), 0, 1), listOf("anguished"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F628), 0, 1), listOf("fearful"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F630), 0, 1), listOf("cold_sweat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F625), 0, 1), listOf("disappointed_relieved"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F622), 0, 1), listOf("cry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62D), 0, 1), listOf("sob"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F631), 0, 1), listOf("scream"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F616), 0, 1), listOf("confounded"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F623), 0, 1), listOf("persevere"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F61E), 0, 1), listOf("disappointed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F613), 0, 1), listOf("sweat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F629), 0, 1), listOf("weary"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F62B), 0, 1), listOf("tired_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F971), 0, 1), listOf("yawning_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F624), 0, 1), listOf("triumph"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F621), 0, 1), listOf("rage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F620), 0, 1), listOf("angry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F92C), 0, 1), listOf("face_with_symbols_on_mouth", "serious_face_with_symbols_covering_mouth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F608), 0, 1), listOf("smiling_imp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F47F), 0, 1), listOf("imp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F480), 0, 1), listOf("skull"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2620, 0xFE0F), 0, 2), listOf("skull_and_crossbones"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4A9), 0, 1), listOf("hankey", "poop", "shit"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F921), 0, 1), listOf("clown_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F479), 0, 1), listOf("japanese_ogre"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F47A), 0, 1), listOf("japanese_goblin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F47B), 0, 1), listOf("ghost"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F47D), 0, 1), listOf("alien"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F47E), 0, 1), listOf("space_invader"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F916), 0, 1), listOf("robot_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63A), 0, 1), listOf("smiley_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F638), 0, 1), listOf("smile_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F639), 0, 1), listOf("joy_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63B), 0, 1), listOf("heart_eyes_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63C), 0, 1), listOf("smirk_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63D), 0, 1), listOf("kissing_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F640), 0, 1), listOf("scream_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63F), 0, 1), listOf("crying_cat_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F63E), 0, 1), listOf("pouting_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F648), 0, 1), listOf("see_no_evil"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F649), 0, 1), listOf("hear_no_evil"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F64A), 0, 1), listOf("speak_no_evil"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F48B), 0, 1), listOf("kiss"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F48C), 0, 1), listOf("love_letter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F498), 0, 1), listOf("cupid"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49D), 0, 1), listOf("gift_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F496), 0, 1), listOf("sparkling_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F497), 0, 1), listOf("heartpulse"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F493), 0, 1), listOf("heartbeat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49E), 0, 1), listOf("revolving_hearts"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F495), 0, 1), listOf("two_hearts"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49F), 0, 1), listOf("heart_decoration"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2763, 0xFE0F), 0, 2), listOf("heavy_heart_exclamation_mark_ornament"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F494), 0, 1), listOf("broken_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1F525), 0, 4), listOf("heart_on_fire"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1FA79), 0, 4), listOf("mending_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2764, 0xFE0F), 0, 2), listOf("heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9E1), 0, 1), listOf("orange_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49B), 0, 1), listOf("yellow_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49A), 0, 1), listOf("green_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F499), 0, 1), listOf("blue_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F49C), 0, 1), listOf("purple_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F90E), 0, 1), listOf("brown_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5A4), 0, 1), listOf("black_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F90D), 0, 1), listOf("white_heart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4AF), 0, 1), listOf("100"), false),
  )
}
