/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object TravelAndPlacesCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F30D), 0, 1), listOf("earth_africa"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F30E), 0, 1), listOf("earth_americas"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F30F), 0, 1), listOf("earth_asia"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F310), 0, 1), listOf("globe_with_meridians"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FA, 0xFE0F), 0, 2), listOf("world_map"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FE), 0, 1), listOf("japan"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9ED), 0, 1), listOf("compass"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D4, 0xFE0F), 0, 2), listOf("snow_capped_mountain"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26F0, 0xFE0F), 0, 2), listOf("mountain"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F30B), 0, 1), listOf("volcano"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FB), 0, 1), listOf("mount_fuji"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D5, 0xFE0F), 0, 2), listOf("camping"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D6, 0xFE0F), 0, 2), listOf("beach_with_umbrella"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DC, 0xFE0F), 0, 2), listOf("desert"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DD, 0xFE0F), 0, 2), listOf("desert_island"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DE, 0xFE0F), 0, 2), listOf("national_park"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DF, 0xFE0F), 0, 2), listOf("stadium"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DB, 0xFE0F), 0, 2), listOf("classical_building"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D7, 0xFE0F), 0, 2), listOf("building_construction"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F1), 0, 1), listOf("bricks"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA8), 0, 1), listOf("rock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB5), 0, 1), listOf("wood"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D6), 0, 1), listOf("hut"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D8, 0xFE0F), 0, 2), listOf("house_buildings"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3DA, 0xFE0F), 0, 2), listOf("derelict_house_building"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E0), 0, 1), listOf("house"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E1), 0, 1), listOf("house_with_garden"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E2), 0, 1), listOf("office"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E3), 0, 1), listOf("post_office"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E4), 0, 1), listOf("european_post_office"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E5), 0, 1), listOf("hospital"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E6), 0, 1), listOf("bank"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E8), 0, 1), listOf("hotel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3E9), 0, 1), listOf("love_hotel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3EA), 0, 1), listOf("convenience_store"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3EB), 0, 1), listOf("school"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3EC), 0, 1), listOf("department_store"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3ED), 0, 1), listOf("factory"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3EF), 0, 1), listOf("japanese_castle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F0), 0, 1), listOf("european_castle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F492), 0, 1), listOf("wedding"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FC), 0, 1), listOf("tokyo_tower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FD), 0, 1), listOf("statue_of_liberty"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26EA), 0, 1), listOf("church"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F54C), 0, 1), listOf("mosque"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D5), 0, 1), listOf("hindu_temple"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F54D), 0, 1), listOf("synagogue"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26E9, 0xFE0F), 0, 2), listOf("shinto_shrine"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F54B), 0, 1), listOf("kaaba"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26F2), 0, 1), listOf("fountain"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26FA), 0, 1), listOf("tent"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F301), 0, 1), listOf("foggy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F303), 0, 1), listOf("night_with_stars"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3D9, 0xFE0F), 0, 2), listOf("cityscape"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F304), 0, 1), listOf("sunrise_over_mountains"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F305), 0, 1), listOf("sunrise"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F306), 0, 1), listOf("city_sunset"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F307), 0, 1), listOf("city_sunrise"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F309), 0, 1), listOf("bridge_at_night"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2668, 0xFE0F), 0, 2), listOf("hotsprings"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3A0), 0, 1), listOf("carousel_horse"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6DD), 0, 1), listOf("playground_slide"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3A1), 0, 1), listOf("ferris_wheel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3A2), 0, 1), listOf("roller_coaster"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F488), 0, 1), listOf("barber"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3AA), 0, 1), listOf("circus_tent"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F682), 0, 1), listOf("steam_locomotive"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F683), 0, 1), listOf("railway_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F684), 0, 1), listOf("bullettrain_side"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F685), 0, 1), listOf("bullettrain_front"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F686), 0, 1), listOf("train2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F687), 0, 1), listOf("metro"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F688), 0, 1), listOf("light_rail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F689), 0, 1), listOf("station"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68A), 0, 1), listOf("tram"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69D), 0, 1), listOf("monorail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69E), 0, 1), listOf("mountain_railway"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68B), 0, 1), listOf("train"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68C), 0, 1), listOf("bus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68D), 0, 1), listOf("oncoming_bus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68E), 0, 1), listOf("trolleybus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F690), 0, 1), listOf("minibus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F691), 0, 1), listOf("ambulance"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F692), 0, 1), listOf("fire_engine"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F693), 0, 1), listOf("police_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F694), 0, 1), listOf("oncoming_police_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F695), 0, 1), listOf("taxi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F696), 0, 1), listOf("oncoming_taxi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F697), 0, 1), listOf("car", "red_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F698), 0, 1), listOf("oncoming_automobile"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F699), 0, 1), listOf("blue_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6FB), 0, 1), listOf("pickup_truck"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69A), 0, 1), listOf("truck"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69B), 0, 1), listOf("articulated_lorry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69C), 0, 1), listOf("tractor"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3CE, 0xFE0F), 0, 2), listOf("racing_car"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3CD, 0xFE0F), 0, 2), listOf("racing_motorcycle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F5), 0, 1), listOf("motor_scooter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9BD), 0, 1), listOf("manual_wheelchair"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9BC), 0, 1), listOf("motorized_wheelchair"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6FA), 0, 1), listOf("auto_rickshaw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B2), 0, 1), listOf("bike"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F4), 0, 1), listOf("scooter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F9), 0, 1), listOf("skateboard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6FC), 0, 1), listOf("roller_skate"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F68F), 0, 1), listOf("busstop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E3, 0xFE0F), 0, 2), listOf("motorway"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E4, 0xFE0F), 0, 2), listOf("railway_track"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E2, 0xFE0F), 0, 2), listOf("oil_drum"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26FD), 0, 1), listOf("fuelpump"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6DE), 0, 1), listOf("wheel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A8), 0, 1), listOf("rotating_light"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A5), 0, 1), listOf("traffic_light"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A6), 0, 1), listOf("vertical_traffic_light"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D1), 0, 1), listOf("octagonal_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A7), 0, 1), listOf("construction"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2693), 0, 1), listOf("anchor"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6DF), 0, 1), listOf("ring_buoy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26F5), 0, 1), listOf("boat", "sailboat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F6), 0, 1), listOf("canoe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A4), 0, 1), listOf("speedboat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F3, 0xFE0F), 0, 2), listOf("passenger_ship"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26F4, 0xFE0F), 0, 2), listOf("ferry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E5, 0xFE0F), 0, 2), listOf("motor_boat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A2), 0, 1), listOf("ship"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2708, 0xFE0F), 0, 2), listOf("airplane"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E9, 0xFE0F), 0, 2), listOf("small_airplane"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6EB), 0, 1), listOf("airplane_departure"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6EC), 0, 1), listOf("airplane_arriving"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA82), 0, 1), listOf("parachute"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4BA), 0, 1), listOf("seat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F681), 0, 1), listOf("helicopter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F69F), 0, 1), listOf("suspension_railway"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A0), 0, 1), listOf("mountain_cableway"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A1), 0, 1), listOf("aerial_tramway"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F0, 0xFE0F), 0, 2), listOf("satellite"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F680), 0, 1), listOf("rocket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6F8), 0, 1), listOf("flying_saucer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6CE, 0xFE0F), 0, 2), listOf("bellhop_bell"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F3), 0, 1), listOf("luggage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x231B), 0, 1), listOf("hourglass"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F3), 0, 1), listOf("hourglass_flowing_sand"), false),
    GoogleCompatEmoji(String(intArrayOf(0x231A), 0, 1), listOf("watch"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F0), 0, 1), listOf("alarm_clock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F1, 0xFE0F), 0, 2), listOf("stopwatch"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F2, 0xFE0F), 0, 2), listOf("timer_clock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F570, 0xFE0F), 0, 2), listOf("mantelpiece_clock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F55B), 0, 1), listOf("clock12"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F567), 0, 1), listOf("clock1230"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F550), 0, 1), listOf("clock1"), false),
  )
}
