/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.twitter.category

import com.vanniktech.emoji.twitter.TwitterEmoji

internal object ObjectsCategoryChunk0 {
  val EMOJIS: Array<TwitterEmoji> = arrayOf(
    TwitterEmoji(intArrayOf(0x1F453), arrayOf("eyeglasses"), 13, 15, false),
    TwitterEmoji(intArrayOf(0x1F576, 0xFE0F), arrayOf("dark_sunglasses"), 31, 22, false),
    TwitterEmoji(intArrayOf(0x1F97D), arrayOf("goggles"), 44, 15, false),
    TwitterEmoji(intArrayOf(0x1F97C), arrayOf("lab_coat"), 44, 14, false),
    TwitterEmoji(intArrayOf(0x1F9BA), arrayOf("safety_vest"), 45, 55, false),
    TwitterEmoji(intArrayOf(0x1F454), arrayOf("necktie"), 13, 16, false),
    TwitterEmoji(intArrayOf(0x1F455), arrayOf("shirt", "tshirt"), 13, 17, false),
    TwitterEmoji(intArrayOf(0x1F456), arrayOf("jeans"), 13, 18, false),
    TwitterEmoji(intArrayOf(0x1F9E3), arrayOf("scarf"), 53, 17, false),
    TwitterEmoji(intArrayOf(0x1F9E4), arrayOf("gloves"), 53, 18, false),
    TwitterEmoji(intArrayOf(0x1F9E5), arrayOf("coat"), 53, 19, false),
    TwitterEmoji(intArrayOf(0x1F9E6), arrayOf("socks"), 53, 20, false),
    TwitterEmoji(intArrayOf(0x1F457), arrayOf("dress"), 13, 19, false),
    TwitterEmoji(intArrayOf(0x1F458), arrayOf("kimono"), 13, 20, false),
    TwitterEmoji(intArrayOf(0x1F97B), arrayOf("sari"), 44, 13, false),
    TwitterEmoji(intArrayOf(0x1FA71), arrayOf("one-piece_swimsuit"), 53, 47, false),
    TwitterEmoji(intArrayOf(0x1FA72), arrayOf("briefs"), 53, 48, false),
    TwitterEmoji(intArrayOf(0x1FA73), arrayOf("shorts"), 53, 49, false),
    TwitterEmoji(intArrayOf(0x1F459), arrayOf("bikini"), 13, 21, false),
    TwitterEmoji(intArrayOf(0x1F45A), arrayOf("womans_clothes"), 13, 22, false),
    TwitterEmoji(intArrayOf(0x1F45B), arrayOf("purse"), 13, 23, false),
    TwitterEmoji(intArrayOf(0x1F45C), arrayOf("handbag"), 13, 24, false),
    TwitterEmoji(intArrayOf(0x1F45D), arrayOf("pouch"), 13, 25, false),
    TwitterEmoji(intArrayOf(0x1F6CD, 0xFE0F), arrayOf("shopping_bags"), 37, 60, false),
    TwitterEmoji(intArrayOf(0x1F392), arrayOf("school_satchel"), 7, 26, false),
    TwitterEmoji(intArrayOf(0x1FA74), arrayOf("thong_sandal"), 53, 50, false),
    TwitterEmoji(intArrayOf(0x1F45E), arrayOf("mans_shoe", "shoe"), 13, 26, false),
    TwitterEmoji(intArrayOf(0x1F45F), arrayOf("athletic_shoe"), 13, 27, false),
    TwitterEmoji(intArrayOf(0x1F97E), arrayOf("hiking_boot"), 44, 16, false),
    TwitterEmoji(intArrayOf(0x1F97F), arrayOf("womans_flat_shoe"), 44, 17, false),
    TwitterEmoji(intArrayOf(0x1F460), arrayOf("high_heel"), 13, 28, false),
    TwitterEmoji(intArrayOf(0x1F461), arrayOf("sandal"), 13, 29, false),
    TwitterEmoji(intArrayOf(0x1FA70), arrayOf("ballet_shoes"), 53, 46, false),
    TwitterEmoji(intArrayOf(0x1F462), arrayOf("boot"), 13, 30, false),
    TwitterEmoji(intArrayOf(0x1F451), arrayOf("crown"), 13, 13, false),
    TwitterEmoji(intArrayOf(0x1F452), arrayOf("womans_hat"), 13, 14, false),
    TwitterEmoji(intArrayOf(0x1F3A9), arrayOf("tophat"), 7, 44, false),
    TwitterEmoji(intArrayOf(0x1F393), arrayOf("mortar_board"), 7, 27, false),
    TwitterEmoji(intArrayOf(0x1F9E2), arrayOf("billed_cap"), 53, 16, false),
    TwitterEmoji(intArrayOf(0x1FA96), arrayOf("military_helmet"), 54, 8, false),
    TwitterEmoji(intArrayOf(0x26D1, 0xFE0F), arrayOf("helmet_with_white_cross"), 57, 51, false),
    TwitterEmoji(intArrayOf(0x1F4FF), arrayOf("prayer_beads"), 29, 24, false),
    TwitterEmoji(intArrayOf(0x1F484), arrayOf("lipstick"), 25, 52, false),
    TwitterEmoji(intArrayOf(0x1F48D), arrayOf("ring"), 26, 39, false),
    TwitterEmoji(intArrayOf(0x1F48E), arrayOf("gem"), 26, 40, false),
    TwitterEmoji(intArrayOf(0x1F507), arrayOf("mute"), 29, 32, false),
    TwitterEmoji(intArrayOf(0x1F508), arrayOf("speaker"), 29, 33, false),
    TwitterEmoji(intArrayOf(0x1F509), arrayOf("sound"), 29, 34, false),
    TwitterEmoji(intArrayOf(0x1F50A), arrayOf("loud_sound"), 29, 35, false),
    TwitterEmoji(intArrayOf(0x1F4E2), arrayOf("loudspeaker"), 28, 57, false),
    TwitterEmoji(intArrayOf(0x1F4E3), arrayOf("mega"), 28, 58, false),
    TwitterEmoji(intArrayOf(0x1F4EF), arrayOf("postal_horn"), 29, 9, false),
    TwitterEmoji(intArrayOf(0x1F514), arrayOf("bell"), 29, 45, false),
    TwitterEmoji(intArrayOf(0x1F515), arrayOf("no_bell"), 29, 46, false),
    TwitterEmoji(intArrayOf(0x1F3BC), arrayOf("musical_score"), 8, 2, false),
    TwitterEmoji(intArrayOf(0x1F3B5), arrayOf("musical_note"), 7, 56, false),
    TwitterEmoji(intArrayOf(0x1F3B6), arrayOf("notes"), 7, 57, false),
    TwitterEmoji(intArrayOf(0x1F399, 0xFE0F), arrayOf("studio_microphone"), 7, 30, false),
    TwitterEmoji(intArrayOf(0x1F39A, 0xFE0F), arrayOf("level_slider"), 7, 31, false),
    TwitterEmoji(intArrayOf(0x1F39B, 0xFE0F), arrayOf("control_knobs"), 7, 32, false),
    TwitterEmoji(intArrayOf(0x1F3A4), arrayOf("microphone"), 7, 39, false),
    TwitterEmoji(intArrayOf(0x1F3A7), arrayOf("headphones"), 7, 42, false),
    TwitterEmoji(intArrayOf(0x1F4FB), arrayOf("radio"), 29, 21, false),
    TwitterEmoji(intArrayOf(0x1F3B7), arrayOf("saxophone"), 7, 58, false),
    TwitterEmoji(intArrayOf(0x1FA97), arrayOf("accordion"), 54, 9, false),
    TwitterEmoji(intArrayOf(0x1F3B8), arrayOf("guitar"), 7, 59, false),
    TwitterEmoji(intArrayOf(0x1F3B9), arrayOf("musical_keyboard"), 7, 60, false),
    TwitterEmoji(intArrayOf(0x1F3BA), arrayOf("trumpet"), 8, 0, false),
    TwitterEmoji(intArrayOf(0x1F3BB), arrayOf("violin"), 8, 1, false),
    TwitterEmoji(intArrayOf(0x1FA95), arrayOf("banjo"), 54, 7, false),
    TwitterEmoji(intArrayOf(0x1F941), arrayOf("drum_with_drumsticks"), 43, 12, false),
    TwitterEmoji(intArrayOf(0x1FA98), arrayOf("long_drum"), 54, 10, false),
    TwitterEmoji(intArrayOf(0x1F4F1), arrayOf("iphone"), 29, 11, false),
    TwitterEmoji(intArrayOf(0x1F4F2), arrayOf("calling"), 29, 12, false),
    TwitterEmoji(intArrayOf(0x260E, 0xFE0F), arrayOf("phone", "telephone"), 56, 45, false),
    TwitterEmoji(intArrayOf(0x1F4DE), arrayOf("telephone_receiver"), 28, 53, false),
    TwitterEmoji(intArrayOf(0x1F4DF), arrayOf("pager"), 28, 54, false),
    TwitterEmoji(intArrayOf(0x1F4E0), arrayOf("fax"), 28, 55, false),
    TwitterEmoji(intArrayOf(0x1F50B), arrayOf("battery"), 29, 36, false),
    TwitterEmoji(intArrayOf(0x1FAAB), arrayOf("low_battery"), 54, 29, false),
    TwitterEmoji(intArrayOf(0x1F50C), arrayOf("electric_plug"), 29, 37, false),
    TwitterEmoji(intArrayOf(0x1F4BB), arrayOf("computer"), 28, 18, false),
    TwitterEmoji(intArrayOf(0x1F5A5, 0xFE0F), arrayOf("desktop_computer"), 31, 56, false),
    TwitterEmoji(intArrayOf(0x1F5A8, 0xFE0F), arrayOf("printer"), 31, 57, false),
    TwitterEmoji(intArrayOf(0x2328, 0xFE0F), arrayOf("keyboard"), 56, 15, false),
    TwitterEmoji(intArrayOf(0x1F5B1, 0xFE0F), arrayOf("three_button_mouse"), 31, 58, false),
    TwitterEmoji(intArrayOf(0x1F5B2, 0xFE0F), arrayOf("trackball"), 31, 59, false),
    TwitterEmoji(intArrayOf(0x1F4BD), arrayOf("minidisc"), 28, 20, false),
    TwitterEmoji(intArrayOf(0x1F4BE), arrayOf("floppy_disk"), 28, 21, false),
    TwitterEmoji(intArrayOf(0x1F4BF), arrayOf("cd"), 28, 22, false),
    TwitterEmoji(intArrayOf(0x1F4C0), arrayOf("dvd"), 28, 23, false),
    TwitterEmoji(intArrayOf(0x1F9EE), arrayOf("abacus"), 53, 28, false),
    TwitterEmoji(intArrayOf(0x1F3A5), arrayOf("movie_camera"), 7, 40, false),
    TwitterEmoji(intArrayOf(0x1F39E, 0xFE0F), arrayOf("film_frames"), 7, 33, false),
    TwitterEmoji(intArrayOf(0x1F4FD, 0xFE0F), arrayOf("film_projector"), 29, 23, false),
    TwitterEmoji(intArrayOf(0x1F3AC), arrayOf("clapper"), 7, 47, false),
    TwitterEmoji(intArrayOf(0x1F4FA), arrayOf("tv"), 29, 20, false),
    TwitterEmoji(intArrayOf(0x1F4F7), arrayOf("camera"), 29, 17, false),
    TwitterEmoji(intArrayOf(0x1F4F8), arrayOf("camera_with_flash"), 29, 18, false),
    TwitterEmoji(intArrayOf(0x1F4F9), arrayOf("video_camera"), 29, 19, false),
    TwitterEmoji(intArrayOf(0x1F4FC), arrayOf("vhs"), 29, 22, false),
    TwitterEmoji(intArrayOf(0x1F50D), arrayOf("mag"), 29, 38, false),
    TwitterEmoji(intArrayOf(0x1F50E), arrayOf("mag_right"), 29, 39, false),
    TwitterEmoji(intArrayOf(0x1F56F, 0xFE0F), arrayOf("candle"), 30, 56, false),
    TwitterEmoji(intArrayOf(0x1F4A1), arrayOf("bulb"), 27, 48, false),
    TwitterEmoji(intArrayOf(0x1F526), arrayOf("flashlight"), 30, 2, false),
    TwitterEmoji(intArrayOf(0x1F3EE), arrayOf("izakaya_lantern", "lantern"), 10, 25, false),
    TwitterEmoji(intArrayOf(0x1FA94), arrayOf("diya_lamp"), 54, 6, false),
    TwitterEmoji(intArrayOf(0x1F4D4), arrayOf("notebook_with_decorative_cover"), 28, 43, false),
    TwitterEmoji(intArrayOf(0x1F4D5), arrayOf("closed_book"), 28, 44, false),
    TwitterEmoji(intArrayOf(0x1F4D6), arrayOf("book", "open_book"), 28, 45, false),
    TwitterEmoji(intArrayOf(0x1F4D7), arrayOf("green_book"), 28, 46, false),
    TwitterEmoji(intArrayOf(0x1F4D8), arrayOf("blue_book"), 28, 47, false),
    TwitterEmoji(intArrayOf(0x1F4D9), arrayOf("orange_book"), 28, 48, false),
    TwitterEmoji(intArrayOf(0x1F4DA), arrayOf("books"), 28, 49, false),
    TwitterEmoji(intArrayOf(0x1F4D3), arrayOf("notebook"), 28, 42, false),
    TwitterEmoji(intArrayOf(0x1F4D2), arrayOf("ledger"), 28, 41, false),
    TwitterEmoji(intArrayOf(0x1F4C3), arrayOf("page_with_curl"), 28, 26, false),
    TwitterEmoji(intArrayOf(0x1F4DC), arrayOf("scroll"), 28, 51, false),
    TwitterEmoji(intArrayOf(0x1F4C4), arrayOf("page_facing_up"), 28, 27, false),
    TwitterEmoji(intArrayOf(0x1F4F0), arrayOf("newspaper"), 29, 10, false),
    TwitterEmoji(intArrayOf(0x1F5DE, 0xFE0F), arrayOf("rolled_up_newspaper"), 32, 8, false),
    TwitterEmoji(intArrayOf(0x1F4D1), arrayOf("bookmark_tabs"), 28, 40, false),
    TwitterEmoji(intArrayOf(0x1F516), arrayOf("bookmark"), 29, 47, false),
    TwitterEmoji(intArrayOf(0x1F3F7, 0xFE0F), arrayOf("label"), 10, 37, false),
    TwitterEmoji(intArrayOf(0x1F4B0), arrayOf("moneybag"), 28, 7, false),
    TwitterEmoji(intArrayOf(0x1FA99), arrayOf("coin"), 54, 11, false),
    TwitterEmoji(intArrayOf(0x1F4B4), arrayOf("yen"), 28, 11, false),
    TwitterEmoji(intArrayOf(0x1F4B5), arrayOf("dollar"), 28, 12, false),
    TwitterEmoji(intArrayOf(0x1F4B6), arrayOf("euro"), 28, 13, false),
    TwitterEmoji(intArrayOf(0x1F4B7), arrayOf("pound"), 28, 14, false),
    TwitterEmoji(intArrayOf(0x1F4B8), arrayOf("money_with_wings"), 28, 15, false),
    TwitterEmoji(intArrayOf(0x1F4B3), arrayOf("credit_card"), 28, 10, false),
    TwitterEmoji(intArrayOf(0x1F9FE), arrayOf("receipt"), 53, 44, false),
    TwitterEmoji(intArrayOf(0x1F4B9), arrayOf("chart"), 28, 16, false),
    TwitterEmoji(intArrayOf(0x2709, 0xFE0F), arrayOf("email", "envelope"), 58, 26, false),
    TwitterEmoji(intArrayOf(0x1F4E7), arrayOf("e-mail"), 29, 1, false),
    TwitterEmoji(intArrayOf(0x1F4E8), arrayOf("incoming_envelope"), 29, 2, false),
    TwitterEmoji(intArrayOf(0x1F4E9), arrayOf("envelope_with_arrow"), 29, 3, false),
    TwitterEmoji(intArrayOf(0x1F4E4), arrayOf("outbox_tray"), 28, 59, false),
    TwitterEmoji(intArrayOf(0x1F4E5), arrayOf("inbox_tray"), 28, 60, false),
    TwitterEmoji(intArrayOf(0x1F4E6), arrayOf("package"), 29, 0, false),
    TwitterEmoji(intArrayOf(0x1F4EB), arrayOf("mailbox"), 29, 5, false),
    TwitterEmoji(intArrayOf(0x1F4EA), arrayOf("mailbox_closed"), 29, 4, false),
    TwitterEmoji(intArrayOf(0x1F4EC), arrayOf("mailbox_with_mail"), 29, 6, false),
    TwitterEmoji(intArrayOf(0x1F4ED), arrayOf("mailbox_with_no_mail"), 29, 7, false),
    TwitterEmoji(intArrayOf(0x1F4EE), arrayOf("postbox"), 29, 8, false),
    TwitterEmoji(intArrayOf(0x1F5F3, 0xFE0F), arrayOf("ballot_box_with_ballot"), 32, 13, false),
    TwitterEmoji(intArrayOf(0x270F, 0xFE0F), arrayOf("pencil2"), 58, 51, false),
    TwitterEmoji(intArrayOf(0x2712, 0xFE0F), arrayOf("black_nib"), 58, 52, false),
  )
}
