/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object TravelAndPlacesCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(0x1F30D, arrayOf("earth_africa"), false),
    GoogleCompatEmoji(0x1F30E, arrayOf("earth_americas"), false),
    GoogleCompatEmoji(0x1F30F, arrayOf("earth_asia"), false),
    GoogleCompatEmoji(0x1F310, arrayOf("globe_with_meridians"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FA, 0xFE0F), arrayOf("world_map"), false),
    GoogleCompatEmoji(0x1F5FE, arrayOf("japan"), false),
    GoogleCompatEmoji(0x1F9ED, arrayOf("compass"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D4, 0xFE0F), arrayOf("snow_capped_mountain"), false),
    GoogleCompatEmoji(intArrayOf(0x26F0, 0xFE0F), arrayOf("mountain"), false),
    GoogleCompatEmoji(0x1F30B, arrayOf("volcano"), false),
    GoogleCompatEmoji(0x1F5FB, arrayOf("mount_fuji"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D5, 0xFE0F), arrayOf("camping"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D6, 0xFE0F), arrayOf("beach_with_umbrella"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DC, 0xFE0F), arrayOf("desert"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DD, 0xFE0F), arrayOf("desert_island"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DE, 0xFE0F), arrayOf("national_park"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DF, 0xFE0F), arrayOf("stadium"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DB, 0xFE0F), arrayOf("classical_building"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D7, 0xFE0F), arrayOf("building_construction"), false),
    GoogleCompatEmoji(0x1F9F1, arrayOf("bricks"), false),
    GoogleCompatEmoji(0x1FAA8, arrayOf("rock"), false),
    GoogleCompatEmoji(0x1FAB5, arrayOf("wood"), false),
    GoogleCompatEmoji(0x1F6D6, arrayOf("hut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D8, 0xFE0F), arrayOf("house_buildings"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DA, 0xFE0F), arrayOf("derelict_house_building"), false),
    GoogleCompatEmoji(0x1F3E0, arrayOf("house"), false),
    GoogleCompatEmoji(0x1F3E1, arrayOf("house_with_garden"), false),
    GoogleCompatEmoji(0x1F3E2, arrayOf("office"), false),
    GoogleCompatEmoji(0x1F3E3, arrayOf("post_office"), false),
    GoogleCompatEmoji(0x1F3E4, arrayOf("european_post_office"), false),
    GoogleCompatEmoji(0x1F3E5, arrayOf("hospital"), false),
    GoogleCompatEmoji(0x1F3E6, arrayOf("bank"), false),
    GoogleCompatEmoji(0x1F3E8, arrayOf("hotel"), false),
    GoogleCompatEmoji(0x1F3E9, arrayOf("love_hotel"), false),
    GoogleCompatEmoji(0x1F3EA, arrayOf("convenience_store"), false),
    GoogleCompatEmoji(0x1F3EB, arrayOf("school"), false),
    GoogleCompatEmoji(0x1F3EC, arrayOf("department_store"), false),
    GoogleCompatEmoji(0x1F3ED, arrayOf("factory"), false),
    GoogleCompatEmoji(0x1F3EF, arrayOf("japanese_castle"), false),
    GoogleCompatEmoji(0x1F3F0, arrayOf("european_castle"), false),
    GoogleCompatEmoji(0x1F492, arrayOf("wedding"), false),
    GoogleCompatEmoji(0x1F5FC, arrayOf("tokyo_tower"), false),
    GoogleCompatEmoji(0x1F5FD, arrayOf("statue_of_liberty"), false),
    GoogleCompatEmoji(0x26EA, arrayOf("church"), false),
    GoogleCompatEmoji(0x1F54C, arrayOf("mosque"), false),
    GoogleCompatEmoji(0x1F6D5, arrayOf("hindu_temple"), false),
    GoogleCompatEmoji(0x1F54D, arrayOf("synagogue"), false),
    GoogleCompatEmoji(intArrayOf(0x26E9, 0xFE0F), arrayOf("shinto_shrine"), false),
    GoogleCompatEmoji(0x1F54B, arrayOf("kaaba"), false),
    GoogleCompatEmoji(0x26F2, arrayOf("fountain"), false),
    GoogleCompatEmoji(0x26FA, arrayOf("tent"), false),
    GoogleCompatEmoji(0x1F301, arrayOf("foggy"), false),
    GoogleCompatEmoji(0x1F303, arrayOf("night_with_stars"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D9, 0xFE0F), arrayOf("cityscape"), false),
    GoogleCompatEmoji(0x1F304, arrayOf("sunrise_over_mountains"), false),
    GoogleCompatEmoji(0x1F305, arrayOf("sunrise"), false),
    GoogleCompatEmoji(0x1F306, arrayOf("city_sunset"), false),
    GoogleCompatEmoji(0x1F307, arrayOf("city_sunrise"), false),
    GoogleCompatEmoji(0x1F309, arrayOf("bridge_at_night"), false),
    GoogleCompatEmoji(intArrayOf(0x2668, 0xFE0F), arrayOf("hotsprings"), false),
    GoogleCompatEmoji(0x1F3A0, arrayOf("carousel_horse"), false),
    GoogleCompatEmoji(0x1F6DD, arrayOf("playground_slide"), false),
    GoogleCompatEmoji(0x1F3A1, arrayOf("ferris_wheel"), false),
    GoogleCompatEmoji(0x1F3A2, arrayOf("roller_coaster"), false),
    GoogleCompatEmoji(0x1F488, arrayOf("barber"), false),
    GoogleCompatEmoji(0x1F3AA, arrayOf("circus_tent"), false),
    GoogleCompatEmoji(0x1F682, arrayOf("steam_locomotive"), false),
    GoogleCompatEmoji(0x1F683, arrayOf("railway_car"), false),
    GoogleCompatEmoji(0x1F684, arrayOf("bullettrain_side"), false),
    GoogleCompatEmoji(0x1F685, arrayOf("bullettrain_front"), false),
    GoogleCompatEmoji(0x1F686, arrayOf("train2"), false),
    GoogleCompatEmoji(0x1F687, arrayOf("metro"), false),
    GoogleCompatEmoji(0x1F688, arrayOf("light_rail"), false),
    GoogleCompatEmoji(0x1F689, arrayOf("station"), false),
    GoogleCompatEmoji(0x1F68A, arrayOf("tram"), false),
    GoogleCompatEmoji(0x1F69D, arrayOf("monorail"), false),
    GoogleCompatEmoji(0x1F69E, arrayOf("mountain_railway"), false),
    GoogleCompatEmoji(0x1F68B, arrayOf("train"), false),
    GoogleCompatEmoji(0x1F68C, arrayOf("bus"), false),
    GoogleCompatEmoji(0x1F68D, arrayOf("oncoming_bus"), false),
    GoogleCompatEmoji(0x1F68E, arrayOf("trolleybus"), false),
    GoogleCompatEmoji(0x1F690, arrayOf("minibus"), false),
    GoogleCompatEmoji(0x1F691, arrayOf("ambulance"), false),
    GoogleCompatEmoji(0x1F692, arrayOf("fire_engine"), false),
    GoogleCompatEmoji(0x1F693, arrayOf("police_car"), false),
    GoogleCompatEmoji(0x1F694, arrayOf("oncoming_police_car"), false),
    GoogleCompatEmoji(0x1F695, arrayOf("taxi"), false),
    GoogleCompatEmoji(0x1F696, arrayOf("oncoming_taxi"), false),
    GoogleCompatEmoji(0x1F697, arrayOf("car", "red_car"), false),
    GoogleCompatEmoji(0x1F698, arrayOf("oncoming_automobile"), false),
    GoogleCompatEmoji(0x1F699, arrayOf("blue_car"), false),
    GoogleCompatEmoji(0x1F6FB, arrayOf("pickup_truck"), false),
    GoogleCompatEmoji(0x1F69A, arrayOf("truck"), false),
    GoogleCompatEmoji(0x1F69B, arrayOf("articulated_lorry"), false),
    GoogleCompatEmoji(0x1F69C, arrayOf("tractor"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3CE, 0xFE0F), arrayOf("racing_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3CD, 0xFE0F), arrayOf("racing_motorcycle"), false),
    GoogleCompatEmoji(0x1F6F5, arrayOf("motor_scooter"), false),
    GoogleCompatEmoji(0x1F9BD, arrayOf("manual_wheelchair"), false),
    GoogleCompatEmoji(0x1F9BC, arrayOf("motorized_wheelchair"), false),
    GoogleCompatEmoji(0x1F6FA, arrayOf("auto_rickshaw"), false),
    GoogleCompatEmoji(0x1F6B2, arrayOf("bike"), false),
    GoogleCompatEmoji(0x1F6F4, arrayOf("scooter"), false),
    GoogleCompatEmoji(0x1F6F9, arrayOf("skateboard"), false),
    GoogleCompatEmoji(0x1F6FC, arrayOf("roller_skate"), false),
    GoogleCompatEmoji(0x1F68F, arrayOf("busstop"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E3, 0xFE0F), arrayOf("motorway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E4, 0xFE0F), arrayOf("railway_track"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E2, 0xFE0F), arrayOf("oil_drum"), false),
    GoogleCompatEmoji(0x26FD, arrayOf("fuelpump"), false),
    GoogleCompatEmoji(0x1F6DE, arrayOf("wheel"), false),
    GoogleCompatEmoji(0x1F6A8, arrayOf("rotating_light"), false),
    GoogleCompatEmoji(0x1F6A5, arrayOf("traffic_light"), false),
    GoogleCompatEmoji(0x1F6A6, arrayOf("vertical_traffic_light"), false),
    GoogleCompatEmoji(0x1F6D1, arrayOf("octagonal_sign"), false),
    GoogleCompatEmoji(0x1F6A7, arrayOf("construction"), false),
    GoogleCompatEmoji(0x2693, arrayOf("anchor"), false),
    GoogleCompatEmoji(0x1F6DF, arrayOf("ring_buoy"), false),
    GoogleCompatEmoji(0x26F5, arrayOf("boat", "sailboat"), false),
    GoogleCompatEmoji(0x1F6F6, arrayOf("canoe"), false),
    GoogleCompatEmoji(0x1F6A4, arrayOf("speedboat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F3, 0xFE0F), arrayOf("passenger_ship"), false),
    GoogleCompatEmoji(intArrayOf(0x26F4, 0xFE0F), arrayOf("ferry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E5, 0xFE0F), arrayOf("motor_boat"), false),
    GoogleCompatEmoji(0x1F6A2, arrayOf("ship"), false),
    GoogleCompatEmoji(intArrayOf(0x2708, 0xFE0F), arrayOf("airplane"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E9, 0xFE0F), arrayOf("small_airplane"), false),
    GoogleCompatEmoji(0x1F6EB, arrayOf("airplane_departure"), false),
    GoogleCompatEmoji(0x1F6EC, arrayOf("airplane_arriving"), false),
    GoogleCompatEmoji(0x1FA82, arrayOf("parachute"), false),
    GoogleCompatEmoji(0x1F4BA, arrayOf("seat"), false),
    GoogleCompatEmoji(0x1F681, arrayOf("helicopter"), false),
    GoogleCompatEmoji(0x1F69F, arrayOf("suspension_railway"), false),
    GoogleCompatEmoji(0x1F6A0, arrayOf("mountain_cableway"), false),
    GoogleCompatEmoji(0x1F6A1, arrayOf("aerial_tramway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F0, 0xFE0F), arrayOf("satellite"), false),
    GoogleCompatEmoji(0x1F680, arrayOf("rocket"), false),
    GoogleCompatEmoji(0x1F6F8, arrayOf("flying_saucer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CE, 0xFE0F), arrayOf("bellhop_bell"), false),
    GoogleCompatEmoji(0x1F9F3, arrayOf("luggage"), false),
    GoogleCompatEmoji(0x231B, arrayOf("hourglass"), false),
    GoogleCompatEmoji(0x23F3, arrayOf("hourglass_flowing_sand"), false),
    GoogleCompatEmoji(0x231A, arrayOf("watch"), false),
    GoogleCompatEmoji(0x23F0, arrayOf("alarm_clock"), false),
    GoogleCompatEmoji(intArrayOf(0x23F1, 0xFE0F), arrayOf("stopwatch"), false),
    GoogleCompatEmoji(intArrayOf(0x23F2, 0xFE0F), arrayOf("timer_clock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F570, 0xFE0F), arrayOf("mantelpiece_clock"), false),
    GoogleCompatEmoji(0x1F55B, arrayOf("clock12"), false),
    GoogleCompatEmoji(0x1F567, arrayOf("clock1230"), false),
    GoogleCompatEmoji(0x1F550, arrayOf("clock1"), false),
    GoogleCompatEmoji(0x1F55C, arrayOf("clock130"), false),
    GoogleCompatEmoji(0x1F551, arrayOf("clock2"), false),
    GoogleCompatEmoji(0x1F55D, arrayOf("clock230"), false),
    GoogleCompatEmoji(0x1F552, arrayOf("clock3"), false),
    GoogleCompatEmoji(0x1F55E, arrayOf("clock330"), false),
    GoogleCompatEmoji(0x1F553, arrayOf("clock4"), false),
    GoogleCompatEmoji(0x1F55F, arrayOf("clock430"), false),
    GoogleCompatEmoji(0x1F554, arrayOf("clock5"), false),
    GoogleCompatEmoji(0x1F560, arrayOf("clock530"), false),
    GoogleCompatEmoji(0x1F555, arrayOf("clock6"), false),
    GoogleCompatEmoji(0x1F561, arrayOf("clock630"), false),
    GoogleCompatEmoji(0x1F556, arrayOf("clock7"), false),
    GoogleCompatEmoji(0x1F562, arrayOf("clock730"), false),
    GoogleCompatEmoji(0x1F557, arrayOf("clock8"), false),
    GoogleCompatEmoji(0x1F563, arrayOf("clock830"), false),
    GoogleCompatEmoji(0x1F558, arrayOf("clock9"), false),
    GoogleCompatEmoji(0x1F564, arrayOf("clock930"), false),
    GoogleCompatEmoji(0x1F559, arrayOf("clock10"), false),
    GoogleCompatEmoji(0x1F565, arrayOf("clock1030"), false),
    GoogleCompatEmoji(0x1F55A, arrayOf("clock11"), false),
    GoogleCompatEmoji(0x1F566, arrayOf("clock1130"), false),
    GoogleCompatEmoji(0x1F311, arrayOf("new_moon"), false),
    GoogleCompatEmoji(0x1F312, arrayOf("waxing_crescent_moon"), false),
    GoogleCompatEmoji(0x1F313, arrayOf("first_quarter_moon"), false),
    GoogleCompatEmoji(0x1F314, arrayOf("moon", "waxing_gibbous_moon"), false),
    GoogleCompatEmoji(0x1F315, arrayOf("full_moon"), false),
    GoogleCompatEmoji(0x1F316, arrayOf("waning_gibbous_moon"), false),
    GoogleCompatEmoji(0x1F317, arrayOf("last_quarter_moon"), false),
    GoogleCompatEmoji(0x1F318, arrayOf("waning_crescent_moon"), false),
    GoogleCompatEmoji(0x1F319, arrayOf("crescent_moon"), false),
    GoogleCompatEmoji(0x1F31A, arrayOf("new_moon_with_face"), false),
    GoogleCompatEmoji(0x1F31B, arrayOf("first_quarter_moon_with_face"), false),
    GoogleCompatEmoji(0x1F31C, arrayOf("last_quarter_moon_with_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F321, 0xFE0F), arrayOf("thermometer"), false),
    GoogleCompatEmoji(intArrayOf(0x2600, 0xFE0F), arrayOf("sunny"), false),
    GoogleCompatEmoji(0x1F31D, arrayOf("full_moon_with_face"), false),
    GoogleCompatEmoji(0x1F31E, arrayOf("sun_with_face"), false),
    GoogleCompatEmoji(0x1FA90, arrayOf("ringed_planet"), false),
    GoogleCompatEmoji(
      0x2B50, arrayOf("star"), false,
      GoogleCompatEmoji(intArrayOf(0x2B50, 0xFE0F), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(0x1F31F, arrayOf("star2"), false),
    GoogleCompatEmoji(0x1F320, arrayOf("stars"), false),
    GoogleCompatEmoji(0x1F30C, arrayOf("milky_way"), false),
    GoogleCompatEmoji(intArrayOf(0x2601, 0xFE0F), arrayOf("cloud"), false),
    GoogleCompatEmoji(0x26C5, arrayOf("partly_sunny"), false),
    GoogleCompatEmoji(intArrayOf(0x26C8, 0xFE0F), arrayOf("thunder_cloud_and_rain"), false),
    GoogleCompatEmoji(intArrayOf(0x1F324, 0xFE0F), arrayOf("mostly_sunny", "sun_small_cloud"), false),
    GoogleCompatEmoji(intArrayOf(0x1F325, 0xFE0F), arrayOf("barely_sunny", "sun_behind_cloud"), false),
    GoogleCompatEmoji(intArrayOf(0x1F326, 0xFE0F), arrayOf("partly_sunny_rain", "sun_behind_rain_cloud"), false),
    GoogleCompatEmoji(intArrayOf(0x1F327, 0xFE0F), arrayOf("rain_cloud"), false),
    GoogleCompatEmoji(intArrayOf(0x1F328, 0xFE0F), arrayOf("snow_cloud"), false),
  )
}
