/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.twitter.category;

import com.vanniktech.emoji.twitter.TwitterEmoji;

final class ObjectsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static TwitterEmoji[] get() {
    return new TwitterEmoji[] {
      new TwitterEmoji(0x1F453, new String[]{"eyeglasses"}, 13, 15, false),
      new TwitterEmoji(new int[] { 0x1F576, 0xFE0F }, new String[]{"dark_sunglasses"}, 31, 22, false),
      new TwitterEmoji(0x1F97D, new String[]{"goggles"}, 44, 15, false),
      new TwitterEmoji(0x1F97C, new String[]{"lab_coat"}, 44, 14, false),
      new TwitterEmoji(0x1F9BA, new String[]{"safety_vest"}, 45, 55, false),
      new TwitterEmoji(0x1F454, new String[]{"necktie"}, 13, 16, false),
      new TwitterEmoji(0x1F455, new String[]{"shirt", "tshirt"}, 13, 17, false),
      new TwitterEmoji(0x1F456, new String[]{"jeans"}, 13, 18, false),
      new TwitterEmoji(0x1F9E3, new String[]{"scarf"}, 53, 17, false),
      new TwitterEmoji(0x1F9E4, new String[]{"gloves"}, 53, 18, false),
      new TwitterEmoji(0x1F9E5, new String[]{"coat"}, 53, 19, false),
      new TwitterEmoji(0x1F9E6, new String[]{"socks"}, 53, 20, false),
      new TwitterEmoji(0x1F457, new String[]{"dress"}, 13, 19, false),
      new TwitterEmoji(0x1F458, new String[]{"kimono"}, 13, 20, false),
      new TwitterEmoji(0x1F97B, new String[]{"sari"}, 44, 13, false),
      new TwitterEmoji(0x1FA71, new String[]{"one-piece_swimsuit"}, 53, 47, false),
      new TwitterEmoji(0x1FA72, new String[]{"briefs"}, 53, 48, false),
      new TwitterEmoji(0x1FA73, new String[]{"shorts"}, 53, 49, false),
      new TwitterEmoji(0x1F459, new String[]{"bikini"}, 13, 21, false),
      new TwitterEmoji(0x1F45A, new String[]{"womans_clothes"}, 13, 22, false),
      new TwitterEmoji(0x1F45B, new String[]{"purse"}, 13, 23, false),
      new TwitterEmoji(0x1F45C, new String[]{"handbag"}, 13, 24, false),
      new TwitterEmoji(0x1F45D, new String[]{"pouch"}, 13, 25, false),
      new TwitterEmoji(new int[] { 0x1F6CD, 0xFE0F }, new String[]{"shopping_bags"}, 37, 60, false),
      new TwitterEmoji(0x1F392, new String[]{"school_satchel"}, 7, 26, false),
      new TwitterEmoji(0x1FA74, new String[]{"thong_sandal"}, 53, 50, false),
      new TwitterEmoji(0x1F45E, new String[]{"mans_shoe", "shoe"}, 13, 26, false),
      new TwitterEmoji(0x1F45F, new String[]{"athletic_shoe"}, 13, 27, false),
      new TwitterEmoji(0x1F97E, new String[]{"hiking_boot"}, 44, 16, false),
      new TwitterEmoji(0x1F97F, new String[]{"womans_flat_shoe"}, 44, 17, false),
      new TwitterEmoji(0x1F460, new String[]{"high_heel"}, 13, 28, false),
      new TwitterEmoji(0x1F461, new String[]{"sandal"}, 13, 29, false),
      new TwitterEmoji(0x1FA70, new String[]{"ballet_shoes"}, 53, 46, false),
      new TwitterEmoji(0x1F462, new String[]{"boot"}, 13, 30, false),
      new TwitterEmoji(0x1F451, new String[]{"crown"}, 13, 13, false),
      new TwitterEmoji(0x1F452, new String[]{"womans_hat"}, 13, 14, false),
      new TwitterEmoji(0x1F3A9, new String[]{"tophat"}, 7, 44, false),
      new TwitterEmoji(0x1F393, new String[]{"mortar_board"}, 7, 27, false),
      new TwitterEmoji(0x1F9E2, new String[]{"billed_cap"}, 53, 16, false),
      new TwitterEmoji(0x1FA96, new String[]{"military_helmet"}, 54, 8, false),
      new TwitterEmoji(new int[] { 0x26D1, 0xFE0F }, new String[]{"helmet_with_white_cross"}, 57, 51, false),
      new TwitterEmoji(0x1F4FF, new String[]{"prayer_beads"}, 29, 24, false),
      new TwitterEmoji(0x1F484, new String[]{"lipstick"}, 25, 52, false),
      new TwitterEmoji(0x1F48D, new String[]{"ring"}, 26, 39, false),
      new TwitterEmoji(0x1F48E, new String[]{"gem"}, 26, 40, false),
      new TwitterEmoji(0x1F507, new String[]{"mute"}, 29, 32, false),
      new TwitterEmoji(0x1F508, new String[]{"speaker"}, 29, 33, false),
      new TwitterEmoji(0x1F509, new String[]{"sound"}, 29, 34, false),
      new TwitterEmoji(0x1F50A, new String[]{"loud_sound"}, 29, 35, false),
      new TwitterEmoji(0x1F4E2, new String[]{"loudspeaker"}, 28, 57, false),
      new TwitterEmoji(0x1F4E3, new String[]{"mega"}, 28, 58, false),
      new TwitterEmoji(0x1F4EF, new String[]{"postal_horn"}, 29, 9, false),
      new TwitterEmoji(0x1F514, new String[]{"bell"}, 29, 45, false),
      new TwitterEmoji(0x1F515, new String[]{"no_bell"}, 29, 46, false),
      new TwitterEmoji(0x1F3BC, new String[]{"musical_score"}, 8, 2, false),
      new TwitterEmoji(0x1F3B5, new String[]{"musical_note"}, 7, 56, false),
      new TwitterEmoji(0x1F3B6, new String[]{"notes"}, 7, 57, false),
      new TwitterEmoji(new int[] { 0x1F399, 0xFE0F }, new String[]{"studio_microphone"}, 7, 30, false),
      new TwitterEmoji(new int[] { 0x1F39A, 0xFE0F }, new String[]{"level_slider"}, 7, 31, false),
      new TwitterEmoji(new int[] { 0x1F39B, 0xFE0F }, new String[]{"control_knobs"}, 7, 32, false),
      new TwitterEmoji(0x1F3A4, new String[]{"microphone"}, 7, 39, false),
      new TwitterEmoji(0x1F3A7, new String[]{"headphones"}, 7, 42, false),
      new TwitterEmoji(0x1F4FB, new String[]{"radio"}, 29, 21, false),
      new TwitterEmoji(0x1F3B7, new String[]{"saxophone"}, 7, 58, false),
      new TwitterEmoji(0x1FA97, new String[]{"accordion"}, 54, 9, false),
      new TwitterEmoji(0x1F3B8, new String[]{"guitar"}, 7, 59, false),
      new TwitterEmoji(0x1F3B9, new String[]{"musical_keyboard"}, 7, 60, false),
      new TwitterEmoji(0x1F3BA, new String[]{"trumpet"}, 8, 0, false),
      new TwitterEmoji(0x1F3BB, new String[]{"violin"}, 8, 1, false),
      new TwitterEmoji(0x1FA95, new String[]{"banjo"}, 54, 7, false),
      new TwitterEmoji(0x1F941, new String[]{"drum_with_drumsticks"}, 43, 12, false),
      new TwitterEmoji(0x1FA98, new String[]{"long_drum"}, 54, 10, false),
      new TwitterEmoji(0x1F4F1, new String[]{"iphone"}, 29, 11, false),
      new TwitterEmoji(0x1F4F2, new String[]{"calling"}, 29, 12, false),
      new TwitterEmoji(new int[] { 0x260E, 0xFE0F }, new String[]{"phone", "telephone"}, 56, 45, false),
      new TwitterEmoji(0x1F4DE, new String[]{"telephone_receiver"}, 28, 53, false),
      new TwitterEmoji(0x1F4DF, new String[]{"pager"}, 28, 54, false),
      new TwitterEmoji(0x1F4E0, new String[]{"fax"}, 28, 55, false),
      new TwitterEmoji(0x1F50B, new String[]{"battery"}, 29, 36, false),
      new TwitterEmoji(0x1FAAB, new String[]{"low_battery"}, 54, 29, false),
      new TwitterEmoji(0x1F50C, new String[]{"electric_plug"}, 29, 37, false),
      new TwitterEmoji(0x1F4BB, new String[]{"computer"}, 28, 18, false),
      new TwitterEmoji(new int[] { 0x1F5A5, 0xFE0F }, new String[]{"desktop_computer"}, 31, 56, false),
      new TwitterEmoji(new int[] { 0x1F5A8, 0xFE0F }, new String[]{"printer"}, 31, 57, false),
      new TwitterEmoji(new int[] { 0x2328, 0xFE0F }, new String[]{"keyboard"}, 56, 15, false),
      new TwitterEmoji(new int[] { 0x1F5B1, 0xFE0F }, new String[]{"three_button_mouse"}, 31, 58, false),
      new TwitterEmoji(new int[] { 0x1F5B2, 0xFE0F }, new String[]{"trackball"}, 31, 59, false),
      new TwitterEmoji(0x1F4BD, new String[]{"minidisc"}, 28, 20, false),
      new TwitterEmoji(0x1F4BE, new String[]{"floppy_disk"}, 28, 21, false),
      new TwitterEmoji(0x1F4BF, new String[]{"cd"}, 28, 22, false),
      new TwitterEmoji(0x1F4C0, new String[]{"dvd"}, 28, 23, false),
      new TwitterEmoji(0x1F9EE, new String[]{"abacus"}, 53, 28, false),
      new TwitterEmoji(0x1F3A5, new String[]{"movie_camera"}, 7, 40, false),
      new TwitterEmoji(new int[] { 0x1F39E, 0xFE0F }, new String[]{"film_frames"}, 7, 33, false),
      new TwitterEmoji(new int[] { 0x1F4FD, 0xFE0F }, new String[]{"film_projector"}, 29, 23, false),
      new TwitterEmoji(0x1F3AC, new String[]{"clapper"}, 7, 47, false),
      new TwitterEmoji(0x1F4FA, new String[]{"tv"}, 29, 20, false),
      new TwitterEmoji(0x1F4F7, new String[]{"camera"}, 29, 17, false),
      new TwitterEmoji(0x1F4F8, new String[]{"camera_with_flash"}, 29, 18, false),
      new TwitterEmoji(0x1F4F9, new String[]{"video_camera"}, 29, 19, false),
      new TwitterEmoji(0x1F4FC, new String[]{"vhs"}, 29, 22, false),
      new TwitterEmoji(0x1F50D, new String[]{"mag"}, 29, 38, false),
      new TwitterEmoji(0x1F50E, new String[]{"mag_right"}, 29, 39, false),
      new TwitterEmoji(new int[] { 0x1F56F, 0xFE0F }, new String[]{"candle"}, 30, 56, false),
      new TwitterEmoji(0x1F4A1, new String[]{"bulb"}, 27, 48, false),
      new TwitterEmoji(0x1F526, new String[]{"flashlight"}, 30, 2, false),
      new TwitterEmoji(0x1F3EE, new String[]{"izakaya_lantern", "lantern"}, 10, 25, false),
      new TwitterEmoji(0x1FA94, new String[]{"diya_lamp"}, 54, 6, false),
      new TwitterEmoji(0x1F4D4, new String[]{"notebook_with_decorative_cover"}, 28, 43, false),
      new TwitterEmoji(0x1F4D5, new String[]{"closed_book"}, 28, 44, false),
      new TwitterEmoji(0x1F4D6, new String[]{"book", "open_book"}, 28, 45, false),
      new TwitterEmoji(0x1F4D7, new String[]{"green_book"}, 28, 46, false),
      new TwitterEmoji(0x1F4D8, new String[]{"blue_book"}, 28, 47, false),
      new TwitterEmoji(0x1F4D9, new String[]{"orange_book"}, 28, 48, false),
      new TwitterEmoji(0x1F4DA, new String[]{"books"}, 28, 49, false),
      new TwitterEmoji(0x1F4D3, new String[]{"notebook"}, 28, 42, false),
      new TwitterEmoji(0x1F4D2, new String[]{"ledger"}, 28, 41, false),
      new TwitterEmoji(0x1F4C3, new String[]{"page_with_curl"}, 28, 26, false),
      new TwitterEmoji(0x1F4DC, new String[]{"scroll"}, 28, 51, false),
      new TwitterEmoji(0x1F4C4, new String[]{"page_facing_up"}, 28, 27, false),
      new TwitterEmoji(0x1F4F0, new String[]{"newspaper"}, 29, 10, false),
      new TwitterEmoji(new int[] { 0x1F5DE, 0xFE0F }, new String[]{"rolled_up_newspaper"}, 32, 8, false),
      new TwitterEmoji(0x1F4D1, new String[]{"bookmark_tabs"}, 28, 40, false),
      new TwitterEmoji(0x1F516, new String[]{"bookmark"}, 29, 47, false),
      new TwitterEmoji(new int[] { 0x1F3F7, 0xFE0F }, new String[]{"label"}, 10, 37, false),
      new TwitterEmoji(0x1F4B0, new String[]{"moneybag"}, 28, 7, false),
      new TwitterEmoji(0x1FA99, new String[]{"coin"}, 54, 11, false),
      new TwitterEmoji(0x1F4B4, new String[]{"yen"}, 28, 11, false),
      new TwitterEmoji(0x1F4B5, new String[]{"dollar"}, 28, 12, false),
      new TwitterEmoji(0x1F4B6, new String[]{"euro"}, 28, 13, false),
      new TwitterEmoji(0x1F4B7, new String[]{"pound"}, 28, 14, false),
      new TwitterEmoji(0x1F4B8, new String[]{"money_with_wings"}, 28, 15, false),
      new TwitterEmoji(0x1F4B3, new String[]{"credit_card"}, 28, 10, false),
      new TwitterEmoji(0x1F9FE, new String[]{"receipt"}, 53, 44, false),
      new TwitterEmoji(0x1F4B9, new String[]{"chart"}, 28, 16, false),
      new TwitterEmoji(new int[] { 0x2709, 0xFE0F }, new String[]{"email", "envelope"}, 58, 26, false),
      new TwitterEmoji(0x1F4E7, new String[]{"e-mail"}, 29, 1, false),
      new TwitterEmoji(0x1F4E8, new String[]{"incoming_envelope"}, 29, 2, false),
      new TwitterEmoji(0x1F4E9, new String[]{"envelope_with_arrow"}, 29, 3, false),
      new TwitterEmoji(0x1F4E4, new String[]{"outbox_tray"}, 28, 59, false),
      new TwitterEmoji(0x1F4E5, new String[]{"inbox_tray"}, 28, 60, false),
      new TwitterEmoji(0x1F4E6, new String[]{"package"}, 29, 0, false),
      new TwitterEmoji(0x1F4EB, new String[]{"mailbox"}, 29, 5, false),
      new TwitterEmoji(0x1F4EA, new String[]{"mailbox_closed"}, 29, 4, false),
      new TwitterEmoji(0x1F4EC, new String[]{"mailbox_with_mail"}, 29, 6, false),
      new TwitterEmoji(0x1F4ED, new String[]{"mailbox_with_no_mail"}, 29, 7, false),
      new TwitterEmoji(0x1F4EE, new String[]{"postbox"}, 29, 8, false),
      new TwitterEmoji(new int[] { 0x1F5F3, 0xFE0F }, new String[]{"ballot_box_with_ballot"}, 32, 13, false),
      new TwitterEmoji(new int[] { 0x270F, 0xFE0F }, new String[]{"pencil2"}, 58, 51, false),
      new TwitterEmoji(new int[] { 0x2712, 0xFE0F }, new String[]{"black_nib"}, 58, 52, false),
      new TwitterEmoji(new int[] { 0x1F58B, 0xFE0F }, new String[]{"lower_left_fountain_pen"}, 31, 34, false),
      new TwitterEmoji(new int[] { 0x1F58A, 0xFE0F }, new String[]{"lower_left_ballpoint_pen"}, 31, 33, false),
      new TwitterEmoji(new int[] { 0x1F58C, 0xFE0F }, new String[]{"lower_left_paintbrush"}, 31, 35, false),
      new TwitterEmoji(new int[] { 0x1F58D, 0xFE0F }, new String[]{"lower_left_crayon"}, 31, 36, false),
      new TwitterEmoji(0x1F4DD, new String[]{"memo", "pencil"}, 28, 52, false),
      new TwitterEmoji(0x1F4BC, new String[]{"briefcase"}, 28, 19, false),
      new TwitterEmoji(0x1F4C1, new String[]{"file_folder"}, 28, 24, false),
      new TwitterEmoji(0x1F4C2, new String[]{"open_file_folder"}, 28, 25, false),
      new TwitterEmoji(new int[] { 0x1F5C2, 0xFE0F }, new String[]{"card_index_dividers"}, 32, 0, false),
      new TwitterEmoji(0x1F4C5, new String[]{"date"}, 28, 28, false),
      new TwitterEmoji(0x1F4C6, new String[]{"calendar"}, 28, 29, false),
      new TwitterEmoji(new int[] { 0x1F5D2, 0xFE0F }, new String[]{"spiral_note_pad"}, 32, 4, false),
      new TwitterEmoji(new int[] { 0x1F5D3, 0xFE0F }, new String[]{"spiral_calendar_pad"}, 32, 5, false),
      new TwitterEmoji(0x1F4C7, new String[]{"card_index"}, 28, 30, false),
      new TwitterEmoji(0x1F4C8, new String[]{"chart_with_upwards_trend"}, 28, 31, false),
      new TwitterEmoji(0x1F4C9, new String[]{"chart_with_downwards_trend"}, 28, 32, false),
      new TwitterEmoji(0x1F4CA, new String[]{"bar_chart"}, 28, 33, false),
      new TwitterEmoji(0x1F4CB, new String[]{"clipboard"}, 28, 34, false),
      new TwitterEmoji(0x1F4CC, new String[]{"pushpin"}, 28, 35, false),
      new TwitterEmoji(0x1F4CD, new String[]{"round_pushpin"}, 28, 36, false),
      new TwitterEmoji(0x1F4CE, new String[]{"paperclip"}, 28, 37, false),
      new TwitterEmoji(new int[] { 0x1F587, 0xFE0F }, new String[]{"linked_paperclips"}, 31, 32, false),
      new TwitterEmoji(0x1F4CF, new String[]{"straight_ruler"}, 28, 38, false),
      new TwitterEmoji(0x1F4D0, new String[]{"triangular_ruler"}, 28, 39, false),
      new TwitterEmoji(new int[] { 0x2702, 0xFE0F }, new String[]{"scissors"}, 58, 23, false),
      new TwitterEmoji(new int[] { 0x1F5C3, 0xFE0F }, new String[]{"card_file_box"}, 32, 1, false),
      new TwitterEmoji(new int[] { 0x1F5C4, 0xFE0F }, new String[]{"file_cabinet"}, 32, 2, false),
      new TwitterEmoji(new int[] { 0x1F5D1, 0xFE0F }, new String[]{"wastebasket"}, 32, 3, false),
      new TwitterEmoji(0x1F512, new String[]{"lock"}, 29, 43, false),
      new TwitterEmoji(0x1F513, new String[]{"unlock"}, 29, 44, false),
      new TwitterEmoji(0x1F50F, new String[]{"lock_with_ink_pen"}, 29, 40, false),
      new TwitterEmoji(0x1F510, new String[]{"closed_lock_with_key"}, 29, 41, false),
      new TwitterEmoji(0x1F511, new String[]{"key"}, 29, 42, false),
      new TwitterEmoji(new int[] { 0x1F5DD, 0xFE0F }, new String[]{"old_key"}, 32, 7, false),
      new TwitterEmoji(0x1F528, new String[]{"hammer"}, 30, 4, false),
      new TwitterEmoji(0x1FA93, new String[]{"axe"}, 54, 5, false),
      new TwitterEmoji(new int[] { 0x26CF, 0xFE0F }, new String[]{"pick"}, 57, 50, false),
      new TwitterEmoji(new int[] { 0x2692, 0xFE0F }, new String[]{"hammer_and_pick"}, 57, 28, false),
      new TwitterEmoji(new int[] { 0x1F6E0, 0xFE0F }, new String[]{"hammer_and_wrench"}, 38, 11, false),
      new TwitterEmoji(new int[] { 0x1F5E1, 0xFE0F }, new String[]{"dagger_knife"}, 32, 9, false),
      new TwitterEmoji(new int[] { 0x2694, 0xFE0F }, new String[]{"crossed_swords"}, 57, 30, false),
      new TwitterEmoji(0x1F52B, new String[]{"gun"}, 30, 7, false),
      new TwitterEmoji(0x1FA83, new String[]{"boomerang"}, 53, 59, false),
      new TwitterEmoji(0x1F3F9, new String[]{"bow_and_arrow"}, 10, 39, false),
      new TwitterEmoji(new int[] { 0x1F6E1, 0xFE0F }, new String[]{"shield"}, 38, 12, false),
      new TwitterEmoji(0x1FA9A, new String[]{"carpentry_saw"}, 54, 12, false),
      new TwitterEmoji(0x1F527, new String[]{"wrench"}, 30, 3, false),
      new TwitterEmoji(0x1FA9B, new String[]{"screwdriver"}, 54, 13, false),
      new TwitterEmoji(0x1F529, new String[]{"nut_and_bolt"}, 30, 5, false),
      new TwitterEmoji(new int[] { 0x2699, 0xFE0F }, new String[]{"gear"}, 57, 34, false)
    };
  }

  private ObjectsCategoryChunk0() {
    // No instances.
  }
}
