/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.facebook.category

import com.vanniktech.emoji.facebook.FacebookEmoji

internal object ObjectsCategoryChunk0 {
  val EMOJIS: Array<FacebookEmoji> = arrayOf(
    FacebookEmoji(intArrayOf(0x1F453), listOf("eyeglasses"), 13, 15, false),
    FacebookEmoji(intArrayOf(0x1F576, 0xFE0F), listOf("dark_sunglasses"), 31, 22, false),
    FacebookEmoji(intArrayOf(0x1F97D), listOf("goggles"), 44, 15, false),
    FacebookEmoji(intArrayOf(0x1F97C), listOf("lab_coat"), 44, 14, false),
    FacebookEmoji(intArrayOf(0x1F9BA), listOf("safety_vest"), 45, 55, false),
    FacebookEmoji(intArrayOf(0x1F454), listOf("necktie"), 13, 16, false),
    FacebookEmoji(intArrayOf(0x1F455), listOf("shirt", "tshirt"), 13, 17, false),
    FacebookEmoji(intArrayOf(0x1F456), listOf("jeans"), 13, 18, false),
    FacebookEmoji(intArrayOf(0x1F9E3), listOf("scarf"), 53, 17, false),
    FacebookEmoji(intArrayOf(0x1F9E4), listOf("gloves"), 53, 18, false),
    FacebookEmoji(intArrayOf(0x1F9E5), listOf("coat"), 53, 19, false),
    FacebookEmoji(intArrayOf(0x1F9E6), listOf("socks"), 53, 20, false),
    FacebookEmoji(intArrayOf(0x1F457), listOf("dress"), 13, 19, false),
    FacebookEmoji(intArrayOf(0x1F458), listOf("kimono"), 13, 20, false),
    FacebookEmoji(intArrayOf(0x1F97B), listOf("sari"), 44, 13, false),
    FacebookEmoji(intArrayOf(0x1FA71), listOf("one-piece_swimsuit"), 53, 47, false),
    FacebookEmoji(intArrayOf(0x1FA72), listOf("briefs"), 53, 48, false),
    FacebookEmoji(intArrayOf(0x1FA73), listOf("shorts"), 53, 49, false),
    FacebookEmoji(intArrayOf(0x1F459), listOf("bikini"), 13, 21, false),
    FacebookEmoji(intArrayOf(0x1F45A), listOf("womans_clothes"), 13, 22, false),
    FacebookEmoji(intArrayOf(0x1F45B), listOf("purse"), 13, 23, false),
    FacebookEmoji(intArrayOf(0x1F45C), listOf("handbag"), 13, 24, false),
    FacebookEmoji(intArrayOf(0x1F45D), listOf("pouch"), 13, 25, false),
    FacebookEmoji(intArrayOf(0x1F6CD, 0xFE0F), listOf("shopping_bags"), 37, 60, false),
    FacebookEmoji(intArrayOf(0x1F392), listOf("school_satchel"), 7, 26, false),
    FacebookEmoji(intArrayOf(0x1FA74), listOf("thong_sandal"), 53, 50, false),
    FacebookEmoji(intArrayOf(0x1F45E), listOf("mans_shoe", "shoe"), 13, 26, false),
    FacebookEmoji(intArrayOf(0x1F45F), listOf("athletic_shoe"), 13, 27, false),
    FacebookEmoji(intArrayOf(0x1F97E), listOf("hiking_boot"), 44, 16, false),
    FacebookEmoji(intArrayOf(0x1F97F), listOf("womans_flat_shoe"), 44, 17, false),
    FacebookEmoji(intArrayOf(0x1F460), listOf("high_heel"), 13, 28, false),
    FacebookEmoji(intArrayOf(0x1F461), listOf("sandal"), 13, 29, false),
    FacebookEmoji(intArrayOf(0x1FA70), listOf("ballet_shoes"), 53, 46, false),
    FacebookEmoji(intArrayOf(0x1F462), listOf("boot"), 13, 30, false),
    FacebookEmoji(intArrayOf(0x1F451), listOf("crown"), 13, 13, false),
    FacebookEmoji(intArrayOf(0x1F452), listOf("womans_hat"), 13, 14, false),
    FacebookEmoji(intArrayOf(0x1F3A9), listOf("tophat"), 7, 44, false),
    FacebookEmoji(intArrayOf(0x1F393), listOf("mortar_board"), 7, 27, false),
    FacebookEmoji(intArrayOf(0x1F9E2), listOf("billed_cap"), 53, 16, false),
    FacebookEmoji(intArrayOf(0x1FA96), listOf("military_helmet"), 54, 8, false),
    FacebookEmoji(intArrayOf(0x26D1, 0xFE0F), listOf("helmet_with_white_cross"), 57, 51, false),
    FacebookEmoji(intArrayOf(0x1F4FF), listOf("prayer_beads"), 29, 24, false),
    FacebookEmoji(intArrayOf(0x1F484), listOf("lipstick"), 25, 52, false),
    FacebookEmoji(intArrayOf(0x1F48D), listOf("ring"), 26, 39, false),
    FacebookEmoji(intArrayOf(0x1F48E), listOf("gem"), 26, 40, false),
    FacebookEmoji(intArrayOf(0x1F507), listOf("mute"), 29, 32, false),
    FacebookEmoji(intArrayOf(0x1F508), listOf("speaker"), 29, 33, false),
    FacebookEmoji(intArrayOf(0x1F509), listOf("sound"), 29, 34, false),
    FacebookEmoji(intArrayOf(0x1F50A), listOf("loud_sound"), 29, 35, false),
    FacebookEmoji(intArrayOf(0x1F4E2), listOf("loudspeaker"), 28, 57, false),
    FacebookEmoji(intArrayOf(0x1F4E3), listOf("mega"), 28, 58, false),
    FacebookEmoji(intArrayOf(0x1F4EF), listOf("postal_horn"), 29, 9, false),
    FacebookEmoji(intArrayOf(0x1F514), listOf("bell"), 29, 45, false),
    FacebookEmoji(intArrayOf(0x1F515), listOf("no_bell"), 29, 46, false),
    FacebookEmoji(intArrayOf(0x1F3BC), listOf("musical_score"), 8, 2, false),
    FacebookEmoji(intArrayOf(0x1F3B5), listOf("musical_note"), 7, 56, false),
    FacebookEmoji(intArrayOf(0x1F3B6), listOf("notes"), 7, 57, false),
    FacebookEmoji(intArrayOf(0x1F399, 0xFE0F), listOf("studio_microphone"), 7, 30, false),
    FacebookEmoji(intArrayOf(0x1F39A, 0xFE0F), listOf("level_slider"), 7, 31, false),
    FacebookEmoji(intArrayOf(0x1F39B, 0xFE0F), listOf("control_knobs"), 7, 32, false),
    FacebookEmoji(intArrayOf(0x1F3A4), listOf("microphone"), 7, 39, false),
    FacebookEmoji(intArrayOf(0x1F3A7), listOf("headphones"), 7, 42, false),
    FacebookEmoji(intArrayOf(0x1F4FB), listOf("radio"), 29, 21, false),
    FacebookEmoji(intArrayOf(0x1F3B7), listOf("saxophone"), 7, 58, false),
    FacebookEmoji(intArrayOf(0x1FA97), listOf("accordion"), 54, 9, false),
    FacebookEmoji(intArrayOf(0x1F3B8), listOf("guitar"), 7, 59, false),
    FacebookEmoji(intArrayOf(0x1F3B9), listOf("musical_keyboard"), 7, 60, false),
    FacebookEmoji(intArrayOf(0x1F3BA), listOf("trumpet"), 8, 0, false),
    FacebookEmoji(intArrayOf(0x1F3BB), listOf("violin"), 8, 1, false),
    FacebookEmoji(intArrayOf(0x1FA95), listOf("banjo"), 54, 7, false),
    FacebookEmoji(intArrayOf(0x1F941), listOf("drum_with_drumsticks"), 43, 12, false),
    FacebookEmoji(intArrayOf(0x1FA98), listOf("long_drum"), 54, 10, false),
    FacebookEmoji(intArrayOf(0x1F4F1), listOf("iphone"), 29, 11, false),
    FacebookEmoji(intArrayOf(0x1F4F2), listOf("calling"), 29, 12, false),
    FacebookEmoji(intArrayOf(0x260E, 0xFE0F), listOf("phone", "telephone"), 56, 45, false),
    FacebookEmoji(intArrayOf(0x1F4DE), listOf("telephone_receiver"), 28, 53, false),
    FacebookEmoji(intArrayOf(0x1F4DF), listOf("pager"), 28, 54, false),
    FacebookEmoji(intArrayOf(0x1F4E0), listOf("fax"), 28, 55, false),
    FacebookEmoji(intArrayOf(0x1F50B), listOf("battery"), 29, 36, false),
    FacebookEmoji(intArrayOf(0x1F50C), listOf("electric_plug"), 29, 37, false),
    FacebookEmoji(intArrayOf(0x1F4BB), listOf("computer"), 28, 18, false),
    FacebookEmoji(intArrayOf(0x1F5A5, 0xFE0F), listOf("desktop_computer"), 31, 56, false),
    FacebookEmoji(intArrayOf(0x1F5A8, 0xFE0F), listOf("printer"), 31, 57, false),
    FacebookEmoji(intArrayOf(0x2328, 0xFE0F), listOf("keyboard"), 56, 15, false),
    FacebookEmoji(intArrayOf(0x1F5B1, 0xFE0F), listOf("three_button_mouse"), 31, 58, false),
    FacebookEmoji(intArrayOf(0x1F5B2, 0xFE0F), listOf("trackball"), 31, 59, false),
    FacebookEmoji(intArrayOf(0x1F4BD), listOf("minidisc"), 28, 20, false),
    FacebookEmoji(intArrayOf(0x1F4BE), listOf("floppy_disk"), 28, 21, false),
    FacebookEmoji(intArrayOf(0x1F4BF), listOf("cd"), 28, 22, false),
    FacebookEmoji(intArrayOf(0x1F4C0), listOf("dvd"), 28, 23, false),
    FacebookEmoji(intArrayOf(0x1F9EE), listOf("abacus"), 53, 28, false),
    FacebookEmoji(intArrayOf(0x1F3A5), listOf("movie_camera"), 7, 40, false),
    FacebookEmoji(intArrayOf(0x1F39E, 0xFE0F), listOf("film_frames"), 7, 33, false),
    FacebookEmoji(intArrayOf(0x1F4FD, 0xFE0F), listOf("film_projector"), 29, 23, false),
    FacebookEmoji(intArrayOf(0x1F3AC), listOf("clapper"), 7, 47, false),
    FacebookEmoji(intArrayOf(0x1F4FA), listOf("tv"), 29, 20, false),
    FacebookEmoji(intArrayOf(0x1F4F7), listOf("camera"), 29, 17, false),
    FacebookEmoji(intArrayOf(0x1F4F8), listOf("camera_with_flash"), 29, 18, false),
    FacebookEmoji(intArrayOf(0x1F4F9), listOf("video_camera"), 29, 19, false),
    FacebookEmoji(intArrayOf(0x1F4FC), listOf("vhs"), 29, 22, false),
    FacebookEmoji(intArrayOf(0x1F50D), listOf("mag"), 29, 38, false),
    FacebookEmoji(intArrayOf(0x1F50E), listOf("mag_right"), 29, 39, false),
    FacebookEmoji(intArrayOf(0x1F56F, 0xFE0F), listOf("candle"), 30, 56, false),
    FacebookEmoji(intArrayOf(0x1F4A1), listOf("bulb"), 27, 48, false),
    FacebookEmoji(intArrayOf(0x1F526), listOf("flashlight"), 30, 2, false),
    FacebookEmoji(intArrayOf(0x1F3EE), listOf("izakaya_lantern", "lantern"), 10, 25, false),
    FacebookEmoji(intArrayOf(0x1FA94), listOf("diya_lamp"), 54, 6, false),
    FacebookEmoji(intArrayOf(0x1F4D4), listOf("notebook_with_decorative_cover"), 28, 43, false),
    FacebookEmoji(intArrayOf(0x1F4D5), listOf("closed_book"), 28, 44, false),
    FacebookEmoji(intArrayOf(0x1F4D6), listOf("book", "open_book"), 28, 45, false),
    FacebookEmoji(intArrayOf(0x1F4D7), listOf("green_book"), 28, 46, false),
    FacebookEmoji(intArrayOf(0x1F4D8), listOf("blue_book"), 28, 47, false),
    FacebookEmoji(intArrayOf(0x1F4D9), listOf("orange_book"), 28, 48, false),
    FacebookEmoji(intArrayOf(0x1F4DA), listOf("books"), 28, 49, false),
    FacebookEmoji(intArrayOf(0x1F4D3), listOf("notebook"), 28, 42, false),
    FacebookEmoji(intArrayOf(0x1F4D2), listOf("ledger"), 28, 41, false),
    FacebookEmoji(intArrayOf(0x1F4C3), listOf("page_with_curl"), 28, 26, false),
    FacebookEmoji(intArrayOf(0x1F4DC), listOf("scroll"), 28, 51, false),
    FacebookEmoji(intArrayOf(0x1F4C4), listOf("page_facing_up"), 28, 27, false),
    FacebookEmoji(intArrayOf(0x1F4F0), listOf("newspaper"), 29, 10, false),
    FacebookEmoji(intArrayOf(0x1F5DE, 0xFE0F), listOf("rolled_up_newspaper"), 32, 8, false),
    FacebookEmoji(intArrayOf(0x1F4D1), listOf("bookmark_tabs"), 28, 40, false),
    FacebookEmoji(intArrayOf(0x1F516), listOf("bookmark"), 29, 47, false),
    FacebookEmoji(intArrayOf(0x1F3F7, 0xFE0F), listOf("label"), 10, 37, false),
    FacebookEmoji(intArrayOf(0x1F4B0), listOf("moneybag"), 28, 7, false),
    FacebookEmoji(intArrayOf(0x1FA99), listOf("coin"), 54, 11, false),
    FacebookEmoji(intArrayOf(0x1F4B4), listOf("yen"), 28, 11, false),
    FacebookEmoji(intArrayOf(0x1F4B5), listOf("dollar"), 28, 12, false),
    FacebookEmoji(intArrayOf(0x1F4B6), listOf("euro"), 28, 13, false),
    FacebookEmoji(intArrayOf(0x1F4B7), listOf("pound"), 28, 14, false),
    FacebookEmoji(intArrayOf(0x1F4B8), listOf("money_with_wings"), 28, 15, false),
    FacebookEmoji(intArrayOf(0x1F4B3), listOf("credit_card"), 28, 10, false),
    FacebookEmoji(intArrayOf(0x1F9FE), listOf("receipt"), 53, 44, false),
    FacebookEmoji(intArrayOf(0x1F4B9), listOf("chart"), 28, 16, false),
    FacebookEmoji(intArrayOf(0x2709, 0xFE0F), listOf("email", "envelope"), 58, 26, false),
    FacebookEmoji(intArrayOf(0x1F4E7), listOf("e-mail"), 29, 1, false),
    FacebookEmoji(intArrayOf(0x1F4E8), listOf("incoming_envelope"), 29, 2, false),
    FacebookEmoji(intArrayOf(0x1F4E9), listOf("envelope_with_arrow"), 29, 3, false),
    FacebookEmoji(intArrayOf(0x1F4E4), listOf("outbox_tray"), 28, 59, false),
    FacebookEmoji(intArrayOf(0x1F4E5), listOf("inbox_tray"), 28, 60, false),
    FacebookEmoji(intArrayOf(0x1F4E6), listOf("package"), 29, 0, false),
    FacebookEmoji(intArrayOf(0x1F4EB), listOf("mailbox"), 29, 5, false),
    FacebookEmoji(intArrayOf(0x1F4EA), listOf("mailbox_closed"), 29, 4, false),
    FacebookEmoji(intArrayOf(0x1F4EC), listOf("mailbox_with_mail"), 29, 6, false),
    FacebookEmoji(intArrayOf(0x1F4ED), listOf("mailbox_with_no_mail"), 29, 7, false),
    FacebookEmoji(intArrayOf(0x1F4EE), listOf("postbox"), 29, 8, false),
    FacebookEmoji(intArrayOf(0x1F5F3, 0xFE0F), listOf("ballot_box_with_ballot"), 32, 13, false),
    FacebookEmoji(intArrayOf(0x270F, 0xFE0F), listOf("pencil2"), 58, 51, false),
    FacebookEmoji(intArrayOf(0x2712, 0xFE0F), listOf("black_nib"), 58, 52, false),
    FacebookEmoji(intArrayOf(0x1F58B, 0xFE0F), listOf("lower_left_fountain_pen"), 31, 34, false),
  )
}
