/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.facebook.category

import com.vanniktech.emoji.facebook.FacebookEmoji

internal object TravelAndPlacesCategoryChunk0 {
  val EMOJIS: Array<FacebookEmoji> = arrayOf(
    FacebookEmoji(intArrayOf(0x1F30D), listOf("earth_africa"), 5, 12, false),
    FacebookEmoji(intArrayOf(0x1F30E), listOf("earth_americas"), 5, 13, false),
    FacebookEmoji(intArrayOf(0x1F30F), listOf("earth_asia"), 5, 14, false),
    FacebookEmoji(intArrayOf(0x1F310), listOf("globe_with_meridians"), 5, 15, false),
    FacebookEmoji(intArrayOf(0x1F5FA, 0xFE0F), listOf("world_map"), 32, 14, false),
    FacebookEmoji(intArrayOf(0x1F5FE), listOf("japan"), 32, 18, false),
    FacebookEmoji(intArrayOf(0x1F9ED), listOf("compass"), 53, 27, false),
    FacebookEmoji(intArrayOf(0x1F3D4, 0xFE0F), listOf("snow_capped_mountain"), 9, 60, false),
    FacebookEmoji(intArrayOf(0x26F0, 0xFE0F), listOf("mountain"), 57, 56, false),
    FacebookEmoji(intArrayOf(0x1F30B), listOf("volcano"), 5, 10, false),
    FacebookEmoji(intArrayOf(0x1F5FB), listOf("mount_fuji"), 32, 15, false),
    FacebookEmoji(intArrayOf(0x1F3D5, 0xFE0F), listOf("camping"), 10, 0, false),
    FacebookEmoji(intArrayOf(0x1F3D6, 0xFE0F), listOf("beach_with_umbrella"), 10, 1, false),
    FacebookEmoji(intArrayOf(0x1F3DC, 0xFE0F), listOf("desert"), 10, 7, false),
    FacebookEmoji(intArrayOf(0x1F3DD, 0xFE0F), listOf("desert_island"), 10, 8, false),
    FacebookEmoji(intArrayOf(0x1F3DE, 0xFE0F), listOf("national_park"), 10, 9, false),
    FacebookEmoji(intArrayOf(0x1F3DF, 0xFE0F), listOf("stadium"), 10, 10, false),
    FacebookEmoji(intArrayOf(0x1F3DB, 0xFE0F), listOf("classical_building"), 10, 6, false),
    FacebookEmoji(intArrayOf(0x1F3D7, 0xFE0F), listOf("building_construction"), 10, 2, false),
    FacebookEmoji(intArrayOf(0x1F9F1), listOf("bricks"), 53, 31, false),
    FacebookEmoji(intArrayOf(0x1FAA8), listOf("rock"), 54, 26, false),
    FacebookEmoji(intArrayOf(0x1FAB5), listOf("wood"), 54, 36, false),
    FacebookEmoji(intArrayOf(0x1F6D6), listOf("hut"), 38, 6, false),
    FacebookEmoji(intArrayOf(0x1F3D8, 0xFE0F), listOf("house_buildings"), 10, 3, false),
    FacebookEmoji(intArrayOf(0x1F3DA, 0xFE0F), listOf("derelict_house_building"), 10, 5, false),
    FacebookEmoji(intArrayOf(0x1F3E0), listOf("house"), 10, 11, false),
    FacebookEmoji(intArrayOf(0x1F3E1), listOf("house_with_garden"), 10, 12, false),
    FacebookEmoji(intArrayOf(0x1F3E2), listOf("office"), 10, 13, false),
    FacebookEmoji(intArrayOf(0x1F3E3), listOf("post_office"), 10, 14, false),
    FacebookEmoji(intArrayOf(0x1F3E4), listOf("european_post_office"), 10, 15, false),
    FacebookEmoji(intArrayOf(0x1F3E5), listOf("hospital"), 10, 16, false),
    FacebookEmoji(intArrayOf(0x1F3E6), listOf("bank"), 10, 17, false),
    FacebookEmoji(intArrayOf(0x1F3E8), listOf("hotel"), 10, 19, false),
    FacebookEmoji(intArrayOf(0x1F3E9), listOf("love_hotel"), 10, 20, false),
    FacebookEmoji(intArrayOf(0x1F3EA), listOf("convenience_store"), 10, 21, false),
    FacebookEmoji(intArrayOf(0x1F3EB), listOf("school"), 10, 22, false),
    FacebookEmoji(intArrayOf(0x1F3EC), listOf("department_store"), 10, 23, false),
    FacebookEmoji(intArrayOf(0x1F3ED), listOf("factory"), 10, 24, false),
    FacebookEmoji(intArrayOf(0x1F3EF), listOf("japanese_castle"), 10, 26, false),
    FacebookEmoji(intArrayOf(0x1F3F0), listOf("european_castle"), 10, 27, false),
    FacebookEmoji(intArrayOf(0x1F492), listOf("wedding"), 27, 33, false),
    FacebookEmoji(intArrayOf(0x1F5FC), listOf("tokyo_tower"), 32, 16, false),
    FacebookEmoji(intArrayOf(0x1F5FD), listOf("statue_of_liberty"), 32, 17, false),
    FacebookEmoji(intArrayOf(0x26EA), listOf("church"), 57, 55, false),
    FacebookEmoji(intArrayOf(0x1F54C), listOf("mosque"), 30, 29, false),
    FacebookEmoji(intArrayOf(0x1F6D5), listOf("hindu_temple"), 38, 5, false),
    FacebookEmoji(intArrayOf(0x1F54D), listOf("synagogue"), 30, 30, false),
    FacebookEmoji(intArrayOf(0x26E9, 0xFE0F), listOf("shinto_shrine"), 57, 54, false),
    FacebookEmoji(intArrayOf(0x1F54B), listOf("kaaba"), 30, 28, false),
    FacebookEmoji(intArrayOf(0x26F2), listOf("fountain"), 57, 58, false),
    FacebookEmoji(intArrayOf(0x26FA), listOf("tent"), 58, 21, false),
    FacebookEmoji(intArrayOf(0x1F301), listOf("foggy"), 5, 0, false),
    FacebookEmoji(intArrayOf(0x1F303), listOf("night_with_stars"), 5, 2, false),
    FacebookEmoji(intArrayOf(0x1F3D9, 0xFE0F), listOf("cityscape"), 10, 4, false),
    FacebookEmoji(intArrayOf(0x1F304), listOf("sunrise_over_mountains"), 5, 3, false),
    FacebookEmoji(intArrayOf(0x1F305), listOf("sunrise"), 5, 4, false),
    FacebookEmoji(intArrayOf(0x1F306), listOf("city_sunset"), 5, 5, false),
    FacebookEmoji(intArrayOf(0x1F307), listOf("city_sunrise"), 5, 6, false),
    FacebookEmoji(intArrayOf(0x1F309), listOf("bridge_at_night"), 5, 8, false),
    FacebookEmoji(intArrayOf(0x2668, 0xFE0F), listOf("hotsprings"), 57, 24, false),
    FacebookEmoji(intArrayOf(0x1F3A0), listOf("carousel_horse"), 7, 35, false),
    FacebookEmoji(intArrayOf(0x1F3A1), listOf("ferris_wheel"), 7, 36, false),
    FacebookEmoji(intArrayOf(0x1F3A2), listOf("roller_coaster"), 7, 37, false),
    FacebookEmoji(intArrayOf(0x1F488), listOf("barber"), 26, 34, false),
    FacebookEmoji(intArrayOf(0x1F3AA), listOf("circus_tent"), 7, 45, false),
    FacebookEmoji(intArrayOf(0x1F682), listOf("steam_locomotive"), 35, 34, false),
    FacebookEmoji(intArrayOf(0x1F683), listOf("railway_car"), 35, 35, false),
    FacebookEmoji(intArrayOf(0x1F684), listOf("bullettrain_side"), 35, 36, false),
    FacebookEmoji(intArrayOf(0x1F685), listOf("bullettrain_front"), 35, 37, false),
    FacebookEmoji(intArrayOf(0x1F686), listOf("train2"), 35, 38, false),
    FacebookEmoji(intArrayOf(0x1F687), listOf("metro"), 35, 39, false),
    FacebookEmoji(intArrayOf(0x1F688), listOf("light_rail"), 35, 40, false),
    FacebookEmoji(intArrayOf(0x1F689), listOf("station"), 35, 41, false),
    FacebookEmoji(intArrayOf(0x1F68A), listOf("tram"), 35, 42, false),
    FacebookEmoji(intArrayOf(0x1F69D), listOf("monorail"), 36, 0, false),
    FacebookEmoji(intArrayOf(0x1F69E), listOf("mountain_railway"), 36, 1, false),
    FacebookEmoji(intArrayOf(0x1F68B), listOf("train"), 35, 43, false),
    FacebookEmoji(intArrayOf(0x1F68C), listOf("bus"), 35, 44, false),
    FacebookEmoji(intArrayOf(0x1F68D), listOf("oncoming_bus"), 35, 45, false),
    FacebookEmoji(intArrayOf(0x1F68E), listOf("trolleybus"), 35, 46, false),
    FacebookEmoji(intArrayOf(0x1F690), listOf("minibus"), 35, 48, false),
    FacebookEmoji(intArrayOf(0x1F691), listOf("ambulance"), 35, 49, false),
    FacebookEmoji(intArrayOf(0x1F692), listOf("fire_engine"), 35, 50, false),
    FacebookEmoji(intArrayOf(0x1F693), listOf("police_car"), 35, 51, false),
    FacebookEmoji(intArrayOf(0x1F694), listOf("oncoming_police_car"), 35, 52, false),
    FacebookEmoji(intArrayOf(0x1F695), listOf("taxi"), 35, 53, false),
    FacebookEmoji(intArrayOf(0x1F696), listOf("oncoming_taxi"), 35, 54, false),
    FacebookEmoji(intArrayOf(0x1F697), listOf("car", "red_car"), 35, 55, false),
    FacebookEmoji(intArrayOf(0x1F698), listOf("oncoming_automobile"), 35, 56, false),
    FacebookEmoji(intArrayOf(0x1F699), listOf("blue_car"), 35, 57, false),
    FacebookEmoji(intArrayOf(0x1F6FB), listOf("pickup_truck"), 38, 29, false),
    FacebookEmoji(intArrayOf(0x1F69A), listOf("truck"), 35, 58, false),
    FacebookEmoji(intArrayOf(0x1F69B), listOf("articulated_lorry"), 35, 59, false),
    FacebookEmoji(intArrayOf(0x1F69C), listOf("tractor"), 35, 60, false),
    FacebookEmoji(intArrayOf(0x1F3CE, 0xFE0F), listOf("racing_car"), 9, 54, false),
    FacebookEmoji(intArrayOf(0x1F3CD, 0xFE0F), listOf("racing_motorcycle"), 9, 53, false),
    FacebookEmoji(intArrayOf(0x1F6F5), listOf("motor_scooter"), 38, 23, false),
    FacebookEmoji(intArrayOf(0x1F9BD), listOf("manual_wheelchair"), 46, 2, false),
    FacebookEmoji(intArrayOf(0x1F9BC), listOf("motorized_wheelchair"), 46, 1, false),
    FacebookEmoji(intArrayOf(0x1F6FA), listOf("auto_rickshaw"), 38, 28, false),
    FacebookEmoji(intArrayOf(0x1F6B2), listOf("bike"), 36, 38, false),
    FacebookEmoji(intArrayOf(0x1F6F4), listOf("scooter"), 38, 22, false),
    FacebookEmoji(intArrayOf(0x1F6F9), listOf("skateboard"), 38, 27, false),
    FacebookEmoji(intArrayOf(0x1F6FC), listOf("roller_skate"), 38, 30, false),
    FacebookEmoji(intArrayOf(0x1F68F), listOf("busstop"), 35, 47, false),
    FacebookEmoji(intArrayOf(0x1F6E3, 0xFE0F), listOf("motorway"), 38, 14, false),
    FacebookEmoji(intArrayOf(0x1F6E4, 0xFE0F), listOf("railway_track"), 38, 15, false),
    FacebookEmoji(intArrayOf(0x1F6E2, 0xFE0F), listOf("oil_drum"), 38, 13, false),
    FacebookEmoji(intArrayOf(0x26FD), listOf("fuelpump"), 58, 22, false),
    FacebookEmoji(intArrayOf(0x1F6A8), listOf("rotating_light"), 36, 28, false),
    FacebookEmoji(intArrayOf(0x1F6A5), listOf("traffic_light"), 36, 25, false),
    FacebookEmoji(intArrayOf(0x1F6A6), listOf("vertical_traffic_light"), 36, 26, false),
    FacebookEmoji(intArrayOf(0x1F6D1), listOf("octagonal_sign"), 38, 3, false),
    FacebookEmoji(intArrayOf(0x1F6A7), listOf("construction"), 36, 27, false),
    FacebookEmoji(intArrayOf(0x2693), listOf("anchor"), 57, 29, false),
    FacebookEmoji(intArrayOf(0x26F5), listOf("boat", "sailboat"), 58, 0, false),
    FacebookEmoji(intArrayOf(0x1F6F6), listOf("canoe"), 38, 24, false),
    FacebookEmoji(intArrayOf(0x1F6A4), listOf("speedboat"), 36, 24, false),
    FacebookEmoji(intArrayOf(0x1F6F3, 0xFE0F), listOf("passenger_ship"), 38, 21, false),
    FacebookEmoji(intArrayOf(0x26F4, 0xFE0F), listOf("ferry"), 57, 60, false),
    FacebookEmoji(intArrayOf(0x1F6E5, 0xFE0F), listOf("motor_boat"), 38, 16, false),
    FacebookEmoji(intArrayOf(0x1F6A2), listOf("ship"), 36, 5, false),
    FacebookEmoji(intArrayOf(0x2708, 0xFE0F), listOf("airplane"), 58, 25, false),
    FacebookEmoji(intArrayOf(0x1F6E9, 0xFE0F), listOf("small_airplane"), 38, 17, false),
    FacebookEmoji(intArrayOf(0x1F6EB), listOf("airplane_departure"), 38, 18, false),
    FacebookEmoji(intArrayOf(0x1F6EC), listOf("airplane_arriving"), 38, 19, false),
    FacebookEmoji(intArrayOf(0x1FA82), listOf("parachute"), 53, 58, false),
    FacebookEmoji(intArrayOf(0x1F4BA), listOf("seat"), 28, 17, false),
    FacebookEmoji(intArrayOf(0x1F681), listOf("helicopter"), 35, 33, false),
    FacebookEmoji(intArrayOf(0x1F69F), listOf("suspension_railway"), 36, 2, false),
    FacebookEmoji(intArrayOf(0x1F6A0), listOf("mountain_cableway"), 36, 3, false),
    FacebookEmoji(intArrayOf(0x1F6A1), listOf("aerial_tramway"), 36, 4, false),
    FacebookEmoji(intArrayOf(0x1F6F0, 0xFE0F), listOf("satellite"), 38, 20, false),
    FacebookEmoji(intArrayOf(0x1F680), listOf("rocket"), 35, 32, false),
    FacebookEmoji(intArrayOf(0x1F6F8), listOf("flying_saucer"), 38, 26, false),
    FacebookEmoji(intArrayOf(0x1F6CE, 0xFE0F), listOf("bellhop_bell"), 38, 0, false),
    FacebookEmoji(intArrayOf(0x1F9F3), listOf("luggage"), 53, 33, false),
    FacebookEmoji(intArrayOf(0x231B), listOf("hourglass"), 56, 14, false),
    FacebookEmoji(intArrayOf(0x23F3), listOf("hourglass_flowing_sand"), 56, 27, false),
    FacebookEmoji(intArrayOf(0x231A), listOf("watch"), 56, 13, false),
    FacebookEmoji(intArrayOf(0x23F0), listOf("alarm_clock"), 56, 24, false),
    FacebookEmoji(intArrayOf(0x23F1, 0xFE0F), listOf("stopwatch"), 56, 25, false),
    FacebookEmoji(intArrayOf(0x23F2, 0xFE0F), listOf("timer_clock"), 56, 26, false),
    FacebookEmoji(intArrayOf(0x1F570, 0xFE0F), listOf("mantelpiece_clock"), 30, 57, false),
    FacebookEmoji(intArrayOf(0x1F55B), listOf("clock12"), 30, 43, false),
    FacebookEmoji(intArrayOf(0x1F567), listOf("clock1230"), 30, 55, false),
    FacebookEmoji(intArrayOf(0x1F550), listOf("clock1"), 30, 32, false),
    FacebookEmoji(intArrayOf(0x1F55C), listOf("clock130"), 30, 44, false),
    FacebookEmoji(intArrayOf(0x1F551), listOf("clock2"), 30, 33, false),
    FacebookEmoji(intArrayOf(0x1F55D), listOf("clock230"), 30, 45, false),
  )
}
