/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object AnimalsAndNatureCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F435), 0, 1), listOf("monkey_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F412), 0, 1), listOf("monkey"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98D), 0, 1), listOf("gorilla"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A7), 0, 1), listOf("orangutan"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F436), 0, 1), listOf("dog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F415), 0, 1), listOf("dog2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AE), 0, 1), listOf("guide_dog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F415, 0x200D, 0x1F9BA), 0, 3), listOf("service_dog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F429), 0, 1), listOf("poodle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43A), 0, 1), listOf("wolf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98A), 0, 1), listOf("fox_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99D), 0, 1), listOf("raccoon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F431), 0, 1), listOf("cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F408), 0, 1), listOf("cat2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F408, 0x200D, 0x2B1B), 0, 3), listOf("black_cat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F981), 0, 1), listOf("lion_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42F), 0, 1), listOf("tiger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F405), 0, 1), listOf("tiger2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F406), 0, 1), listOf("leopard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F434), 0, 1), listOf("horse"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40E), 0, 1), listOf("racehorse"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F984), 0, 1), listOf("unicorn_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F993), 0, 1), listOf("zebra_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98C), 0, 1), listOf("deer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AC), 0, 1), listOf("bison"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42E), 0, 1), listOf("cow"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F402), 0, 1), listOf("ox"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F403), 0, 1), listOf("water_buffalo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F404), 0, 1), listOf("cow2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F437), 0, 1), listOf("pig"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F416), 0, 1), listOf("pig2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F417), 0, 1), listOf("boar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43D), 0, 1), listOf("pig_nose"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40F), 0, 1), listOf("ram"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F411), 0, 1), listOf("sheep"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F410), 0, 1), listOf("goat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42A), 0, 1), listOf("dromedary_camel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42B), 0, 1), listOf("camel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F999), 0, 1), listOf("llama"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F992), 0, 1), listOf("giraffe_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F418), 0, 1), listOf("elephant"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A3), 0, 1), listOf("mammoth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98F), 0, 1), listOf("rhinoceros"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99B), 0, 1), listOf("hippopotamus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42D), 0, 1), listOf("mouse"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F401), 0, 1), listOf("mouse2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F400), 0, 1), listOf("rat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F439), 0, 1), listOf("hamster"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F430), 0, 1), listOf("rabbit"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F407), 0, 1), listOf("rabbit2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43F, 0xFE0F), 0, 2), listOf("chipmunk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AB), 0, 1), listOf("beaver"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F994), 0, 1), listOf("hedgehog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F987), 0, 1), listOf("bat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43B), 0, 1), listOf("bear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43B, 0x200D, 0x2744, 0xFE0F), 0, 4), listOf("polar_bear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F428), 0, 1), listOf("koala"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43C), 0, 1), listOf("panda_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A5), 0, 1), listOf("sloth"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A6), 0, 1), listOf("otter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A8), 0, 1), listOf("skunk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F998), 0, 1), listOf("kangaroo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A1), 0, 1), listOf("badger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F43E), 0, 1), listOf("feet", "paw_prints"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F983), 0, 1), listOf("turkey"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F414), 0, 1), listOf("chicken"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F413), 0, 1), listOf("rooster"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F423), 0, 1), listOf("hatching_chick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F424), 0, 1), listOf("baby_chick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F425), 0, 1), listOf("hatched_chick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F426), 0, 1), listOf("bird"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F427), 0, 1), listOf("penguin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F54A, 0xFE0F), 0, 2), listOf("dove_of_peace"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F985), 0, 1), listOf("eagle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F986), 0, 1), listOf("duck"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A2), 0, 1), listOf("swan"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F989), 0, 1), listOf("owl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A4), 0, 1), listOf("dodo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB6), 0, 1), listOf("feather"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A9), 0, 1), listOf("flamingo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99A), 0, 1), listOf("peacock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99C), 0, 1), listOf("parrot"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F438), 0, 1), listOf("frog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40A), 0, 1), listOf("crocodile"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F422), 0, 1), listOf("turtle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98E), 0, 1), listOf("lizard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40D), 0, 1), listOf("snake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F432), 0, 1), listOf("dragon_face"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F409), 0, 1), listOf("dragon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F995), 0, 1), listOf("sauropod"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F996), 0, 1), listOf("t-rex"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F433), 0, 1), listOf("whale"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40B), 0, 1), listOf("whale2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F42C), 0, 1), listOf("dolphin", "flipper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AD), 0, 1), listOf("seal"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41F), 0, 1), listOf("fish"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F420), 0, 1), listOf("tropical_fish"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F421), 0, 1), listOf("blowfish"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F988), 0, 1), listOf("shark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F419), 0, 1), listOf("octopus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41A), 0, 1), listOf("shell"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB8), 0, 1), listOf("coral"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F40C), 0, 1), listOf("snail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F98B), 0, 1), listOf("butterfly"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41B), 0, 1), listOf("bug"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41C), 0, 1), listOf("ant"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41D), 0, 1), listOf("bee", "honeybee"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB2), 0, 1), listOf("beetle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F41E), 0, 1), listOf("ladybug", "lady_beetle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F997), 0, 1), listOf("cricket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB3), 0, 1), listOf("cockroach"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F577, 0xFE0F), 0, 2), listOf("spider"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F578, 0xFE0F), 0, 2), listOf("spider_web"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F982), 0, 1), listOf("scorpion"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99F), 0, 1), listOf("mosquito"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB0), 0, 1), listOf("fly"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB1), 0, 1), listOf("worm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9A0), 0, 1), listOf("microbe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F490), 0, 1), listOf("bouquet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F338), 0, 1), listOf("cherry_blossom"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4AE), 0, 1), listOf("white_flower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB7), 0, 1), listOf("lotus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F5, 0xFE0F), 0, 2), listOf("rosette"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F339), 0, 1), listOf("rose"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F940), 0, 1), listOf("wilted_flower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33A), 0, 1), listOf("hibiscus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33B), 0, 1), listOf("sunflower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33C), 0, 1), listOf("blossom"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F337), 0, 1), listOf("tulip"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F331), 0, 1), listOf("seedling"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB4), 0, 1), listOf("potted_plant"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F332), 0, 1), listOf("evergreen_tree"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F333), 0, 1), listOf("deciduous_tree"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F334), 0, 1), listOf("palm_tree"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F335), 0, 1), listOf("cactus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33E), 0, 1), listOf("ear_of_rice"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33F), 0, 1), listOf("herb"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2618, 0xFE0F), 0, 2), listOf("shamrock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F340), 0, 1), listOf("four_leaf_clover"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F341), 0, 1), listOf("maple_leaf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F342), 0, 1), listOf("fallen_leaf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F343), 0, 1), listOf("leaves"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAB9), 0, 1), listOf("empty_nest"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FABA), 0, 1), listOf("nest_with_eggs"), false),
  )
}
