/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object AnimalsAndNatureCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(0x1F435, arrayOf("monkey_face"), false),
    GoogleCompatEmoji(0x1F412, arrayOf("monkey"), false),
    GoogleCompatEmoji(0x1F98D, arrayOf("gorilla"), false),
    GoogleCompatEmoji(0x1F9A7, arrayOf("orangutan"), false),
    GoogleCompatEmoji(0x1F436, arrayOf("dog"), false),
    GoogleCompatEmoji(0x1F415, arrayOf("dog2"), false),
    GoogleCompatEmoji(0x1F9AE, arrayOf("guide_dog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F415, 0x200D, 0x1F9BA), arrayOf("service_dog"), false),
    GoogleCompatEmoji(0x1F429, arrayOf("poodle"), false),
    GoogleCompatEmoji(0x1F43A, arrayOf("wolf"), false),
    GoogleCompatEmoji(0x1F98A, arrayOf("fox_face"), false),
    GoogleCompatEmoji(0x1F99D, arrayOf("raccoon"), false),
    GoogleCompatEmoji(0x1F431, arrayOf("cat"), false),
    GoogleCompatEmoji(0x1F408, arrayOf("cat2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F408, 0x200D, 0x2B1B), arrayOf("black_cat"), false),
    GoogleCompatEmoji(0x1F981, arrayOf("lion_face"), false),
    GoogleCompatEmoji(0x1F42F, arrayOf("tiger"), false),
    GoogleCompatEmoji(0x1F405, arrayOf("tiger2"), false),
    GoogleCompatEmoji(0x1F406, arrayOf("leopard"), false),
    GoogleCompatEmoji(0x1F434, arrayOf("horse"), false),
    GoogleCompatEmoji(0x1F40E, arrayOf("racehorse"), false),
    GoogleCompatEmoji(0x1F984, arrayOf("unicorn_face"), false),
    GoogleCompatEmoji(0x1F993, arrayOf("zebra_face"), false),
    GoogleCompatEmoji(0x1F98C, arrayOf("deer"), false),
    GoogleCompatEmoji(0x1F9AC, arrayOf("bison"), false),
    GoogleCompatEmoji(0x1F42E, arrayOf("cow"), false),
    GoogleCompatEmoji(0x1F402, arrayOf("ox"), false),
    GoogleCompatEmoji(0x1F403, arrayOf("water_buffalo"), false),
    GoogleCompatEmoji(0x1F404, arrayOf("cow2"), false),
    GoogleCompatEmoji(0x1F437, arrayOf("pig"), false),
    GoogleCompatEmoji(0x1F416, arrayOf("pig2"), false),
    GoogleCompatEmoji(0x1F417, arrayOf("boar"), false),
    GoogleCompatEmoji(0x1F43D, arrayOf("pig_nose"), false),
    GoogleCompatEmoji(0x1F40F, arrayOf("ram"), false),
    GoogleCompatEmoji(0x1F411, arrayOf("sheep"), false),
    GoogleCompatEmoji(0x1F410, arrayOf("goat"), false),
    GoogleCompatEmoji(0x1F42A, arrayOf("dromedary_camel"), false),
    GoogleCompatEmoji(0x1F42B, arrayOf("camel"), false),
    GoogleCompatEmoji(0x1F999, arrayOf("llama"), false),
    GoogleCompatEmoji(0x1F992, arrayOf("giraffe_face"), false),
    GoogleCompatEmoji(0x1F418, arrayOf("elephant"), false),
    GoogleCompatEmoji(0x1F9A3, arrayOf("mammoth"), false),
    GoogleCompatEmoji(0x1F98F, arrayOf("rhinoceros"), false),
    GoogleCompatEmoji(0x1F99B, arrayOf("hippopotamus"), false),
    GoogleCompatEmoji(0x1F42D, arrayOf("mouse"), false),
    GoogleCompatEmoji(0x1F401, arrayOf("mouse2"), false),
    GoogleCompatEmoji(0x1F400, arrayOf("rat"), false),
    GoogleCompatEmoji(0x1F439, arrayOf("hamster"), false),
    GoogleCompatEmoji(0x1F430, arrayOf("rabbit"), false),
    GoogleCompatEmoji(0x1F407, arrayOf("rabbit2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43F, 0xFE0F), arrayOf("chipmunk"), false),
    GoogleCompatEmoji(0x1F9AB, arrayOf("beaver"), false),
    GoogleCompatEmoji(0x1F994, arrayOf("hedgehog"), false),
    GoogleCompatEmoji(0x1F987, arrayOf("bat"), false),
    GoogleCompatEmoji(0x1F43B, arrayOf("bear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43B, 0x200D, 0x2744, 0xFE0F), arrayOf("polar_bear"), false),
    GoogleCompatEmoji(0x1F428, arrayOf("koala"), false),
    GoogleCompatEmoji(0x1F43C, arrayOf("panda_face"), false),
    GoogleCompatEmoji(0x1F9A5, arrayOf("sloth"), false),
    GoogleCompatEmoji(0x1F9A6, arrayOf("otter"), false),
    GoogleCompatEmoji(0x1F9A8, arrayOf("skunk"), false),
    GoogleCompatEmoji(0x1F998, arrayOf("kangaroo"), false),
    GoogleCompatEmoji(0x1F9A1, arrayOf("badger"), false),
    GoogleCompatEmoji(0x1F43E, arrayOf("feet", "paw_prints"), false),
    GoogleCompatEmoji(0x1F983, arrayOf("turkey"), false),
    GoogleCompatEmoji(0x1F414, arrayOf("chicken"), false),
    GoogleCompatEmoji(0x1F413, arrayOf("rooster"), false),
    GoogleCompatEmoji(0x1F423, arrayOf("hatching_chick"), false),
    GoogleCompatEmoji(0x1F424, arrayOf("baby_chick"), false),
    GoogleCompatEmoji(0x1F425, arrayOf("hatched_chick"), false),
    GoogleCompatEmoji(0x1F426, arrayOf("bird"), false),
    GoogleCompatEmoji(0x1F427, arrayOf("penguin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54A, 0xFE0F), arrayOf("dove_of_peace"), false),
    GoogleCompatEmoji(0x1F985, arrayOf("eagle"), false),
    GoogleCompatEmoji(0x1F986, arrayOf("duck"), false),
    GoogleCompatEmoji(0x1F9A2, arrayOf("swan"), false),
    GoogleCompatEmoji(0x1F989, arrayOf("owl"), false),
    GoogleCompatEmoji(0x1F9A4, arrayOf("dodo"), false),
    GoogleCompatEmoji(0x1FAB6, arrayOf("feather"), false),
    GoogleCompatEmoji(0x1F9A9, arrayOf("flamingo"), false),
    GoogleCompatEmoji(0x1F99A, arrayOf("peacock"), false),
    GoogleCompatEmoji(0x1F99C, arrayOf("parrot"), false),
    GoogleCompatEmoji(0x1F438, arrayOf("frog"), false),
    GoogleCompatEmoji(0x1F40A, arrayOf("crocodile"), false),
    GoogleCompatEmoji(0x1F422, arrayOf("turtle"), false),
    GoogleCompatEmoji(0x1F98E, arrayOf("lizard"), false),
    GoogleCompatEmoji(0x1F40D, arrayOf("snake"), false),
    GoogleCompatEmoji(0x1F432, arrayOf("dragon_face"), false),
    GoogleCompatEmoji(0x1F409, arrayOf("dragon"), false),
    GoogleCompatEmoji(0x1F995, arrayOf("sauropod"), false),
    GoogleCompatEmoji(0x1F996, arrayOf("t-rex"), false),
    GoogleCompatEmoji(0x1F433, arrayOf("whale"), false),
    GoogleCompatEmoji(0x1F40B, arrayOf("whale2"), false),
    GoogleCompatEmoji(0x1F42C, arrayOf("dolphin", "flipper"), false),
    GoogleCompatEmoji(0x1F9AD, arrayOf("seal"), false),
    GoogleCompatEmoji(0x1F41F, arrayOf("fish"), false),
    GoogleCompatEmoji(0x1F420, arrayOf("tropical_fish"), false),
    GoogleCompatEmoji(0x1F421, arrayOf("blowfish"), false),
    GoogleCompatEmoji(0x1F988, arrayOf("shark"), false),
    GoogleCompatEmoji(0x1F419, arrayOf("octopus"), false),
    GoogleCompatEmoji(0x1F41A, arrayOf("shell"), false),
    GoogleCompatEmoji(0x1FAB8, arrayOf("coral"), false),
    GoogleCompatEmoji(0x1F40C, arrayOf("snail"), false),
    GoogleCompatEmoji(0x1F98B, arrayOf("butterfly"), false),
    GoogleCompatEmoji(0x1F41B, arrayOf("bug"), false),
    GoogleCompatEmoji(0x1F41C, arrayOf("ant"), false),
    GoogleCompatEmoji(0x1F41D, arrayOf("bee", "honeybee"), false),
    GoogleCompatEmoji(0x1FAB2, arrayOf("beetle"), false),
    GoogleCompatEmoji(0x1F41E, arrayOf("ladybug", "lady_beetle"), false),
    GoogleCompatEmoji(0x1F997, arrayOf("cricket"), false),
    GoogleCompatEmoji(0x1FAB3, arrayOf("cockroach"), false),
    GoogleCompatEmoji(intArrayOf(0x1F577, 0xFE0F), arrayOf("spider"), false),
    GoogleCompatEmoji(intArrayOf(0x1F578, 0xFE0F), arrayOf("spider_web"), false),
    GoogleCompatEmoji(0x1F982, arrayOf("scorpion"), false),
    GoogleCompatEmoji(0x1F99F, arrayOf("mosquito"), false),
    GoogleCompatEmoji(0x1FAB0, arrayOf("fly"), false),
    GoogleCompatEmoji(0x1FAB1, arrayOf("worm"), false),
    GoogleCompatEmoji(0x1F9A0, arrayOf("microbe"), false),
    GoogleCompatEmoji(0x1F490, arrayOf("bouquet"), false),
    GoogleCompatEmoji(0x1F338, arrayOf("cherry_blossom"), false),
    GoogleCompatEmoji(0x1F4AE, arrayOf("white_flower"), false),
    GoogleCompatEmoji(0x1FAB7, arrayOf("lotus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F5, 0xFE0F), arrayOf("rosette"), false),
    GoogleCompatEmoji(0x1F339, arrayOf("rose"), false),
    GoogleCompatEmoji(0x1F940, arrayOf("wilted_flower"), false),
    GoogleCompatEmoji(0x1F33A, arrayOf("hibiscus"), false),
    GoogleCompatEmoji(0x1F33B, arrayOf("sunflower"), false),
    GoogleCompatEmoji(0x1F33C, arrayOf("blossom"), false),
    GoogleCompatEmoji(0x1F337, arrayOf("tulip"), false),
    GoogleCompatEmoji(0x1F331, arrayOf("seedling"), false),
    GoogleCompatEmoji(0x1FAB4, arrayOf("potted_plant"), false),
    GoogleCompatEmoji(0x1F332, arrayOf("evergreen_tree"), false),
    GoogleCompatEmoji(0x1F333, arrayOf("deciduous_tree"), false),
    GoogleCompatEmoji(0x1F334, arrayOf("palm_tree"), false),
    GoogleCompatEmoji(0x1F335, arrayOf("cactus"), false),
    GoogleCompatEmoji(0x1F33E, arrayOf("ear_of_rice"), false),
    GoogleCompatEmoji(0x1F33F, arrayOf("herb"), false),
    GoogleCompatEmoji(intArrayOf(0x2618, 0xFE0F), arrayOf("shamrock"), false),
    GoogleCompatEmoji(0x1F340, arrayOf("four_leaf_clover"), false),
    GoogleCompatEmoji(0x1F341, arrayOf("maple_leaf"), false),
    GoogleCompatEmoji(0x1F342, arrayOf("fallen_leaf"), false),
    GoogleCompatEmoji(0x1F343, arrayOf("leaves"), false),
    GoogleCompatEmoji(0x1FAB9, arrayOf("empty_nest"), false),
    GoogleCompatEmoji(0x1FABA, arrayOf("nest_with_eggs"), false),
  )
}
