/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object AnimalsAndNatureCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F435), listOf("monkey_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F412), listOf("monkey"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98D), listOf("gorilla"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A7), listOf("orangutan"), false),
    GoogleCompatEmoji(intArrayOf(0x1F436), listOf("dog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F415), listOf("dog2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AE), listOf("guide_dog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F415, 0x200D, 0x1F9BA), listOf("service_dog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F429), listOf("poodle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43A), listOf("wolf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98A), listOf("fox_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99D), listOf("raccoon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F431), listOf("cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F408), listOf("cat2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F408, 0x200D, 0x2B1B), listOf("black_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F981), listOf("lion_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42F), listOf("tiger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F405), listOf("tiger2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F406), listOf("leopard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F434), listOf("horse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40E), listOf("racehorse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F984), listOf("unicorn_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F993), listOf("zebra_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98C), listOf("deer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AC), listOf("bison"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42E), listOf("cow"), false),
    GoogleCompatEmoji(intArrayOf(0x1F402), listOf("ox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F403), listOf("water_buffalo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F404), listOf("cow2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F437), listOf("pig"), false),
    GoogleCompatEmoji(intArrayOf(0x1F416), listOf("pig2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F417), listOf("boar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43D), listOf("pig_nose"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40F), listOf("ram"), false),
    GoogleCompatEmoji(intArrayOf(0x1F411), listOf("sheep"), false),
    GoogleCompatEmoji(intArrayOf(0x1F410), listOf("goat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42A), listOf("dromedary_camel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42B), listOf("camel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F999), listOf("llama"), false),
    GoogleCompatEmoji(intArrayOf(0x1F992), listOf("giraffe_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F418), listOf("elephant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A3), listOf("mammoth"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98F), listOf("rhinoceros"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99B), listOf("hippopotamus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42D), listOf("mouse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F401), listOf("mouse2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F400), listOf("rat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F439), listOf("hamster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F430), listOf("rabbit"), false),
    GoogleCompatEmoji(intArrayOf(0x1F407), listOf("rabbit2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43F, 0xFE0F), listOf("chipmunk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AB), listOf("beaver"), false),
    GoogleCompatEmoji(intArrayOf(0x1F994), listOf("hedgehog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F987), listOf("bat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43B), listOf("bear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43B, 0x200D, 0x2744, 0xFE0F), listOf("polar_bear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F428), listOf("koala"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43C), listOf("panda_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A5), listOf("sloth"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A6), listOf("otter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A8), listOf("skunk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F998), listOf("kangaroo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A1), listOf("badger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F43E), listOf("feet", "paw_prints"), false),
    GoogleCompatEmoji(intArrayOf(0x1F983), listOf("turkey"), false),
    GoogleCompatEmoji(intArrayOf(0x1F414), listOf("chicken"), false),
    GoogleCompatEmoji(intArrayOf(0x1F413), listOf("rooster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F423), listOf("hatching_chick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F424), listOf("baby_chick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F425), listOf("hatched_chick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F426), listOf("bird"), false),
    GoogleCompatEmoji(intArrayOf(0x1F427), listOf("penguin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54A, 0xFE0F), listOf("dove_of_peace"), false),
    GoogleCompatEmoji(intArrayOf(0x1F985), listOf("eagle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F986), listOf("duck"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A2), listOf("swan"), false),
    GoogleCompatEmoji(intArrayOf(0x1F989), listOf("owl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A4), listOf("dodo"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB6), listOf("feather"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A9), listOf("flamingo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99A), listOf("peacock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99C), listOf("parrot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F438), listOf("frog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40A), listOf("crocodile"), false),
    GoogleCompatEmoji(intArrayOf(0x1F422), listOf("turtle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98E), listOf("lizard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40D), listOf("snake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F432), listOf("dragon_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F409), listOf("dragon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F995), listOf("sauropod"), false),
    GoogleCompatEmoji(intArrayOf(0x1F996), listOf("t-rex"), false),
    GoogleCompatEmoji(intArrayOf(0x1F433), listOf("whale"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40B), listOf("whale2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F42C), listOf("dolphin", "flipper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AD), listOf("seal"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41F), listOf("fish"), false),
    GoogleCompatEmoji(intArrayOf(0x1F420), listOf("tropical_fish"), false),
    GoogleCompatEmoji(intArrayOf(0x1F421), listOf("blowfish"), false),
    GoogleCompatEmoji(intArrayOf(0x1F988), listOf("shark"), false),
    GoogleCompatEmoji(intArrayOf(0x1F419), listOf("octopus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41A), listOf("shell"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB8), listOf("coral"), false),
    GoogleCompatEmoji(intArrayOf(0x1F40C), listOf("snail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F98B), listOf("butterfly"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41B), listOf("bug"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41C), listOf("ant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41D), listOf("bee", "honeybee"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB2), listOf("beetle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F41E), listOf("ladybug", "lady_beetle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F997), listOf("cricket"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB3), listOf("cockroach"), false),
    GoogleCompatEmoji(intArrayOf(0x1F577, 0xFE0F), listOf("spider"), false),
    GoogleCompatEmoji(intArrayOf(0x1F578, 0xFE0F), listOf("spider_web"), false),
    GoogleCompatEmoji(intArrayOf(0x1F982), listOf("scorpion"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99F), listOf("mosquito"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB0), listOf("fly"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB1), listOf("worm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9A0), listOf("microbe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F490), listOf("bouquet"), false),
    GoogleCompatEmoji(intArrayOf(0x1F338), listOf("cherry_blossom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4AE), listOf("white_flower"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB7), listOf("lotus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F5, 0xFE0F), listOf("rosette"), false),
    GoogleCompatEmoji(intArrayOf(0x1F339), listOf("rose"), false),
    GoogleCompatEmoji(intArrayOf(0x1F940), listOf("wilted_flower"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33A), listOf("hibiscus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33B), listOf("sunflower"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33C), listOf("blossom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F337), listOf("tulip"), false),
    GoogleCompatEmoji(intArrayOf(0x1F331), listOf("seedling"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB4), listOf("potted_plant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F332), listOf("evergreen_tree"), false),
    GoogleCompatEmoji(intArrayOf(0x1F333), listOf("deciduous_tree"), false),
    GoogleCompatEmoji(intArrayOf(0x1F334), listOf("palm_tree"), false),
    GoogleCompatEmoji(intArrayOf(0x1F335), listOf("cactus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33E), listOf("ear_of_rice"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33F), listOf("herb"), false),
    GoogleCompatEmoji(intArrayOf(0x2618, 0xFE0F), listOf("shamrock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F340), listOf("four_leaf_clover"), false),
    GoogleCompatEmoji(intArrayOf(0x1F341), listOf("maple_leaf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F342), listOf("fallen_leaf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F343), listOf("leaves"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB9), listOf("empty_nest"), false),
    GoogleCompatEmoji(intArrayOf(0x1FABA), listOf("nest_with_eggs"), false),
  )
}
