/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FlagsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F3C1), 0, 1), listOf("checkered_flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6A9), 0, 1), listOf("triangular_flag_on_post"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F38C), 0, 1), listOf("crossed_flags"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F4), 0, 1), listOf("waving_black_flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F3, 0xFE0F), 0, 2), listOf("waving_white_flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F3, 0xFE0F, 0x200D, 0x1F308), 0, 4), listOf("rainbow-flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F3, 0xFE0F, 0x200D, 0x26A7, 0xFE0F), 0, 5), listOf("transgender_flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F4, 0x200D, 0x2620, 0xFE0F), 0, 4), listOf("pirate_flag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1E8), 0, 2), listOf("flag-ac"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1E9), 0, 2), listOf("flag-ad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1EA), 0, 2), listOf("flag-ae"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1EB), 0, 2), listOf("flag-af"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1EC), 0, 2), listOf("flag-ag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1EE), 0, 2), listOf("flag-ai"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F1), 0, 2), listOf("flag-al"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F2), 0, 2), listOf("flag-am"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F4), 0, 2), listOf("flag-ao"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F6), 0, 2), listOf("flag-aq"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F7), 0, 2), listOf("flag-ar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F8), 0, 2), listOf("flag-as"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1F9), 0, 2), listOf("flag-at"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1FA), 0, 2), listOf("flag-au"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1FC), 0, 2), listOf("flag-aw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1FD), 0, 2), listOf("flag-ax"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E6, 0x1F1FF), 0, 2), listOf("flag-az"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1E6), 0, 2), listOf("flag-ba"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1E7), 0, 2), listOf("flag-bb"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1E9), 0, 2), listOf("flag-bd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1EA), 0, 2), listOf("flag-be"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1EB), 0, 2), listOf("flag-bf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1EC), 0, 2), listOf("flag-bg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1ED), 0, 2), listOf("flag-bh"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1EE), 0, 2), listOf("flag-bi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1EF), 0, 2), listOf("flag-bj"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F1), 0, 2), listOf("flag-bl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F2), 0, 2), listOf("flag-bm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F3), 0, 2), listOf("flag-bn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F4), 0, 2), listOf("flag-bo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F6), 0, 2), listOf("flag-bq"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F7), 0, 2), listOf("flag-br"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F8), 0, 2), listOf("flag-bs"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1F9), 0, 2), listOf("flag-bt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1FB), 0, 2), listOf("flag-bv"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1FC), 0, 2), listOf("flag-bw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1FE), 0, 2), listOf("flag-by"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E7, 0x1F1FF), 0, 2), listOf("flag-bz"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1E6), 0, 2), listOf("flag-ca"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1E8), 0, 2), listOf("flag-cc"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1E9), 0, 2), listOf("flag-cd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1EB), 0, 2), listOf("flag-cf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1EC), 0, 2), listOf("flag-cg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1ED), 0, 2), listOf("flag-ch"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1EE), 0, 2), listOf("flag-ci"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F0), 0, 2), listOf("flag-ck"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F1), 0, 2), listOf("flag-cl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F2), 0, 2), listOf("flag-cm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F3), 0, 2), listOf("cn", "flag-cn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F4), 0, 2), listOf("flag-co"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F5), 0, 2), listOf("flag-cp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1F7), 0, 2), listOf("flag-cr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FA), 0, 2), listOf("flag-cu"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FB), 0, 2), listOf("flag-cv"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FC), 0, 2), listOf("flag-cw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FD), 0, 2), listOf("flag-cx"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FE), 0, 2), listOf("flag-cy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E8, 0x1F1FF), 0, 2), listOf("flag-cz"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1EA), 0, 2), listOf("de", "flag-de"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1EC), 0, 2), listOf("flag-dg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1EF), 0, 2), listOf("flag-dj"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1F0), 0, 2), listOf("flag-dk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1F2), 0, 2), listOf("flag-dm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1F4), 0, 2), listOf("flag-do"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1E9, 0x1F1FF), 0, 2), listOf("flag-dz"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1E6), 0, 2), listOf("flag-ea"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1E8), 0, 2), listOf("flag-ec"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1EA), 0, 2), listOf("flag-ee"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1EC), 0, 2), listOf("flag-eg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1ED), 0, 2), listOf("flag-eh"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1F7), 0, 2), listOf("flag-er"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1F8), 0, 2), listOf("es", "flag-es"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1F9), 0, 2), listOf("flag-et"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EA, 0x1F1FA), 0, 2), listOf("flag-eu"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1EE), 0, 2), listOf("flag-fi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1EF), 0, 2), listOf("flag-fj"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1F0), 0, 2), listOf("flag-fk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1F2), 0, 2), listOf("flag-fm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1F4), 0, 2), listOf("flag-fo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EB, 0x1F1F7), 0, 2), listOf("fr", "flag-fr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1E6), 0, 2), listOf("flag-ga"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1E7), 0, 2), listOf("gb", "uk", "flag-gb"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1E9), 0, 2), listOf("flag-gd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1EA), 0, 2), listOf("flag-ge"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1EB), 0, 2), listOf("flag-gf"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1EC), 0, 2), listOf("flag-gg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1ED), 0, 2), listOf("flag-gh"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1EE), 0, 2), listOf("flag-gi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F1), 0, 2), listOf("flag-gl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F2), 0, 2), listOf("flag-gm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F3), 0, 2), listOf("flag-gn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F5), 0, 2), listOf("flag-gp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F6), 0, 2), listOf("flag-gq"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F7), 0, 2), listOf("flag-gr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F8), 0, 2), listOf("flag-gs"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1F9), 0, 2), listOf("flag-gt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1FA), 0, 2), listOf("flag-gu"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1FC), 0, 2), listOf("flag-gw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EC, 0x1F1FE), 0, 2), listOf("flag-gy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1F0), 0, 2), listOf("flag-hk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1F2), 0, 2), listOf("flag-hm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1F3), 0, 2), listOf("flag-hn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1F7), 0, 2), listOf("flag-hr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1F9), 0, 2), listOf("flag-ht"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1ED, 0x1F1FA), 0, 2), listOf("flag-hu"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1E8), 0, 2), listOf("flag-ic"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1E9), 0, 2), listOf("flag-id"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1EA), 0, 2), listOf("flag-ie"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F1), 0, 2), listOf("flag-il"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F2), 0, 2), listOf("flag-im"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F3), 0, 2), listOf("flag-in"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F4), 0, 2), listOf("flag-io"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F6), 0, 2), listOf("flag-iq"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F7), 0, 2), listOf("flag-ir"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F8), 0, 2), listOf("flag-is"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EE, 0x1F1F9), 0, 2), listOf("it", "flag-it"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EF, 0x1F1EA), 0, 2), listOf("flag-je"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EF, 0x1F1F2), 0, 2), listOf("flag-jm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EF, 0x1F1F4), 0, 2), listOf("flag-jo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1EF, 0x1F1F5), 0, 2), listOf("jp", "flag-jp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1EA), 0, 2), listOf("flag-ke"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1EC), 0, 2), listOf("flag-kg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1ED), 0, 2), listOf("flag-kh"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1EE), 0, 2), listOf("flag-ki"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1F2), 0, 2), listOf("flag-km"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1F3), 0, 2), listOf("flag-kn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1F5), 0, 2), listOf("flag-kp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1F7), 0, 2), listOf("kr", "flag-kr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1FC), 0, 2), listOf("flag-kw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1FE), 0, 2), listOf("flag-ky"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F0, 0x1F1FF), 0, 2), listOf("flag-kz"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1E6), 0, 2), listOf("flag-la"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1E7), 0, 2), listOf("flag-lb"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1E8), 0, 2), listOf("flag-lc"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1EE), 0, 2), listOf("flag-li"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1F0), 0, 2), listOf("flag-lk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1F7), 0, 2), listOf("flag-lr"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1F8), 0, 2), listOf("flag-ls"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1F9), 0, 2), listOf("flag-lt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1FA), 0, 2), listOf("flag-lu"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1FB), 0, 2), listOf("flag-lv"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F1F1, 0x1F1FE), 0, 2), listOf("flag-ly"), false),
  )
}
