/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FlagsCategoryChunk1 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E6), arrayOf("flag-ma"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E8), arrayOf("flag-mc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E9), arrayOf("flag-md"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EA), arrayOf("flag-me"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EB), arrayOf("flag-mf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EC), arrayOf("flag-mg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1ED), arrayOf("flag-mh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F0), arrayOf("flag-mk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F1), arrayOf("flag-ml"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F2), arrayOf("flag-mm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F3), arrayOf("flag-mn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F4), arrayOf("flag-mo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F5), arrayOf("flag-mp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F6), arrayOf("flag-mq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F7), arrayOf("flag-mr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F8), arrayOf("flag-ms"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F9), arrayOf("flag-mt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FA), arrayOf("flag-mu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FB), arrayOf("flag-mv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FC), arrayOf("flag-mw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FD), arrayOf("flag-mx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FE), arrayOf("flag-my"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FF), arrayOf("flag-mz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E6), arrayOf("flag-na"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E8), arrayOf("flag-nc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EA), arrayOf("flag-ne"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EB), arrayOf("flag-nf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EC), arrayOf("flag-ng"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EE), arrayOf("flag-ni"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F1), arrayOf("flag-nl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F4), arrayOf("flag-no"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F5), arrayOf("flag-np"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F7), arrayOf("flag-nr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FA), arrayOf("flag-nu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FF), arrayOf("flag-nz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F4, 0x1F1F2), arrayOf("flag-om"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1E6), arrayOf("flag-pa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EA), arrayOf("flag-pe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EB), arrayOf("flag-pf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EC), arrayOf("flag-pg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1ED), arrayOf("flag-ph"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F0), arrayOf("flag-pk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F1), arrayOf("flag-pl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F2), arrayOf("flag-pm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F3), arrayOf("flag-pn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F7), arrayOf("flag-pr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F8), arrayOf("flag-ps"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F9), arrayOf("flag-pt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FC), arrayOf("flag-pw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FE), arrayOf("flag-py"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F6, 0x1F1E6), arrayOf("flag-qa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1EA), arrayOf("flag-re"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1F4), arrayOf("flag-ro"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1F8), arrayOf("flag-rs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1FA), arrayOf("ru", "flag-ru"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1FC), arrayOf("flag-rw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E6), arrayOf("flag-sa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E7), arrayOf("flag-sb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E8), arrayOf("flag-sc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E9), arrayOf("flag-sd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EA), arrayOf("flag-se"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EC), arrayOf("flag-sg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1ED), arrayOf("flag-sh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EE), arrayOf("flag-si"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EF), arrayOf("flag-sj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F0), arrayOf("flag-sk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F1), arrayOf("flag-sl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F2), arrayOf("flag-sm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F3), arrayOf("flag-sn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F4), arrayOf("flag-so"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F7), arrayOf("flag-sr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F8), arrayOf("flag-ss"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F9), arrayOf("flag-st"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FB), arrayOf("flag-sv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FD), arrayOf("flag-sx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FE), arrayOf("flag-sy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FF), arrayOf("flag-sz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E6), arrayOf("flag-ta"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E8), arrayOf("flag-tc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E9), arrayOf("flag-td"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EB), arrayOf("flag-tf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EC), arrayOf("flag-tg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1ED), arrayOf("flag-th"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EF), arrayOf("flag-tj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F0), arrayOf("flag-tk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F1), arrayOf("flag-tl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F2), arrayOf("flag-tm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F3), arrayOf("flag-tn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F4), arrayOf("flag-to"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F7), arrayOf("flag-tr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F9), arrayOf("flag-tt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FB), arrayOf("flag-tv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FC), arrayOf("flag-tw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FF), arrayOf("flag-tz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1E6), arrayOf("flag-ua"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1EC), arrayOf("flag-ug"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F2), arrayOf("flag-um"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F3), arrayOf("flag-un"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F8), arrayOf("us", "flag-us"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1FE), arrayOf("flag-uy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1FF), arrayOf("flag-uz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1E6), arrayOf("flag-va"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1E8), arrayOf("flag-vc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EA), arrayOf("flag-ve"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EC), arrayOf("flag-vg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EE), arrayOf("flag-vi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1F3), arrayOf("flag-vn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1FA), arrayOf("flag-vu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FC, 0x1F1EB), arrayOf("flag-wf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FC, 0x1F1F8), arrayOf("flag-ws"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FD, 0x1F1F0), arrayOf("flag-xk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FE, 0x1F1EA), arrayOf("flag-ye"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FE, 0x1F1F9), arrayOf("flag-yt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1E6), arrayOf("flag-za"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1F2), arrayOf("flag-zm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1FC), arrayOf("flag-zw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0065, 0xE006E, 0xE0067, 0xE007F), arrayOf("flag-england"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0073, 0xE0063, 0xE0074, 0xE007F), arrayOf("flag-scotland"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0077, 0xE006C, 0xE0073, 0xE007F), arrayOf("flag-wales"), false),
  )
}
