/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FlagsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F3C1), arrayOf("checkered_flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A9), arrayOf("triangular_flag_on_post"), false),
    GoogleCompatEmoji(intArrayOf(0x1F38C), arrayOf("crossed_flags"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4), arrayOf("waving_black_flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F3, 0xFE0F), arrayOf("waving_white_flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F3, 0xFE0F, 0x200D, 0x1F308), arrayOf("rainbow-flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F3, 0xFE0F, 0x200D, 0x26A7, 0xFE0F), arrayOf("transgender_flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0x200D, 0x2620, 0xFE0F), arrayOf("pirate_flag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1E8), arrayOf("flag-ac"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1E9), arrayOf("flag-ad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1EA), arrayOf("flag-ae"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1EB), arrayOf("flag-af"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1EC), arrayOf("flag-ag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1EE), arrayOf("flag-ai"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F1), arrayOf("flag-al"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F2), arrayOf("flag-am"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F4), arrayOf("flag-ao"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F6), arrayOf("flag-aq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F7), arrayOf("flag-ar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F8), arrayOf("flag-as"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1F9), arrayOf("flag-at"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1FA), arrayOf("flag-au"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1FC), arrayOf("flag-aw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1FD), arrayOf("flag-ax"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E6, 0x1F1FF), arrayOf("flag-az"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1E6), arrayOf("flag-ba"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1E7), arrayOf("flag-bb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1E9), arrayOf("flag-bd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1EA), arrayOf("flag-be"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1EB), arrayOf("flag-bf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1EC), arrayOf("flag-bg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1ED), arrayOf("flag-bh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1EE), arrayOf("flag-bi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1EF), arrayOf("flag-bj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F1), arrayOf("flag-bl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F2), arrayOf("flag-bm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F3), arrayOf("flag-bn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F4), arrayOf("flag-bo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F6), arrayOf("flag-bq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F7), arrayOf("flag-br"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F8), arrayOf("flag-bs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1F9), arrayOf("flag-bt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1FB), arrayOf("flag-bv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1FC), arrayOf("flag-bw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1FE), arrayOf("flag-by"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E7, 0x1F1FF), arrayOf("flag-bz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1E6), arrayOf("flag-ca"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1E8), arrayOf("flag-cc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1E9), arrayOf("flag-cd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1EB), arrayOf("flag-cf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1EC), arrayOf("flag-cg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1ED), arrayOf("flag-ch"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1EE), arrayOf("flag-ci"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F0), arrayOf("flag-ck"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F1), arrayOf("flag-cl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F2), arrayOf("flag-cm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F3), arrayOf("cn", "flag-cn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F4), arrayOf("flag-co"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F5), arrayOf("flag-cp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1F7), arrayOf("flag-cr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FA), arrayOf("flag-cu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FB), arrayOf("flag-cv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FC), arrayOf("flag-cw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FD), arrayOf("flag-cx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FE), arrayOf("flag-cy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E8, 0x1F1FF), arrayOf("flag-cz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1EA), arrayOf("de", "flag-de"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1EC), arrayOf("flag-dg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1EF), arrayOf("flag-dj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1F0), arrayOf("flag-dk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1F2), arrayOf("flag-dm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1F4), arrayOf("flag-do"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1E9, 0x1F1FF), arrayOf("flag-dz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1E6), arrayOf("flag-ea"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1E8), arrayOf("flag-ec"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1EA), arrayOf("flag-ee"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1EC), arrayOf("flag-eg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1ED), arrayOf("flag-eh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1F7), arrayOf("flag-er"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1F8), arrayOf("es", "flag-es"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1F9), arrayOf("flag-et"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EA, 0x1F1FA), arrayOf("flag-eu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1EE), arrayOf("flag-fi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1EF), arrayOf("flag-fj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1F0), arrayOf("flag-fk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1F2), arrayOf("flag-fm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1F4), arrayOf("flag-fo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EB, 0x1F1F7), arrayOf("fr", "flag-fr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1E6), arrayOf("flag-ga"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1E7), arrayOf("gb", "uk", "flag-gb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1E9), arrayOf("flag-gd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1EA), arrayOf("flag-ge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1EB), arrayOf("flag-gf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1EC), arrayOf("flag-gg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1ED), arrayOf("flag-gh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1EE), arrayOf("flag-gi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F1), arrayOf("flag-gl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F2), arrayOf("flag-gm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F3), arrayOf("flag-gn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F5), arrayOf("flag-gp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F6), arrayOf("flag-gq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F7), arrayOf("flag-gr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F8), arrayOf("flag-gs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1F9), arrayOf("flag-gt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1FA), arrayOf("flag-gu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1FC), arrayOf("flag-gw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EC, 0x1F1FE), arrayOf("flag-gy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1F0), arrayOf("flag-hk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1F2), arrayOf("flag-hm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1F3), arrayOf("flag-hn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1F7), arrayOf("flag-hr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1F9), arrayOf("flag-ht"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1ED, 0x1F1FA), arrayOf("flag-hu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1E8), arrayOf("flag-ic"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1E9), arrayOf("flag-id"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1EA), arrayOf("flag-ie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F1), arrayOf("flag-il"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F2), arrayOf("flag-im"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F3), arrayOf("flag-in"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F4), arrayOf("flag-io"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F6), arrayOf("flag-iq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F7), arrayOf("flag-ir"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F8), arrayOf("flag-is"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EE, 0x1F1F9), arrayOf("it", "flag-it"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EF, 0x1F1EA), arrayOf("flag-je"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EF, 0x1F1F2), arrayOf("flag-jm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EF, 0x1F1F4), arrayOf("flag-jo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1EF, 0x1F1F5), arrayOf("jp", "flag-jp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1EA), arrayOf("flag-ke"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1EC), arrayOf("flag-kg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1ED), arrayOf("flag-kh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1EE), arrayOf("flag-ki"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1F2), arrayOf("flag-km"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1F3), arrayOf("flag-kn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1F5), arrayOf("flag-kp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1F7), arrayOf("kr", "flag-kr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1FC), arrayOf("flag-kw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1FE), arrayOf("flag-ky"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F0, 0x1F1FF), arrayOf("flag-kz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1E6), arrayOf("flag-la"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1E7), arrayOf("flag-lb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1E8), arrayOf("flag-lc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1EE), arrayOf("flag-li"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1F0), arrayOf("flag-lk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1F7), arrayOf("flag-lr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1F8), arrayOf("flag-ls"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1F9), arrayOf("flag-lt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1FA), arrayOf("flag-lu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1FB), arrayOf("flag-lv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F1, 0x1F1FE), arrayOf("flag-ly"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E6), arrayOf("flag-ma"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E8), arrayOf("flag-mc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E9), arrayOf("flag-md"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EA), arrayOf("flag-me"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EB), arrayOf("flag-mf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EC), arrayOf("flag-mg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1ED), arrayOf("flag-mh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F0), arrayOf("flag-mk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F1), arrayOf("flag-ml"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F2), arrayOf("flag-mm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F3), arrayOf("flag-mn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F4), arrayOf("flag-mo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F5), arrayOf("flag-mp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F6), arrayOf("flag-mq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F7), arrayOf("flag-mr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F8), arrayOf("flag-ms"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F9), arrayOf("flag-mt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FA), arrayOf("flag-mu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FB), arrayOf("flag-mv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FC), arrayOf("flag-mw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FD), arrayOf("flag-mx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FE), arrayOf("flag-my"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FF), arrayOf("flag-mz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E6), arrayOf("flag-na"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E8), arrayOf("flag-nc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EA), arrayOf("flag-ne"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EB), arrayOf("flag-nf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EC), arrayOf("flag-ng"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EE), arrayOf("flag-ni"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F1), arrayOf("flag-nl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F4), arrayOf("flag-no"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F5), arrayOf("flag-np"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F7), arrayOf("flag-nr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FA), arrayOf("flag-nu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FF), arrayOf("flag-nz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F4, 0x1F1F2), arrayOf("flag-om"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1E6), arrayOf("flag-pa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EA), arrayOf("flag-pe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EB), arrayOf("flag-pf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EC), arrayOf("flag-pg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1ED), arrayOf("flag-ph"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F0), arrayOf("flag-pk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F1), arrayOf("flag-pl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F2), arrayOf("flag-pm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F3), arrayOf("flag-pn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F7), arrayOf("flag-pr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F8), arrayOf("flag-ps"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F9), arrayOf("flag-pt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FC), arrayOf("flag-pw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FE), arrayOf("flag-py"), false),
  )
}
