/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FlagsCategoryChunk1 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E6), listOf("flag-ma"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E8), listOf("flag-mc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1E9), listOf("flag-md"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EA), listOf("flag-me"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EB), listOf("flag-mf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1EC), listOf("flag-mg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1ED), listOf("flag-mh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F0), listOf("flag-mk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F1), listOf("flag-ml"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F2), listOf("flag-mm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F3), listOf("flag-mn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F4), listOf("flag-mo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F5), listOf("flag-mp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F6), listOf("flag-mq"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F7), listOf("flag-mr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F8), listOf("flag-ms"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1F9), listOf("flag-mt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FA), listOf("flag-mu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FB), listOf("flag-mv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FC), listOf("flag-mw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FD), listOf("flag-mx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FE), listOf("flag-my"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F2, 0x1F1FF), listOf("flag-mz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E6), listOf("flag-na"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1E8), listOf("flag-nc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EA), listOf("flag-ne"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EB), listOf("flag-nf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EC), listOf("flag-ng"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1EE), listOf("flag-ni"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F1), listOf("flag-nl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F4), listOf("flag-no"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F5), listOf("flag-np"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1F7), listOf("flag-nr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FA), listOf("flag-nu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F3, 0x1F1FF), listOf("flag-nz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F4, 0x1F1F2), listOf("flag-om"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1E6), listOf("flag-pa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EA), listOf("flag-pe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EB), listOf("flag-pf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1EC), listOf("flag-pg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1ED), listOf("flag-ph"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F0), listOf("flag-pk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F1), listOf("flag-pl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F2), listOf("flag-pm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F3), listOf("flag-pn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F7), listOf("flag-pr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F8), listOf("flag-ps"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1F9), listOf("flag-pt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FC), listOf("flag-pw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F5, 0x1F1FE), listOf("flag-py"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F6, 0x1F1E6), listOf("flag-qa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1EA), listOf("flag-re"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1F4), listOf("flag-ro"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1F8), listOf("flag-rs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1FA), listOf("ru", "flag-ru"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F7, 0x1F1FC), listOf("flag-rw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E6), listOf("flag-sa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E7), listOf("flag-sb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E8), listOf("flag-sc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1E9), listOf("flag-sd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EA), listOf("flag-se"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EC), listOf("flag-sg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1ED), listOf("flag-sh"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EE), listOf("flag-si"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1EF), listOf("flag-sj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F0), listOf("flag-sk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F1), listOf("flag-sl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F2), listOf("flag-sm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F3), listOf("flag-sn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F4), listOf("flag-so"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F7), listOf("flag-sr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F8), listOf("flag-ss"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1F9), listOf("flag-st"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FB), listOf("flag-sv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FD), listOf("flag-sx"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FE), listOf("flag-sy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F8, 0x1F1FF), listOf("flag-sz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E6), listOf("flag-ta"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E8), listOf("flag-tc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1E9), listOf("flag-td"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EB), listOf("flag-tf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EC), listOf("flag-tg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1ED), listOf("flag-th"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1EF), listOf("flag-tj"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F0), listOf("flag-tk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F1), listOf("flag-tl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F2), listOf("flag-tm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F3), listOf("flag-tn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F4), listOf("flag-to"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F7), listOf("flag-tr"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1F9), listOf("flag-tt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FB), listOf("flag-tv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FC), listOf("flag-tw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1F9, 0x1F1FF), listOf("flag-tz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1E6), listOf("flag-ua"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1EC), listOf("flag-ug"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F2), listOf("flag-um"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F3), listOf("flag-un"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1F8), listOf("us", "flag-us"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1FE), listOf("flag-uy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FA, 0x1F1FF), listOf("flag-uz"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1E6), listOf("flag-va"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1E8), listOf("flag-vc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EA), listOf("flag-ve"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EC), listOf("flag-vg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1EE), listOf("flag-vi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1F3), listOf("flag-vn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FB, 0x1F1FA), listOf("flag-vu"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FC, 0x1F1EB), listOf("flag-wf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FC, 0x1F1F8), listOf("flag-ws"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FD, 0x1F1F0), listOf("flag-xk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FE, 0x1F1EA), listOf("flag-ye"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FE, 0x1F1F9), listOf("flag-yt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1E6), listOf("flag-za"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1F2), listOf("flag-zm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F1FF, 0x1F1FC), listOf("flag-zw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0065, 0xE006E, 0xE0067, 0xE007F), listOf("flag-england"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0073, 0xE0063, 0xE0074, 0xE007F), listOf("flag-scotland"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F4, 0xE0067, 0xE0062, 0xE0077, 0xE006C, 0xE0073, 0xE007F), listOf("flag-wales"), false),
  )
}
