/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FoodAndDrinkCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F347), arrayOf("grapes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F348), arrayOf("melon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F349), arrayOf("watermelon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34A), arrayOf("tangerine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34B), arrayOf("lemon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34C), arrayOf("banana"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34D), arrayOf("pineapple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96D), arrayOf("mango"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34E), arrayOf("apple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34F), arrayOf("green_apple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F350), arrayOf("pear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F351), arrayOf("peach"), false),
    GoogleCompatEmoji(intArrayOf(0x1F352), arrayOf("cherries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F353), arrayOf("strawberry"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD0), arrayOf("blueberries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95D), arrayOf("kiwifruit"), false),
    GoogleCompatEmoji(intArrayOf(0x1F345), arrayOf("tomato"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD2), arrayOf("olive"), false),
    GoogleCompatEmoji(intArrayOf(0x1F965), arrayOf("coconut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F951), arrayOf("avocado"), false),
    GoogleCompatEmoji(intArrayOf(0x1F346), arrayOf("eggplant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F954), arrayOf("potato"), false),
    GoogleCompatEmoji(intArrayOf(0x1F955), arrayOf("carrot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33D), arrayOf("corn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F336, 0xFE0F), arrayOf("hot_pepper"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD1), arrayOf("bell_pepper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F952), arrayOf("cucumber"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96C), arrayOf("leafy_green"), false),
    GoogleCompatEmoji(intArrayOf(0x1F966), arrayOf("broccoli"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C4), arrayOf("garlic"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C5), arrayOf("onion"), false),
    GoogleCompatEmoji(intArrayOf(0x1F344), arrayOf("mushroom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95C), arrayOf("peanuts"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD8), arrayOf("beans"), false),
    GoogleCompatEmoji(intArrayOf(0x1F330), arrayOf("chestnut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35E), arrayOf("bread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F950), arrayOf("croissant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F956), arrayOf("baguette_bread"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD3), arrayOf("flatbread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F968), arrayOf("pretzel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96F), arrayOf("bagel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95E), arrayOf("pancakes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C7), arrayOf("waffle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C0), arrayOf("cheese_wedge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F356), arrayOf("meat_on_bone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F357), arrayOf("poultry_leg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F969), arrayOf("cut_of_meat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F953), arrayOf("bacon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F354), arrayOf("hamburger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35F), arrayOf("fries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F355), arrayOf("pizza"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32D), arrayOf("hotdog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96A), arrayOf("sandwich"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32E), arrayOf("taco"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32F), arrayOf("burrito"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD4), arrayOf("tamale"), false),
    GoogleCompatEmoji(intArrayOf(0x1F959), arrayOf("stuffed_flatbread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C6), arrayOf("falafel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95A), arrayOf("egg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F373), arrayOf("fried_egg", "cooking"), false),
    GoogleCompatEmoji(intArrayOf(0x1F958), arrayOf("shallow_pan_of_food"), false),
    GoogleCompatEmoji(intArrayOf(0x1F372), arrayOf("stew"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD5), arrayOf("fondue"), false),
    GoogleCompatEmoji(intArrayOf(0x1F963), arrayOf("bowl_with_spoon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F957), arrayOf("green_salad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37F), arrayOf("popcorn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C8), arrayOf("butter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C2), arrayOf("salt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96B), arrayOf("canned_food"), false),
    GoogleCompatEmoji(intArrayOf(0x1F371), arrayOf("bento"), false),
    GoogleCompatEmoji(intArrayOf(0x1F358), arrayOf("rice_cracker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F359), arrayOf("rice_ball"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35A), arrayOf("rice"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35B), arrayOf("curry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35C), arrayOf("ramen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35D), arrayOf("spaghetti"), false),
    GoogleCompatEmoji(intArrayOf(0x1F360), arrayOf("sweet_potato"), false),
    GoogleCompatEmoji(intArrayOf(0x1F362), arrayOf("oden"), false),
    GoogleCompatEmoji(intArrayOf(0x1F363), arrayOf("sushi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F364), arrayOf("fried_shrimp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F365), arrayOf("fish_cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96E), arrayOf("moon_cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F361), arrayOf("dango"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95F), arrayOf("dumpling"), false),
    GoogleCompatEmoji(intArrayOf(0x1F960), arrayOf("fortune_cookie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F961), arrayOf("takeout_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F980), arrayOf("crab"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99E), arrayOf("lobster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F990), arrayOf("shrimp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F991), arrayOf("squid"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AA), arrayOf("oyster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F366), arrayOf("icecream"), false),
    GoogleCompatEmoji(intArrayOf(0x1F367), arrayOf("shaved_ice"), false),
    GoogleCompatEmoji(intArrayOf(0x1F368), arrayOf("ice_cream"), false),
    GoogleCompatEmoji(intArrayOf(0x1F369), arrayOf("doughnut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36A), arrayOf("cookie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F382), arrayOf("birthday"), false),
    GoogleCompatEmoji(intArrayOf(0x1F370), arrayOf("cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C1), arrayOf("cupcake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F967), arrayOf("pie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36B), arrayOf("chocolate_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36C), arrayOf("candy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36D), arrayOf("lollipop"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36E), arrayOf("custard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36F), arrayOf("honey_pot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37C), arrayOf("baby_bottle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95B), arrayOf("glass_of_milk"), false),
    GoogleCompatEmoji(intArrayOf(0x2615), arrayOf("coffee"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD6), arrayOf("teapot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F375), arrayOf("tea"), false),
    GoogleCompatEmoji(intArrayOf(0x1F376), arrayOf("sake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37E), arrayOf("champagne"), false),
    GoogleCompatEmoji(intArrayOf(0x1F377), arrayOf("wine_glass"), false),
    GoogleCompatEmoji(intArrayOf(0x1F378), arrayOf("cocktail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F379), arrayOf("tropical_drink"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37A), arrayOf("beer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37B), arrayOf("beers"), false),
    GoogleCompatEmoji(intArrayOf(0x1F942), arrayOf("clinking_glasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F943), arrayOf("tumbler_glass"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD7), arrayOf("pouring_liquid"), false),
    GoogleCompatEmoji(intArrayOf(0x1F964), arrayOf("cup_with_straw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9CB), arrayOf("bubble_tea"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C3), arrayOf("beverage_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C9), arrayOf("mate_drink"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9CA), arrayOf("ice_cube"), false),
    GoogleCompatEmoji(intArrayOf(0x1F962), arrayOf("chopsticks"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37D, 0xFE0F), arrayOf("knife_fork_plate"), false),
    GoogleCompatEmoji(intArrayOf(0x1F374), arrayOf("fork_and_knife"), false),
    GoogleCompatEmoji(intArrayOf(0x1F944), arrayOf("spoon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52A), arrayOf("hocho", "knife"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD9), arrayOf("jar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3FA), arrayOf("amphora"), false),
  )
}
