/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FoodAndDrinkCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F347), 0, 1), listOf("grapes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F348), 0, 1), listOf("melon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F349), 0, 1), listOf("watermelon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34A), 0, 1), listOf("tangerine"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34B), 0, 1), listOf("lemon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34C), 0, 1), listOf("banana"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34D), 0, 1), listOf("pineapple"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96D), 0, 1), listOf("mango"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34E), 0, 1), listOf("apple"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F34F), 0, 1), listOf("green_apple"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F350), 0, 1), listOf("pear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F351), 0, 1), listOf("peach"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F352), 0, 1), listOf("cherries"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F353), 0, 1), listOf("strawberry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD0), 0, 1), listOf("blueberries"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95D), 0, 1), listOf("kiwifruit"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F345), 0, 1), listOf("tomato"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD2), 0, 1), listOf("olive"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F965), 0, 1), listOf("coconut"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F951), 0, 1), listOf("avocado"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F346), 0, 1), listOf("eggplant"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F954), 0, 1), listOf("potato"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F955), 0, 1), listOf("carrot"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F33D), 0, 1), listOf("corn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F336, 0xFE0F), 0, 2), listOf("hot_pepper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD1), 0, 1), listOf("bell_pepper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F952), 0, 1), listOf("cucumber"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96C), 0, 1), listOf("leafy_green"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F966), 0, 1), listOf("broccoli"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C4), 0, 1), listOf("garlic"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C5), 0, 1), listOf("onion"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F344), 0, 1), listOf("mushroom"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95C), 0, 1), listOf("peanuts"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD8), 0, 1), listOf("beans"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F330), 0, 1), listOf("chestnut"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35E), 0, 1), listOf("bread"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F950), 0, 1), listOf("croissant"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F956), 0, 1), listOf("baguette_bread"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD3), 0, 1), listOf("flatbread"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F968), 0, 1), listOf("pretzel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96F), 0, 1), listOf("bagel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95E), 0, 1), listOf("pancakes"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C7), 0, 1), listOf("waffle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C0), 0, 1), listOf("cheese_wedge"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F356), 0, 1), listOf("meat_on_bone"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F357), 0, 1), listOf("poultry_leg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F969), 0, 1), listOf("cut_of_meat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F953), 0, 1), listOf("bacon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F354), 0, 1), listOf("hamburger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35F), 0, 1), listOf("fries"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F355), 0, 1), listOf("pizza"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F32D), 0, 1), listOf("hotdog"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96A), 0, 1), listOf("sandwich"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F32E), 0, 1), listOf("taco"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F32F), 0, 1), listOf("burrito"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD4), 0, 1), listOf("tamale"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F959), 0, 1), listOf("stuffed_flatbread"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C6), 0, 1), listOf("falafel"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95A), 0, 1), listOf("egg"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F373), 0, 1), listOf("fried_egg", "cooking"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F958), 0, 1), listOf("shallow_pan_of_food"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F372), 0, 1), listOf("stew"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD5), 0, 1), listOf("fondue"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F963), 0, 1), listOf("bowl_with_spoon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F957), 0, 1), listOf("green_salad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37F), 0, 1), listOf("popcorn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C8), 0, 1), listOf("butter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C2), 0, 1), listOf("salt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96B), 0, 1), listOf("canned_food"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F371), 0, 1), listOf("bento"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F358), 0, 1), listOf("rice_cracker"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F359), 0, 1), listOf("rice_ball"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35A), 0, 1), listOf("rice"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35B), 0, 1), listOf("curry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35C), 0, 1), listOf("ramen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F35D), 0, 1), listOf("spaghetti"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F360), 0, 1), listOf("sweet_potato"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F362), 0, 1), listOf("oden"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F363), 0, 1), listOf("sushi"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F364), 0, 1), listOf("fried_shrimp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F365), 0, 1), listOf("fish_cake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F96E), 0, 1), listOf("moon_cake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F361), 0, 1), listOf("dango"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95F), 0, 1), listOf("dumpling"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F960), 0, 1), listOf("fortune_cookie"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F961), 0, 1), listOf("takeout_box"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F980), 0, 1), listOf("crab"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F99E), 0, 1), listOf("lobster"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F990), 0, 1), listOf("shrimp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F991), 0, 1), listOf("squid"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AA), 0, 1), listOf("oyster"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F366), 0, 1), listOf("icecream"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F367), 0, 1), listOf("shaved_ice"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F368), 0, 1), listOf("ice_cream"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F369), 0, 1), listOf("doughnut"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36A), 0, 1), listOf("cookie"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F382), 0, 1), listOf("birthday"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F370), 0, 1), listOf("cake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C1), 0, 1), listOf("cupcake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F967), 0, 1), listOf("pie"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36B), 0, 1), listOf("chocolate_bar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36C), 0, 1), listOf("candy"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36D), 0, 1), listOf("lollipop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36E), 0, 1), listOf("custard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F36F), 0, 1), listOf("honey_pot"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37C), 0, 1), listOf("baby_bottle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F95B), 0, 1), listOf("glass_of_milk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2615), 0, 1), listOf("coffee"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD6), 0, 1), listOf("teapot"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F375), 0, 1), listOf("tea"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F376), 0, 1), listOf("sake"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37E), 0, 1), listOf("champagne"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F377), 0, 1), listOf("wine_glass"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F378), 0, 1), listOf("cocktail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F379), 0, 1), listOf("tropical_drink"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37A), 0, 1), listOf("beer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37B), 0, 1), listOf("beers"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F942), 0, 1), listOf("clinking_glasses"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F943), 0, 1), listOf("tumbler_glass"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD7), 0, 1), listOf("pouring_liquid"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F964), 0, 1), listOf("cup_with_straw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9CB), 0, 1), listOf("bubble_tea"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C3), 0, 1), listOf("beverage_box"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9C9), 0, 1), listOf("mate_drink"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9CA), 0, 1), listOf("ice_cube"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F962), 0, 1), listOf("chopsticks"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F37D, 0xFE0F), 0, 2), listOf("knife_fork_plate"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F374), 0, 1), listOf("fork_and_knife"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F944), 0, 1), listOf("spoon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52A), 0, 1), listOf("hocho", "knife"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAD9), 0, 1), listOf("jar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3FA), 0, 1), listOf("amphora"), false),
  )
}
