/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FoodAndDrinkCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F347), listOf("grapes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F348), listOf("melon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F349), listOf("watermelon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34A), listOf("tangerine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34B), listOf("lemon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34C), listOf("banana"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34D), listOf("pineapple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96D), listOf("mango"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34E), listOf("apple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F34F), listOf("green_apple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F350), listOf("pear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F351), listOf("peach"), false),
    GoogleCompatEmoji(intArrayOf(0x1F352), listOf("cherries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F353), listOf("strawberry"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD0), listOf("blueberries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95D), listOf("kiwifruit"), false),
    GoogleCompatEmoji(intArrayOf(0x1F345), listOf("tomato"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD2), listOf("olive"), false),
    GoogleCompatEmoji(intArrayOf(0x1F965), listOf("coconut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F951), listOf("avocado"), false),
    GoogleCompatEmoji(intArrayOf(0x1F346), listOf("eggplant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F954), listOf("potato"), false),
    GoogleCompatEmoji(intArrayOf(0x1F955), listOf("carrot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F33D), listOf("corn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F336, 0xFE0F), listOf("hot_pepper"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD1), listOf("bell_pepper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F952), listOf("cucumber"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96C), listOf("leafy_green"), false),
    GoogleCompatEmoji(intArrayOf(0x1F966), listOf("broccoli"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C4), listOf("garlic"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C5), listOf("onion"), false),
    GoogleCompatEmoji(intArrayOf(0x1F344), listOf("mushroom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95C), listOf("peanuts"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD8), listOf("beans"), false),
    GoogleCompatEmoji(intArrayOf(0x1F330), listOf("chestnut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35E), listOf("bread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F950), listOf("croissant"), false),
    GoogleCompatEmoji(intArrayOf(0x1F956), listOf("baguette_bread"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD3), listOf("flatbread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F968), listOf("pretzel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96F), listOf("bagel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95E), listOf("pancakes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C7), listOf("waffle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C0), listOf("cheese_wedge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F356), listOf("meat_on_bone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F357), listOf("poultry_leg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F969), listOf("cut_of_meat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F953), listOf("bacon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F354), listOf("hamburger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35F), listOf("fries"), false),
    GoogleCompatEmoji(intArrayOf(0x1F355), listOf("pizza"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32D), listOf("hotdog"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96A), listOf("sandwich"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32E), listOf("taco"), false),
    GoogleCompatEmoji(intArrayOf(0x1F32F), listOf("burrito"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD4), listOf("tamale"), false),
    GoogleCompatEmoji(intArrayOf(0x1F959), listOf("stuffed_flatbread"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C6), listOf("falafel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95A), listOf("egg"), false),
    GoogleCompatEmoji(intArrayOf(0x1F373), listOf("fried_egg", "cooking"), false),
    GoogleCompatEmoji(intArrayOf(0x1F958), listOf("shallow_pan_of_food"), false),
    GoogleCompatEmoji(intArrayOf(0x1F372), listOf("stew"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD5), listOf("fondue"), false),
    GoogleCompatEmoji(intArrayOf(0x1F963), listOf("bowl_with_spoon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F957), listOf("green_salad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37F), listOf("popcorn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C8), listOf("butter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C2), listOf("salt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96B), listOf("canned_food"), false),
    GoogleCompatEmoji(intArrayOf(0x1F371), listOf("bento"), false),
    GoogleCompatEmoji(intArrayOf(0x1F358), listOf("rice_cracker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F359), listOf("rice_ball"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35A), listOf("rice"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35B), listOf("curry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35C), listOf("ramen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F35D), listOf("spaghetti"), false),
    GoogleCompatEmoji(intArrayOf(0x1F360), listOf("sweet_potato"), false),
    GoogleCompatEmoji(intArrayOf(0x1F362), listOf("oden"), false),
    GoogleCompatEmoji(intArrayOf(0x1F363), listOf("sushi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F364), listOf("fried_shrimp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F365), listOf("fish_cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F96E), listOf("moon_cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F361), listOf("dango"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95F), listOf("dumpling"), false),
    GoogleCompatEmoji(intArrayOf(0x1F960), listOf("fortune_cookie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F961), listOf("takeout_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F980), listOf("crab"), false),
    GoogleCompatEmoji(intArrayOf(0x1F99E), listOf("lobster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F990), listOf("shrimp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F991), listOf("squid"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AA), listOf("oyster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F366), listOf("icecream"), false),
    GoogleCompatEmoji(intArrayOf(0x1F367), listOf("shaved_ice"), false),
    GoogleCompatEmoji(intArrayOf(0x1F368), listOf("ice_cream"), false),
    GoogleCompatEmoji(intArrayOf(0x1F369), listOf("doughnut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36A), listOf("cookie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F382), listOf("birthday"), false),
    GoogleCompatEmoji(intArrayOf(0x1F370), listOf("cake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C1), listOf("cupcake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F967), listOf("pie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36B), listOf("chocolate_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36C), listOf("candy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36D), listOf("lollipop"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36E), listOf("custard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F36F), listOf("honey_pot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37C), listOf("baby_bottle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F95B), listOf("glass_of_milk"), false),
    GoogleCompatEmoji(intArrayOf(0x2615), listOf("coffee"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD6), listOf("teapot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F375), listOf("tea"), false),
    GoogleCompatEmoji(intArrayOf(0x1F376), listOf("sake"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37E), listOf("champagne"), false),
    GoogleCompatEmoji(intArrayOf(0x1F377), listOf("wine_glass"), false),
    GoogleCompatEmoji(intArrayOf(0x1F378), listOf("cocktail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F379), listOf("tropical_drink"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37A), listOf("beer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37B), listOf("beers"), false),
    GoogleCompatEmoji(intArrayOf(0x1F942), listOf("clinking_glasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F943), listOf("tumbler_glass"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD7), listOf("pouring_liquid"), false),
    GoogleCompatEmoji(intArrayOf(0x1F964), listOf("cup_with_straw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9CB), listOf("bubble_tea"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C3), listOf("beverage_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9C9), listOf("mate_drink"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9CA), listOf("ice_cube"), false),
    GoogleCompatEmoji(intArrayOf(0x1F962), listOf("chopsticks"), false),
    GoogleCompatEmoji(intArrayOf(0x1F37D, 0xFE0F), listOf("knife_fork_plate"), false),
    GoogleCompatEmoji(intArrayOf(0x1F374), listOf("fork_and_knife"), false),
    GoogleCompatEmoji(intArrayOf(0x1F944), listOf("spoon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52A), listOf("hocho", "knife"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAD9), listOf("jar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3FA), listOf("amphora"), false),
  )
}
