/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F453), arrayOf("eyeglasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F576, 0xFE0F), arrayOf("dark_sunglasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97D), arrayOf("goggles"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97C), arrayOf("lab_coat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9BA), arrayOf("safety_vest"), false),
    GoogleCompatEmoji(intArrayOf(0x1F454), arrayOf("necktie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F455), arrayOf("shirt", "tshirt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F456), arrayOf("jeans"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E3), arrayOf("scarf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E4), arrayOf("gloves"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E5), arrayOf("coat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E6), arrayOf("socks"), false),
    GoogleCompatEmoji(intArrayOf(0x1F457), arrayOf("dress"), false),
    GoogleCompatEmoji(intArrayOf(0x1F458), arrayOf("kimono"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97B), arrayOf("sari"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA71), arrayOf("one-piece_swimsuit"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA72), arrayOf("briefs"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA73), arrayOf("shorts"), false),
    GoogleCompatEmoji(intArrayOf(0x1F459), arrayOf("bikini"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45A), arrayOf("womans_clothes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45B), arrayOf("purse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45C), arrayOf("handbag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45D), arrayOf("pouch"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CD, 0xFE0F), arrayOf("shopping_bags"), false),
    GoogleCompatEmoji(intArrayOf(0x1F392), arrayOf("school_satchel"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA74), arrayOf("thong_sandal"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45E), arrayOf("mans_shoe", "shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45F), arrayOf("athletic_shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97E), arrayOf("hiking_boot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97F), arrayOf("womans_flat_shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F460), arrayOf("high_heel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F461), arrayOf("sandal"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA70), arrayOf("ballet_shoes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F462), arrayOf("boot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F451), arrayOf("crown"), false),
    GoogleCompatEmoji(intArrayOf(0x1F452), arrayOf("womans_hat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A9), arrayOf("tophat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F393), arrayOf("mortar_board"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E2), arrayOf("billed_cap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA96), arrayOf("military_helmet"), false),
    GoogleCompatEmoji(intArrayOf(0x26D1, 0xFE0F), arrayOf("helmet_with_white_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FF), arrayOf("prayer_beads"), false),
    GoogleCompatEmoji(intArrayOf(0x1F484), arrayOf("lipstick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48D), arrayOf("ring"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48E), arrayOf("gem"), false),
    GoogleCompatEmoji(intArrayOf(0x1F507), arrayOf("mute"), false),
    GoogleCompatEmoji(intArrayOf(0x1F508), arrayOf("speaker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F509), arrayOf("sound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50A), arrayOf("loud_sound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E2), arrayOf("loudspeaker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E3), arrayOf("mega"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EF), arrayOf("postal_horn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F514), arrayOf("bell"), false),
    GoogleCompatEmoji(intArrayOf(0x1F515), arrayOf("no_bell"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BC), arrayOf("musical_score"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B5), arrayOf("musical_note"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B6), arrayOf("notes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F399, 0xFE0F), arrayOf("studio_microphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39A, 0xFE0F), arrayOf("level_slider"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39B, 0xFE0F), arrayOf("control_knobs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A4), arrayOf("microphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A7), arrayOf("headphones"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FB), arrayOf("radio"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B7), arrayOf("saxophone"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA97), arrayOf("accordion"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B8), arrayOf("guitar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B9), arrayOf("musical_keyboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BA), arrayOf("trumpet"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BB), arrayOf("violin"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA95), arrayOf("banjo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F941), arrayOf("drum_with_drumsticks"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA98), arrayOf("long_drum"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F1), arrayOf("iphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F2), arrayOf("calling"), false),
    GoogleCompatEmoji(intArrayOf(0x260E, 0xFE0F), arrayOf("phone", "telephone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DE), arrayOf("telephone_receiver"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DF), arrayOf("pager"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E0), arrayOf("fax"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50B), arrayOf("battery"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAAB), arrayOf("low_battery"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50C), arrayOf("electric_plug"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BB), arrayOf("computer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5A5, 0xFE0F), arrayOf("desktop_computer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5A8, 0xFE0F), arrayOf("printer"), false),
    GoogleCompatEmoji(intArrayOf(0x2328, 0xFE0F), arrayOf("keyboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5B1, 0xFE0F), arrayOf("three_button_mouse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5B2, 0xFE0F), arrayOf("trackball"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BD), arrayOf("minidisc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BE), arrayOf("floppy_disk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BF), arrayOf("cd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C0), arrayOf("dvd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EE), arrayOf("abacus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A5), arrayOf("movie_camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39E, 0xFE0F), arrayOf("film_frames"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FD, 0xFE0F), arrayOf("film_projector"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3AC), arrayOf("clapper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FA), arrayOf("tv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F7), arrayOf("camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F8), arrayOf("camera_with_flash"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F9), arrayOf("video_camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FC), arrayOf("vhs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50D), arrayOf("mag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50E), arrayOf("mag_right"), false),
    GoogleCompatEmoji(intArrayOf(0x1F56F, 0xFE0F), arrayOf("candle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4A1), arrayOf("bulb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F526), arrayOf("flashlight"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EE), arrayOf("izakaya_lantern", "lantern"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA94), arrayOf("diya_lamp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D4), arrayOf("notebook_with_decorative_cover"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D5), arrayOf("closed_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D6), arrayOf("book", "open_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D7), arrayOf("green_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D8), arrayOf("blue_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D9), arrayOf("orange_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DA), arrayOf("books"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D3), arrayOf("notebook"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D2), arrayOf("ledger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C3), arrayOf("page_with_curl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DC), arrayOf("scroll"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C4), arrayOf("page_facing_up"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F0), arrayOf("newspaper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DE, 0xFE0F), arrayOf("rolled_up_newspaper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D1), arrayOf("bookmark_tabs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F516), arrayOf("bookmark"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F7, 0xFE0F), arrayOf("label"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B0), arrayOf("moneybag"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA99), arrayOf("coin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B4), arrayOf("yen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B5), arrayOf("dollar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B6), arrayOf("euro"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B7), arrayOf("pound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B8), arrayOf("money_with_wings"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B3), arrayOf("credit_card"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FE), arrayOf("receipt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B9), arrayOf("chart"), false),
    GoogleCompatEmoji(intArrayOf(0x2709, 0xFE0F), arrayOf("email", "envelope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E7), arrayOf("e-mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E8), arrayOf("incoming_envelope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E9), arrayOf("envelope_with_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E4), arrayOf("outbox_tray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E5), arrayOf("inbox_tray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E6), arrayOf("package"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EB), arrayOf("mailbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EA), arrayOf("mailbox_closed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EC), arrayOf("mailbox_with_mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4ED), arrayOf("mailbox_with_no_mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EE), arrayOf("postbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5F3, 0xFE0F), arrayOf("ballot_box_with_ballot"), false),
    GoogleCompatEmoji(intArrayOf(0x270F, 0xFE0F), arrayOf("pencil2"), false),
    GoogleCompatEmoji(intArrayOf(0x2712, 0xFE0F), arrayOf("black_nib"), false),
  )
}
