/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk1 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F58B, 0xFE0F), listOf("lower_left_fountain_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58A, 0xFE0F), listOf("lower_left_ballpoint_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58C, 0xFE0F), listOf("lower_left_paintbrush"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58D, 0xFE0F), listOf("lower_left_crayon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DD), listOf("memo", "pencil"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BC), listOf("briefcase"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C1), listOf("file_folder"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C2), listOf("open_file_folder"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C2, 0xFE0F), listOf("card_index_dividers"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C5), listOf("date"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C6), listOf("calendar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D2, 0xFE0F), listOf("spiral_note_pad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D3, 0xFE0F), listOf("spiral_calendar_pad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C7), listOf("card_index"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C8), listOf("chart_with_upwards_trend"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C9), listOf("chart_with_downwards_trend"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CA), listOf("bar_chart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CB), listOf("clipboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CC), listOf("pushpin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CD), listOf("round_pushpin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CE), listOf("paperclip"), false),
    GoogleCompatEmoji(intArrayOf(0x1F587, 0xFE0F), listOf("linked_paperclips"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CF), listOf("straight_ruler"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D0), listOf("triangular_ruler"), false),
    GoogleCompatEmoji(intArrayOf(0x2702, 0xFE0F), listOf("scissors"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C3, 0xFE0F), listOf("card_file_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C4, 0xFE0F), listOf("file_cabinet"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D1, 0xFE0F), listOf("wastebasket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F512), listOf("lock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F513), listOf("unlock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50F), listOf("lock_with_ink_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F510), listOf("closed_lock_with_key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F511), listOf("key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DD, 0xFE0F), listOf("old_key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F528), listOf("hammer"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA93), listOf("axe"), false),
    GoogleCompatEmoji(intArrayOf(0x26CF, 0xFE0F), listOf("pick"), false),
    GoogleCompatEmoji(intArrayOf(0x2692, 0xFE0F), listOf("hammer_and_pick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E0, 0xFE0F), listOf("hammer_and_wrench"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5E1, 0xFE0F), listOf("dagger_knife"), false),
    GoogleCompatEmoji(intArrayOf(0x2694, 0xFE0F), listOf("crossed_swords"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52B), listOf("gun"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA83), listOf("boomerang"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F9), listOf("bow_and_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E1, 0xFE0F), listOf("shield"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9A), listOf("carpentry_saw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F527), listOf("wrench"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9B), listOf("screwdriver"), false),
    GoogleCompatEmoji(intArrayOf(0x1F529), listOf("nut_and_bolt"), false),
    GoogleCompatEmoji(intArrayOf(0x2699, 0xFE0F), listOf("gear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DC, 0xFE0F), listOf("compression"), false),
    GoogleCompatEmoji(intArrayOf(0x2696, 0xFE0F), listOf("scales"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AF), listOf("probing_cane"), false),
    GoogleCompatEmoji(intArrayOf(0x1F517), listOf("link"), false),
    GoogleCompatEmoji(intArrayOf(0x26D3, 0xFE0F), listOf("chains"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9D), listOf("hook"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F0), listOf("toolbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F2), listOf("magnet"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9C), listOf("ladder"), false),
    GoogleCompatEmoji(intArrayOf(0x2697, 0xFE0F), listOf("alembic"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EA), listOf("test_tube"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EB), listOf("petri_dish"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EC), listOf("dna"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52C), listOf("microscope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52D), listOf("telescope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E1), listOf("satellite_antenna"), false),
    GoogleCompatEmoji(intArrayOf(0x1F489), listOf("syringe"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA78), listOf("drop_of_blood"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48A), listOf("pill"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA79), listOf("adhesive_bandage"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7C), listOf("crutch"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7A), listOf("stethoscope"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7B), listOf("x-ray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AA), listOf("door"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D7), listOf("elevator"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9E), listOf("mirror"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9F), listOf("window"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CF, 0xFE0F), listOf("bed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CB, 0xFE0F), listOf("couch_and_lamp"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA91), listOf("chair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BD), listOf("toilet"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA0), listOf("plunger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BF), listOf("shower"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C1), listOf("bathtub"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA4), listOf("mouse_trap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA92), listOf("razor"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F4), listOf("lotion_bottle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F7), listOf("safety_pin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F9), listOf("broom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FA), listOf("basket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FB), listOf("roll_of_paper"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA3), listOf("bucket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FC), listOf("soap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE7), listOf("bubbles"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA5), listOf("toothbrush"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FD), listOf("sponge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EF), listOf("fire_extinguisher"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D2), listOf("shopping_trolley"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AC), listOf("smoking"), false),
    GoogleCompatEmoji(intArrayOf(0x26B0, 0xFE0F), listOf("coffin"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA6), listOf("headstone"), false),
    GoogleCompatEmoji(intArrayOf(0x26B1, 0xFE0F), listOf("funeral_urn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FF), listOf("moyai"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA7), listOf("placard"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAAA), listOf("identification_card"), false),
  )
}
