/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F453), listOf("eyeglasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F576, 0xFE0F), listOf("dark_sunglasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97D), listOf("goggles"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97C), listOf("lab_coat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9BA), listOf("safety_vest"), false),
    GoogleCompatEmoji(intArrayOf(0x1F454), listOf("necktie"), false),
    GoogleCompatEmoji(intArrayOf(0x1F455), listOf("shirt", "tshirt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F456), listOf("jeans"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E3), listOf("scarf"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E4), listOf("gloves"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E5), listOf("coat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E6), listOf("socks"), false),
    GoogleCompatEmoji(intArrayOf(0x1F457), listOf("dress"), false),
    GoogleCompatEmoji(intArrayOf(0x1F458), listOf("kimono"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97B), listOf("sari"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA71), listOf("one-piece_swimsuit"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA72), listOf("briefs"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA73), listOf("shorts"), false),
    GoogleCompatEmoji(intArrayOf(0x1F459), listOf("bikini"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45A), listOf("womans_clothes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45B), listOf("purse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45C), listOf("handbag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45D), listOf("pouch"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CD, 0xFE0F), listOf("shopping_bags"), false),
    GoogleCompatEmoji(intArrayOf(0x1F392), listOf("school_satchel"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA74), listOf("thong_sandal"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45E), listOf("mans_shoe", "shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F45F), listOf("athletic_shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97E), listOf("hiking_boot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97F), listOf("womans_flat_shoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F460), listOf("high_heel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F461), listOf("sandal"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA70), listOf("ballet_shoes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F462), listOf("boot"), false),
    GoogleCompatEmoji(intArrayOf(0x1F451), listOf("crown"), false),
    GoogleCompatEmoji(intArrayOf(0x1F452), listOf("womans_hat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A9), listOf("tophat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F393), listOf("mortar_board"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E2), listOf("billed_cap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA96), listOf("military_helmet"), false),
    GoogleCompatEmoji(intArrayOf(0x26D1, 0xFE0F), listOf("helmet_with_white_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FF), listOf("prayer_beads"), false),
    GoogleCompatEmoji(intArrayOf(0x1F484), listOf("lipstick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48D), listOf("ring"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48E), listOf("gem"), false),
    GoogleCompatEmoji(intArrayOf(0x1F507), listOf("mute"), false),
    GoogleCompatEmoji(intArrayOf(0x1F508), listOf("speaker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F509), listOf("sound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50A), listOf("loud_sound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E2), listOf("loudspeaker"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E3), listOf("mega"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EF), listOf("postal_horn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F514), listOf("bell"), false),
    GoogleCompatEmoji(intArrayOf(0x1F515), listOf("no_bell"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BC), listOf("musical_score"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B5), listOf("musical_note"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B6), listOf("notes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F399, 0xFE0F), listOf("studio_microphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39A, 0xFE0F), listOf("level_slider"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39B, 0xFE0F), listOf("control_knobs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A4), listOf("microphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A7), listOf("headphones"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FB), listOf("radio"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B7), listOf("saxophone"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA97), listOf("accordion"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B8), listOf("guitar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3B9), listOf("musical_keyboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BA), listOf("trumpet"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3BB), listOf("violin"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA95), listOf("banjo"), false),
    GoogleCompatEmoji(intArrayOf(0x1F941), listOf("drum_with_drumsticks"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA98), listOf("long_drum"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F1), listOf("iphone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F2), listOf("calling"), false),
    GoogleCompatEmoji(intArrayOf(0x260E, 0xFE0F), listOf("phone", "telephone"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DE), listOf("telephone_receiver"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DF), listOf("pager"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E0), listOf("fax"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50B), listOf("battery"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAAB), listOf("low_battery"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50C), listOf("electric_plug"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BB), listOf("computer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5A5, 0xFE0F), listOf("desktop_computer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5A8, 0xFE0F), listOf("printer"), false),
    GoogleCompatEmoji(intArrayOf(0x2328, 0xFE0F), listOf("keyboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5B1, 0xFE0F), listOf("three_button_mouse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5B2, 0xFE0F), listOf("trackball"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BD), listOf("minidisc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BE), listOf("floppy_disk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BF), listOf("cd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C0), listOf("dvd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EE), listOf("abacus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A5), listOf("movie_camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F39E, 0xFE0F), listOf("film_frames"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FD, 0xFE0F), listOf("film_projector"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3AC), listOf("clapper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FA), listOf("tv"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F7), listOf("camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F8), listOf("camera_with_flash"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F9), listOf("video_camera"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4FC), listOf("vhs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50D), listOf("mag"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50E), listOf("mag_right"), false),
    GoogleCompatEmoji(intArrayOf(0x1F56F, 0xFE0F), listOf("candle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4A1), listOf("bulb"), false),
    GoogleCompatEmoji(intArrayOf(0x1F526), listOf("flashlight"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EE), listOf("izakaya_lantern", "lantern"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA94), listOf("diya_lamp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D4), listOf("notebook_with_decorative_cover"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D5), listOf("closed_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D6), listOf("book", "open_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D7), listOf("green_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D8), listOf("blue_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D9), listOf("orange_book"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DA), listOf("books"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D3), listOf("notebook"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D2), listOf("ledger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C3), listOf("page_with_curl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DC), listOf("scroll"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C4), listOf("page_facing_up"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F0), listOf("newspaper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DE, 0xFE0F), listOf("rolled_up_newspaper"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D1), listOf("bookmark_tabs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F516), listOf("bookmark"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F7, 0xFE0F), listOf("label"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B0), listOf("moneybag"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA99), listOf("coin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B4), listOf("yen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B5), listOf("dollar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B6), listOf("euro"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B7), listOf("pound"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B8), listOf("money_with_wings"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B3), listOf("credit_card"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FE), listOf("receipt"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B9), listOf("chart"), false),
    GoogleCompatEmoji(intArrayOf(0x2709, 0xFE0F), listOf("email", "envelope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E7), listOf("e-mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E8), listOf("incoming_envelope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E9), listOf("envelope_with_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E4), listOf("outbox_tray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E5), listOf("inbox_tray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E6), listOf("package"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EB), listOf("mailbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EA), listOf("mailbox_closed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EC), listOf("mailbox_with_mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4ED), listOf("mailbox_with_no_mail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4EE), listOf("postbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5F3, 0xFE0F), listOf("ballot_box_with_ballot"), false),
    GoogleCompatEmoji(intArrayOf(0x270F, 0xFE0F), listOf("pencil2"), false),
    GoogleCompatEmoji(intArrayOf(0x2712, 0xFE0F), listOf("black_nib"), false),
  )
}
