/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk1 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F58B, 0xFE0F), arrayOf("lower_left_fountain_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58A, 0xFE0F), arrayOf("lower_left_ballpoint_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58C, 0xFE0F), arrayOf("lower_left_paintbrush"), false),
    GoogleCompatEmoji(intArrayOf(0x1F58D, 0xFE0F), arrayOf("lower_left_crayon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DD), arrayOf("memo", "pencil"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BC), arrayOf("briefcase"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C1), arrayOf("file_folder"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C2), arrayOf("open_file_folder"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C2, 0xFE0F), arrayOf("card_index_dividers"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C5), arrayOf("date"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C6), arrayOf("calendar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D2, 0xFE0F), arrayOf("spiral_note_pad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D3, 0xFE0F), arrayOf("spiral_calendar_pad"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C7), arrayOf("card_index"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C8), arrayOf("chart_with_upwards_trend"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4C9), arrayOf("chart_with_downwards_trend"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CA), arrayOf("bar_chart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CB), arrayOf("clipboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CC), arrayOf("pushpin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CD), arrayOf("round_pushpin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CE), arrayOf("paperclip"), false),
    GoogleCompatEmoji(intArrayOf(0x1F587, 0xFE0F), arrayOf("linked_paperclips"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4CF), arrayOf("straight_ruler"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4D0), arrayOf("triangular_ruler"), false),
    GoogleCompatEmoji(intArrayOf(0x2702, 0xFE0F), arrayOf("scissors"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C3, 0xFE0F), arrayOf("card_file_box"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5C4, 0xFE0F), arrayOf("file_cabinet"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5D1, 0xFE0F), arrayOf("wastebasket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F512), arrayOf("lock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F513), arrayOf("unlock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F50F), arrayOf("lock_with_ink_pen"), false),
    GoogleCompatEmoji(intArrayOf(0x1F510), arrayOf("closed_lock_with_key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F511), arrayOf("key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DD, 0xFE0F), arrayOf("old_key"), false),
    GoogleCompatEmoji(intArrayOf(0x1F528), arrayOf("hammer"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA93), arrayOf("axe"), false),
    GoogleCompatEmoji(intArrayOf(0x26CF, 0xFE0F), arrayOf("pick"), false),
    GoogleCompatEmoji(intArrayOf(0x2692, 0xFE0F), arrayOf("hammer_and_pick"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E0, 0xFE0F), arrayOf("hammer_and_wrench"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5E1, 0xFE0F), arrayOf("dagger_knife"), false),
    GoogleCompatEmoji(intArrayOf(0x2694, 0xFE0F), arrayOf("crossed_swords"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52B), arrayOf("gun"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA83), arrayOf("boomerang"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F9), arrayOf("bow_and_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E1, 0xFE0F), arrayOf("shield"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9A), arrayOf("carpentry_saw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F527), arrayOf("wrench"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9B), arrayOf("screwdriver"), false),
    GoogleCompatEmoji(intArrayOf(0x1F529), arrayOf("nut_and_bolt"), false),
    GoogleCompatEmoji(intArrayOf(0x2699, 0xFE0F), arrayOf("gear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5DC, 0xFE0F), arrayOf("compression"), false),
    GoogleCompatEmoji(intArrayOf(0x2696, 0xFE0F), arrayOf("scales"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9AF), arrayOf("probing_cane"), false),
    GoogleCompatEmoji(intArrayOf(0x1F517), arrayOf("link"), false),
    GoogleCompatEmoji(intArrayOf(0x26D3, 0xFE0F), arrayOf("chains"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9D), arrayOf("hook"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F0), arrayOf("toolbox"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F2), arrayOf("magnet"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9C), arrayOf("ladder"), false),
    GoogleCompatEmoji(intArrayOf(0x2697, 0xFE0F), arrayOf("alembic"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EA), arrayOf("test_tube"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EB), arrayOf("petri_dish"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EC), arrayOf("dna"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52C), arrayOf("microscope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52D), arrayOf("telescope"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4E1), arrayOf("satellite_antenna"), false),
    GoogleCompatEmoji(intArrayOf(0x1F489), arrayOf("syringe"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA78), arrayOf("drop_of_blood"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48A), arrayOf("pill"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA79), arrayOf("adhesive_bandage"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7C), arrayOf("crutch"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7A), arrayOf("stethoscope"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA7B), arrayOf("x-ray"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AA), arrayOf("door"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D7), arrayOf("elevator"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9E), arrayOf("mirror"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA9F), arrayOf("window"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CF, 0xFE0F), arrayOf("bed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CB, 0xFE0F), arrayOf("couch_and_lamp"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA91), arrayOf("chair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BD), arrayOf("toilet"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA0), arrayOf("plunger"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BF), arrayOf("shower"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C1), arrayOf("bathtub"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA4), arrayOf("mouse_trap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA92), arrayOf("razor"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F4), arrayOf("lotion_bottle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F7), arrayOf("safety_pin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F9), arrayOf("broom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FA), arrayOf("basket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FB), arrayOf("roll_of_paper"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA3), arrayOf("bucket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FC), arrayOf("soap"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE7), arrayOf("bubbles"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA5), arrayOf("toothbrush"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9FD), arrayOf("sponge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9EF), arrayOf("fire_extinguisher"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D2), arrayOf("shopping_trolley"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AC), arrayOf("smoking"), false),
    GoogleCompatEmoji(intArrayOf(0x26B0, 0xFE0F), arrayOf("coffin"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA6), arrayOf("headstone"), false),
    GoogleCompatEmoji(intArrayOf(0x26B1, 0xFE0F), arrayOf("funeral_urn"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FF), arrayOf("moyai"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA7), arrayOf("placard"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAAA), arrayOf("identification_card"), false),
  )
}
