/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk1 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F58B, 0xFE0F), 0, 2), listOf("lower_left_fountain_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58A, 0xFE0F), 0, 2), listOf("lower_left_ballpoint_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58C, 0xFE0F), 0, 2), listOf("lower_left_paintbrush"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58D, 0xFE0F), 0, 2), listOf("lower_left_crayon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4DD), 0, 1), listOf("memo", "pencil"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4BC), 0, 1), listOf("briefcase"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C1), 0, 1), listOf("file_folder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C2), 0, 1), listOf("open_file_folder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C2, 0xFE0F), 0, 2), listOf("card_index_dividers"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C5), 0, 1), listOf("date"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C6), 0, 1), listOf("calendar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D2, 0xFE0F), 0, 2), listOf("spiral_note_pad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D3, 0xFE0F), 0, 2), listOf("spiral_calendar_pad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C7), 0, 1), listOf("card_index"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C8), 0, 1), listOf("chart_with_upwards_trend"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C9), 0, 1), listOf("chart_with_downwards_trend"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CA), 0, 1), listOf("bar_chart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CB), 0, 1), listOf("clipboard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CC), 0, 1), listOf("pushpin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CD), 0, 1), listOf("round_pushpin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CE), 0, 1), listOf("paperclip"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F587, 0xFE0F), 0, 2), listOf("linked_paperclips"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CF), 0, 1), listOf("straight_ruler"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4D0), 0, 1), listOf("triangular_ruler"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2702, 0xFE0F), 0, 2), listOf("scissors"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C3, 0xFE0F), 0, 2), listOf("card_file_box"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C4, 0xFE0F), 0, 2), listOf("file_cabinet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D1, 0xFE0F), 0, 2), listOf("wastebasket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F512), 0, 1), listOf("lock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F513), 0, 1), listOf("unlock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F50F), 0, 1), listOf("lock_with_ink_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F510), 0, 1), listOf("closed_lock_with_key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F511), 0, 1), listOf("key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5DD, 0xFE0F), 0, 2), listOf("old_key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F528), 0, 1), listOf("hammer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA93), 0, 1), listOf("axe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26CF, 0xFE0F), 0, 2), listOf("pick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2692, 0xFE0F), 0, 2), listOf("hammer_and_pick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E0, 0xFE0F), 0, 2), listOf("hammer_and_wrench"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5E1, 0xFE0F), 0, 2), listOf("dagger_knife"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2694, 0xFE0F), 0, 2), listOf("crossed_swords"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52B), 0, 1), listOf("gun"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA83), 0, 1), listOf("boomerang"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F9), 0, 1), listOf("bow_and_arrow"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E1, 0xFE0F), 0, 2), listOf("shield"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9A), 0, 1), listOf("carpentry_saw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F527), 0, 1), listOf("wrench"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9B), 0, 1), listOf("screwdriver"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F529), 0, 1), listOf("nut_and_bolt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2699, 0xFE0F), 0, 2), listOf("gear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5DC, 0xFE0F), 0, 2), listOf("compression"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2696, 0xFE0F), 0, 2), listOf("scales"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AF), 0, 1), listOf("probing_cane"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F517), 0, 1), listOf("link"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26D3, 0xFE0F), 0, 2), listOf("chains"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9D), 0, 1), listOf("hook"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F0), 0, 1), listOf("toolbox"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F2), 0, 1), listOf("magnet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9C), 0, 1), listOf("ladder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2697, 0xFE0F), 0, 2), listOf("alembic"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EA), 0, 1), listOf("test_tube"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EB), 0, 1), listOf("petri_dish"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EC), 0, 1), listOf("dna"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52C), 0, 1), listOf("microscope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52D), 0, 1), listOf("telescope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E1), 0, 1), listOf("satellite_antenna"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F489), 0, 1), listOf("syringe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA78), 0, 1), listOf("drop_of_blood"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F48A), 0, 1), listOf("pill"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA79), 0, 1), listOf("adhesive_bandage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7C), 0, 1), listOf("crutch"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7A), 0, 1), listOf("stethoscope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7B), 0, 1), listOf("x-ray"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AA), 0, 1), listOf("door"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D7), 0, 1), listOf("elevator"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9E), 0, 1), listOf("mirror"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9F), 0, 1), listOf("window"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6CF, 0xFE0F), 0, 2), listOf("bed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6CB, 0xFE0F), 0, 2), listOf("couch_and_lamp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA91), 0, 1), listOf("chair"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BD), 0, 1), listOf("toilet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA0), 0, 1), listOf("plunger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BF), 0, 1), listOf("shower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C1), 0, 1), listOf("bathtub"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA4), 0, 1), listOf("mouse_trap"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA92), 0, 1), listOf("razor"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F4), 0, 1), listOf("lotion_bottle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F7), 0, 1), listOf("safety_pin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F9), 0, 1), listOf("broom"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9FA), 0, 1), listOf("basket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9FB), 0, 1), listOf("roll_of_paper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA3), 0, 1), listOf("bucket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9FC), 0, 1), listOf("soap"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAE7), 0, 1), listOf("bubbles"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA5), 0, 1), listOf("toothbrush"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9FD), 0, 1), listOf("sponge"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EF), 0, 1), listOf("fire_extinguisher"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D2), 0, 1), listOf("shopping_trolley"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AC), 0, 1), listOf("smoking"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26B0, 0xFE0F), 0, 2), listOf("coffin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA6), 0, 1), listOf("headstone"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26B1, 0xFE0F), 0, 2), listOf("funeral_urn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5FF), 0, 1), listOf("moyai"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA7), 0, 1), listOf("placard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAAA), 0, 1), listOf("identification_card"), false),
  )
}
