/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SmileysAndPeopleCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(0x1F600, arrayOf("grinning"), false),
    GoogleCompatEmoji(0x1F603, arrayOf("smiley"), false),
    GoogleCompatEmoji(0x1F604, arrayOf("smile"), false),
    GoogleCompatEmoji(0x1F601, arrayOf("grin"), false),
    GoogleCompatEmoji(0x1F606, arrayOf("laughing", "satisfied"), false),
    GoogleCompatEmoji(0x1F605, arrayOf("sweat_smile"), false),
    GoogleCompatEmoji(0x1F923, arrayOf("rolling_on_the_floor_laughing"), false),
    GoogleCompatEmoji(0x1F602, arrayOf("joy"), false),
    GoogleCompatEmoji(0x1F642, arrayOf("slightly_smiling_face"), false),
    GoogleCompatEmoji(0x1F643, arrayOf("upside_down_face"), false),
    GoogleCompatEmoji(0x1FAE0, arrayOf("melting_face"), false),
    GoogleCompatEmoji(0x1F609, arrayOf("wink"), false),
    GoogleCompatEmoji(0x1F60A, arrayOf("blush"), false),
    GoogleCompatEmoji(0x1F607, arrayOf("innocent"), false),
    GoogleCompatEmoji(0x1F970, arrayOf("smiling_face_with_3_hearts"), false),
    GoogleCompatEmoji(0x1F60D, arrayOf("heart_eyes"), false),
    GoogleCompatEmoji(0x1F929, arrayOf("star-struck", "grinning_face_with_star_eyes"), false),
    GoogleCompatEmoji(0x1F618, arrayOf("kissing_heart"), false),
    GoogleCompatEmoji(0x1F617, arrayOf("kissing"), false),
    GoogleCompatEmoji(intArrayOf(0x263A, 0xFE0F), arrayOf("relaxed"), false),
    GoogleCompatEmoji(0x1F61A, arrayOf("kissing_closed_eyes"), false),
    GoogleCompatEmoji(0x1F619, arrayOf("kissing_smiling_eyes"), false),
    GoogleCompatEmoji(0x1F972, arrayOf("smiling_face_with_tear"), false),
    GoogleCompatEmoji(0x1F60B, arrayOf("yum"), false),
    GoogleCompatEmoji(0x1F61B, arrayOf("stuck_out_tongue"), false),
    GoogleCompatEmoji(0x1F61C, arrayOf("stuck_out_tongue_winking_eye"), false),
    GoogleCompatEmoji(0x1F92A, arrayOf("zany_face", "grinning_face_with_one_large_and_one_small_eye"), false),
    GoogleCompatEmoji(0x1F61D, arrayOf("stuck_out_tongue_closed_eyes"), false),
    GoogleCompatEmoji(0x1F911, arrayOf("money_mouth_face"), false),
    GoogleCompatEmoji(0x1F917, arrayOf("hugging_face"), false),
    GoogleCompatEmoji(0x1F92D, arrayOf("face_with_hand_over_mouth", "smiling_face_with_smiling_eyes_and_hand_covering_mouth"), false),
    GoogleCompatEmoji(0x1FAE2, arrayOf("face_with_open_eyes_and_hand_over_mouth"), false),
    GoogleCompatEmoji(0x1FAE3, arrayOf("face_with_peeking_eye"), false),
    GoogleCompatEmoji(0x1F92B, arrayOf("shushing_face", "face_with_finger_covering_closed_lips"), false),
    GoogleCompatEmoji(0x1F914, arrayOf("thinking_face"), false),
    GoogleCompatEmoji(0x1FAE1, arrayOf("saluting_face"), false),
    GoogleCompatEmoji(0x1F910, arrayOf("zipper_mouth_face"), false),
    GoogleCompatEmoji(0x1F928, arrayOf("face_with_raised_eyebrow", "face_with_one_eyebrow_raised"), false),
    GoogleCompatEmoji(0x1F610, arrayOf("neutral_face"), false),
    GoogleCompatEmoji(0x1F611, arrayOf("expressionless"), false),
    GoogleCompatEmoji(0x1F636, arrayOf("no_mouth"), false),
    GoogleCompatEmoji(0x1FAE5, arrayOf("dotted_line_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F636, 0x200D, 0x1F32B, 0xFE0F), arrayOf("face_in_clouds"), false),
    GoogleCompatEmoji(0x1F60F, arrayOf("smirk"), false),
    GoogleCompatEmoji(0x1F612, arrayOf("unamused"), false),
    GoogleCompatEmoji(0x1F644, arrayOf("face_with_rolling_eyes"), false),
    GoogleCompatEmoji(0x1F62C, arrayOf("grimacing"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62E, 0x200D, 0x1F4A8), arrayOf("face_exhaling"), false),
    GoogleCompatEmoji(0x1F925, arrayOf("lying_face"), false),
    GoogleCompatEmoji(0x1F60C, arrayOf("relieved"), false),
    GoogleCompatEmoji(0x1F614, arrayOf("pensive"), false),
    GoogleCompatEmoji(0x1F62A, arrayOf("sleepy"), false),
    GoogleCompatEmoji(0x1F924, arrayOf("drooling_face"), false),
    GoogleCompatEmoji(0x1F634, arrayOf("sleeping"), false),
    GoogleCompatEmoji(0x1F637, arrayOf("mask"), false),
    GoogleCompatEmoji(0x1F912, arrayOf("face_with_thermometer"), false),
    GoogleCompatEmoji(0x1F915, arrayOf("face_with_head_bandage"), false),
    GoogleCompatEmoji(0x1F922, arrayOf("nauseated_face"), false),
    GoogleCompatEmoji(0x1F92E, arrayOf("face_vomiting", "face_with_open_mouth_vomiting"), false),
    GoogleCompatEmoji(0x1F927, arrayOf("sneezing_face"), false),
    GoogleCompatEmoji(0x1F975, arrayOf("hot_face"), false),
    GoogleCompatEmoji(0x1F976, arrayOf("cold_face"), false),
    GoogleCompatEmoji(0x1F974, arrayOf("woozy_face"), false),
    GoogleCompatEmoji(0x1F635, arrayOf("dizzy_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F635, 0x200D, 0x1F4AB), arrayOf("face_with_spiral_eyes"), false),
    GoogleCompatEmoji(0x1F92F, arrayOf("exploding_head", "shocked_face_with_exploding_head"), false),
    GoogleCompatEmoji(0x1F920, arrayOf("face_with_cowboy_hat"), false),
    GoogleCompatEmoji(0x1F973, arrayOf("partying_face"), false),
    GoogleCompatEmoji(0x1F978, arrayOf("disguised_face"), false),
    GoogleCompatEmoji(0x1F60E, arrayOf("sunglasses"), false),
    GoogleCompatEmoji(0x1F913, arrayOf("nerd_face"), false),
    GoogleCompatEmoji(0x1F9D0, arrayOf("face_with_monocle"), false),
    GoogleCompatEmoji(0x1F615, arrayOf("confused"), false),
    GoogleCompatEmoji(0x1FAE4, arrayOf("face_with_diagonal_mouth"), false),
    GoogleCompatEmoji(0x1F61F, arrayOf("worried"), false),
    GoogleCompatEmoji(0x1F641, arrayOf("slightly_frowning_face"), false),
    GoogleCompatEmoji(intArrayOf(0x2639, 0xFE0F), arrayOf("white_frowning_face"), false),
    GoogleCompatEmoji(0x1F62E, arrayOf("open_mouth"), false),
    GoogleCompatEmoji(0x1F62F, arrayOf("hushed"), false),
    GoogleCompatEmoji(0x1F632, arrayOf("astonished"), false),
    GoogleCompatEmoji(0x1F633, arrayOf("flushed"), false),
    GoogleCompatEmoji(0x1F97A, arrayOf("pleading_face"), false),
    GoogleCompatEmoji(0x1F979, arrayOf("face_holding_back_tears"), false),
    GoogleCompatEmoji(0x1F626, arrayOf("frowning"), false),
    GoogleCompatEmoji(0x1F627, arrayOf("anguished"), false),
    GoogleCompatEmoji(0x1F628, arrayOf("fearful"), false),
    GoogleCompatEmoji(0x1F630, arrayOf("cold_sweat"), false),
    GoogleCompatEmoji(0x1F625, arrayOf("disappointed_relieved"), false),
    GoogleCompatEmoji(0x1F622, arrayOf("cry"), false),
    GoogleCompatEmoji(0x1F62D, arrayOf("sob"), false),
    GoogleCompatEmoji(0x1F631, arrayOf("scream"), false),
    GoogleCompatEmoji(0x1F616, arrayOf("confounded"), false),
    GoogleCompatEmoji(0x1F623, arrayOf("persevere"), false),
    GoogleCompatEmoji(0x1F61E, arrayOf("disappointed"), false),
    GoogleCompatEmoji(0x1F613, arrayOf("sweat"), false),
    GoogleCompatEmoji(0x1F629, arrayOf("weary"), false),
    GoogleCompatEmoji(0x1F62B, arrayOf("tired_face"), false),
    GoogleCompatEmoji(0x1F971, arrayOf("yawning_face"), false),
    GoogleCompatEmoji(0x1F624, arrayOf("triumph"), false),
    GoogleCompatEmoji(0x1F621, arrayOf("rage"), false),
    GoogleCompatEmoji(0x1F620, arrayOf("angry"), false),
    GoogleCompatEmoji(0x1F92C, arrayOf("face_with_symbols_on_mouth", "serious_face_with_symbols_covering_mouth"), false),
    GoogleCompatEmoji(0x1F608, arrayOf("smiling_imp"), false),
    GoogleCompatEmoji(0x1F47F, arrayOf("imp"), false),
    GoogleCompatEmoji(0x1F480, arrayOf("skull"), false),
    GoogleCompatEmoji(intArrayOf(0x2620, 0xFE0F), arrayOf("skull_and_crossbones"), false),
    GoogleCompatEmoji(0x1F4A9, arrayOf("hankey", "poop", "shit"), false),
    GoogleCompatEmoji(0x1F921, arrayOf("clown_face"), false),
    GoogleCompatEmoji(0x1F479, arrayOf("japanese_ogre"), false),
    GoogleCompatEmoji(0x1F47A, arrayOf("japanese_goblin"), false),
    GoogleCompatEmoji(0x1F47B, arrayOf("ghost"), false),
    GoogleCompatEmoji(0x1F47D, arrayOf("alien"), false),
    GoogleCompatEmoji(0x1F47E, arrayOf("space_invader"), false),
    GoogleCompatEmoji(0x1F916, arrayOf("robot_face"), false),
    GoogleCompatEmoji(0x1F63A, arrayOf("smiley_cat"), false),
    GoogleCompatEmoji(0x1F638, arrayOf("smile_cat"), false),
    GoogleCompatEmoji(0x1F639, arrayOf("joy_cat"), false),
    GoogleCompatEmoji(0x1F63B, arrayOf("heart_eyes_cat"), false),
    GoogleCompatEmoji(0x1F63C, arrayOf("smirk_cat"), false),
    GoogleCompatEmoji(0x1F63D, arrayOf("kissing_cat"), false),
    GoogleCompatEmoji(0x1F640, arrayOf("scream_cat"), false),
    GoogleCompatEmoji(0x1F63F, arrayOf("crying_cat_face"), false),
    GoogleCompatEmoji(0x1F63E, arrayOf("pouting_cat"), false),
    GoogleCompatEmoji(0x1F648, arrayOf("see_no_evil"), false),
    GoogleCompatEmoji(0x1F649, arrayOf("hear_no_evil"), false),
    GoogleCompatEmoji(0x1F64A, arrayOf("speak_no_evil"), false),
    GoogleCompatEmoji(0x1F48B, arrayOf("kiss"), false),
    GoogleCompatEmoji(0x1F48C, arrayOf("love_letter"), false),
    GoogleCompatEmoji(0x1F498, arrayOf("cupid"), false),
    GoogleCompatEmoji(0x1F49D, arrayOf("gift_heart"), false),
    GoogleCompatEmoji(0x1F496, arrayOf("sparkling_heart"), false),
    GoogleCompatEmoji(0x1F497, arrayOf("heartpulse"), false),
    GoogleCompatEmoji(0x1F493, arrayOf("heartbeat"), false),
    GoogleCompatEmoji(0x1F49E, arrayOf("revolving_hearts"), false),
    GoogleCompatEmoji(0x1F495, arrayOf("two_hearts"), false),
    GoogleCompatEmoji(0x1F49F, arrayOf("heart_decoration"), false),
    GoogleCompatEmoji(intArrayOf(0x2763, 0xFE0F), arrayOf("heavy_heart_exclamation_mark_ornament"), false),
    GoogleCompatEmoji(0x1F494, arrayOf("broken_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1F525), arrayOf("heart_on_fire"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1FA79), arrayOf("mending_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F), arrayOf("heart"), false),
    GoogleCompatEmoji(0x1F9E1, arrayOf("orange_heart"), false),
    GoogleCompatEmoji(0x1F49B, arrayOf("yellow_heart"), false),
    GoogleCompatEmoji(0x1F49A, arrayOf("green_heart"), false),
    GoogleCompatEmoji(0x1F499, arrayOf("blue_heart"), false),
    GoogleCompatEmoji(0x1F49C, arrayOf("purple_heart"), false),
    GoogleCompatEmoji(0x1F90E, arrayOf("brown_heart"), false),
    GoogleCompatEmoji(0x1F5A4, arrayOf("black_heart"), false),
    GoogleCompatEmoji(0x1F90D, arrayOf("white_heart"), false),
    GoogleCompatEmoji(0x1F4AF, arrayOf("100"), false),
    GoogleCompatEmoji(0x1F4A2, arrayOf("anger"), false),
    GoogleCompatEmoji(0x1F4A5, arrayOf("boom", "collision"), false),
    GoogleCompatEmoji(0x1F4AB, arrayOf("dizzy"), false),
    GoogleCompatEmoji(0x1F4A6, arrayOf("sweat_drops"), false),
    GoogleCompatEmoji(0x1F4A8, arrayOf("dash"), false),
    GoogleCompatEmoji(intArrayOf(0x1F573, 0xFE0F), arrayOf("hole"), false),
    GoogleCompatEmoji(0x1F4A3, arrayOf("bomb"), false),
    GoogleCompatEmoji(0x1F4AC, arrayOf("speech_balloon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F441, 0xFE0F, 0x200D, 0x1F5E8, 0xFE0F), arrayOf("eye-in-speech-bubble"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5E8, 0xFE0F), arrayOf("left_speech_bubble"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5EF, 0xFE0F), arrayOf("right_anger_bubble"), false),
    GoogleCompatEmoji(0x1F4AD, arrayOf("thought_balloon"), false),
    GoogleCompatEmoji(0x1F4A4, arrayOf("zzz"), false),
    GoogleCompatEmoji(
      0x1F44B, arrayOf("wave"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44B, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44B, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44B, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44B, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44B, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91A, arrayOf("raised_back_of_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91A, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91A, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91A, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91A, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91A, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      intArrayOf(0x1F590, 0xFE0F), arrayOf("raised_hand_with_fingers_splayed"), false,
      GoogleCompatEmoji(intArrayOf(0x1F590, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F590, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F590, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F590, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F590, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x270B, arrayOf("hand", "raised_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x270B, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270B, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270B, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270B, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270B, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F596, arrayOf("spock-hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1F596, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F596, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F596, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F596, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F596, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF1, arrayOf("rightwards_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF2, arrayOf("leftwards_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF2, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF2, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF2, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF2, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF2, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF3, arrayOf("palm_down_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF3, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF3, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF3, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF3, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF3, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF4, arrayOf("palm_up_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF4, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF4, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF4, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF4, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF4, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F44C, arrayOf("ok_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44C, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44C, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44C, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44C, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44C, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F90C, arrayOf("pinched_fingers"), false,
      GoogleCompatEmoji(intArrayOf(0x1F90C, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90C, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90C, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90C, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90C, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F90F, arrayOf("pinching_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1F90F, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90F, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90F, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90F, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F90F, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      intArrayOf(0x270C, 0xFE0F), arrayOf("v"), false,
      GoogleCompatEmoji(intArrayOf(0x270C, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270C, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270C, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270C, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270C, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91E, arrayOf("crossed_fingers", "hand_with_index_and_middle_fingers_crossed"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91E, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91E, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91E, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91E, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91E, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF0, arrayOf("hand_with_index_finger_and_thumb_crossed"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF0, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF0, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF0, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF0, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF0, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91F, arrayOf("i_love_you_hand_sign"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91F, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91F, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91F, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91F, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91F, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F918, arrayOf("the_horns", "sign_of_the_horns"), false,
      GoogleCompatEmoji(intArrayOf(0x1F918, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F918, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F918, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F918, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F918, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F919, arrayOf("call_me_hand"), false,
      GoogleCompatEmoji(intArrayOf(0x1F919, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F919, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F919, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F919, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F919, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F448, arrayOf("point_left"), false,
      GoogleCompatEmoji(intArrayOf(0x1F448, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F448, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F448, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F448, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F448, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F449, arrayOf("point_right"), false,
      GoogleCompatEmoji(intArrayOf(0x1F449, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F449, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F449, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F449, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F449, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F446, arrayOf("point_up_2"), false,
      GoogleCompatEmoji(intArrayOf(0x1F446, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F446, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F446, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F446, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F446, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F595, arrayOf("middle_finger", "reversed_hand_with_middle_finger_extended"), false,
      GoogleCompatEmoji(intArrayOf(0x1F595, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F595, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F595, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F595, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F595, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F447, arrayOf("point_down"), false,
      GoogleCompatEmoji(intArrayOf(0x1F447, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F447, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F447, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F447, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F447, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      intArrayOf(0x261D, 0xFE0F), arrayOf("point_up"), false,
      GoogleCompatEmoji(intArrayOf(0x261D, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x261D, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x261D, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x261D, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x261D, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF5, arrayOf("index_pointing_at_the_viewer"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF5, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF5, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF5, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF5, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF5, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F44D, arrayOf("+1", "thumbsup"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44D, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44D, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44D, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44D, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44D, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F44E, arrayOf("-1", "thumbsdown"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44E, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44E, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44E, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44E, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44E, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x270A, arrayOf("fist"), false,
      GoogleCompatEmoji(intArrayOf(0x270A, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270A, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270A, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270A, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x270A, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F44A, arrayOf("facepunch", "punch"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44A, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44A, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44A, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44A, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44A, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91B, arrayOf("left-facing_fist"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91B, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91B, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91B, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91B, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91B, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91C, arrayOf("right-facing_fist"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91C, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91C, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91C, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91C, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91C, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F44F, arrayOf("clap"), false,
      GoogleCompatEmoji(intArrayOf(0x1F44F, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44F, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44F, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44F, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F44F, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F64C, arrayOf("raised_hands"), false,
      GoogleCompatEmoji(intArrayOf(0x1F64C, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F64C, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F64C, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F64C, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F64C, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1FAF6, arrayOf("heart_hands"), false,
      GoogleCompatEmoji(intArrayOf(0x1FAF6, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF6, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF6, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF6, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF6, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F450, arrayOf("open_hands"), false,
      GoogleCompatEmoji(intArrayOf(0x1F450, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F450, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F450, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F450, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F450, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F932, arrayOf("palms_up_together"), false,
      GoogleCompatEmoji(intArrayOf(0x1F932, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F932, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F932, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F932, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F932, 0x1F3FF), emptyArray<String>(), false),
    ),
    GoogleCompatEmoji(
      0x1F91D, arrayOf("handshake"), false,
      GoogleCompatEmoji(intArrayOf(0x1F91D, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91D, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91D, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91D, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1F91D, 0x1F3FF), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FB, 0x200D, 0x1FAF2, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FB, 0x200D, 0x1FAF2, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FB, 0x200D, 0x1FAF2, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FB, 0x200D, 0x1FAF2, 0x1F3FF), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FC, 0x200D, 0x1FAF2, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FC, 0x200D, 0x1FAF2, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FC, 0x200D, 0x1FAF2, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FC, 0x200D, 0x1FAF2, 0x1F3FF), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FD, 0x200D, 0x1FAF2, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FD, 0x200D, 0x1FAF2, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FD, 0x200D, 0x1FAF2, 0x1F3FE), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FD, 0x200D, 0x1FAF2, 0x1F3FF), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FE, 0x200D, 0x1FAF2, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FE, 0x200D, 0x1FAF2, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FE, 0x200D, 0x1FAF2, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FE, 0x200D, 0x1FAF2, 0x1F3FF), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FF, 0x200D, 0x1FAF2, 0x1F3FB), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FF, 0x200D, 0x1FAF2, 0x1F3FC), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FF, 0x200D, 0x1FAF2, 0x1F3FD), emptyArray<String>(), false),
      GoogleCompatEmoji(intArrayOf(0x1FAF1, 0x1F3FF, 0x200D, 0x1FAF2, 0x1F3FE), emptyArray<String>(), false),
    ),
  )
}
