/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SmileysAndPeopleCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F600), listOf("grinning"), false),
    GoogleCompatEmoji(intArrayOf(0x1F603), listOf("smiley"), false),
    GoogleCompatEmoji(intArrayOf(0x1F604), listOf("smile"), false),
    GoogleCompatEmoji(intArrayOf(0x1F601), listOf("grin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F606), listOf("laughing", "satisfied"), false),
    GoogleCompatEmoji(intArrayOf(0x1F605), listOf("sweat_smile"), false),
    GoogleCompatEmoji(intArrayOf(0x1F923), listOf("rolling_on_the_floor_laughing"), false),
    GoogleCompatEmoji(intArrayOf(0x1F602), listOf("joy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F642), listOf("slightly_smiling_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F643), listOf("upside_down_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE0), listOf("melting_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F609), listOf("wink"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60A), listOf("blush"), false),
    GoogleCompatEmoji(intArrayOf(0x1F607), listOf("innocent"), false),
    GoogleCompatEmoji(intArrayOf(0x1F970), listOf("smiling_face_with_3_hearts"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60D), listOf("heart_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F929), listOf("star-struck", "grinning_face_with_star_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F618), listOf("kissing_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F617), listOf("kissing"), false),
    GoogleCompatEmoji(intArrayOf(0x263A, 0xFE0F), listOf("relaxed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61A), listOf("kissing_closed_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F619), listOf("kissing_smiling_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F972), listOf("smiling_face_with_tear"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60B), listOf("yum"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61B), listOf("stuck_out_tongue"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61C), listOf("stuck_out_tongue_winking_eye"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92A), listOf("zany_face", "grinning_face_with_one_large_and_one_small_eye"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61D), listOf("stuck_out_tongue_closed_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F911), listOf("money_mouth_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F917), listOf("hugging_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92D), listOf("face_with_hand_over_mouth", "smiling_face_with_smiling_eyes_and_hand_covering_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE2), listOf("face_with_open_eyes_and_hand_over_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE3), listOf("face_with_peeking_eye"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92B), listOf("shushing_face", "face_with_finger_covering_closed_lips"), false),
    GoogleCompatEmoji(intArrayOf(0x1F914), listOf("thinking_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE1), listOf("saluting_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F910), listOf("zipper_mouth_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F928), listOf("face_with_raised_eyebrow", "face_with_one_eyebrow_raised"), false),
    GoogleCompatEmoji(intArrayOf(0x1F610), listOf("neutral_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F611), listOf("expressionless"), false),
    GoogleCompatEmoji(intArrayOf(0x1F636), listOf("no_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE5), listOf("dotted_line_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F636, 0x200D, 0x1F32B, 0xFE0F), listOf("face_in_clouds"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60F), listOf("smirk"), false),
    GoogleCompatEmoji(intArrayOf(0x1F612), listOf("unamused"), false),
    GoogleCompatEmoji(intArrayOf(0x1F644), listOf("face_with_rolling_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62C), listOf("grimacing"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62E, 0x200D, 0x1F4A8), listOf("face_exhaling"), false),
    GoogleCompatEmoji(intArrayOf(0x1F925), listOf("lying_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60C), listOf("relieved"), false),
    GoogleCompatEmoji(intArrayOf(0x1F614), listOf("pensive"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62A), listOf("sleepy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F924), listOf("drooling_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F634), listOf("sleeping"), false),
    GoogleCompatEmoji(intArrayOf(0x1F637), listOf("mask"), false),
    GoogleCompatEmoji(intArrayOf(0x1F912), listOf("face_with_thermometer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F915), listOf("face_with_head_bandage"), false),
    GoogleCompatEmoji(intArrayOf(0x1F922), listOf("nauseated_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92E), listOf("face_vomiting", "face_with_open_mouth_vomiting"), false),
    GoogleCompatEmoji(intArrayOf(0x1F927), listOf("sneezing_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F975), listOf("hot_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F976), listOf("cold_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F974), listOf("woozy_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F635), listOf("dizzy_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F635, 0x200D, 0x1F4AB), listOf("face_with_spiral_eyes"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92F), listOf("exploding_head", "shocked_face_with_exploding_head"), false),
    GoogleCompatEmoji(intArrayOf(0x1F920), listOf("face_with_cowboy_hat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F973), listOf("partying_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F978), listOf("disguised_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F60E), listOf("sunglasses"), false),
    GoogleCompatEmoji(intArrayOf(0x1F913), listOf("nerd_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9D0), listOf("face_with_monocle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F615), listOf("confused"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAE4), listOf("face_with_diagonal_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61F), listOf("worried"), false),
    GoogleCompatEmoji(intArrayOf(0x1F641), listOf("slightly_frowning_face"), false),
    GoogleCompatEmoji(intArrayOf(0x2639, 0xFE0F), listOf("white_frowning_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62E), listOf("open_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62F), listOf("hushed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F632), listOf("astonished"), false),
    GoogleCompatEmoji(intArrayOf(0x1F633), listOf("flushed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F97A), listOf("pleading_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F979), listOf("face_holding_back_tears"), false),
    GoogleCompatEmoji(intArrayOf(0x1F626), listOf("frowning"), false),
    GoogleCompatEmoji(intArrayOf(0x1F627), listOf("anguished"), false),
    GoogleCompatEmoji(intArrayOf(0x1F628), listOf("fearful"), false),
    GoogleCompatEmoji(intArrayOf(0x1F630), listOf("cold_sweat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F625), listOf("disappointed_relieved"), false),
    GoogleCompatEmoji(intArrayOf(0x1F622), listOf("cry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62D), listOf("sob"), false),
    GoogleCompatEmoji(intArrayOf(0x1F631), listOf("scream"), false),
    GoogleCompatEmoji(intArrayOf(0x1F616), listOf("confounded"), false),
    GoogleCompatEmoji(intArrayOf(0x1F623), listOf("persevere"), false),
    GoogleCompatEmoji(intArrayOf(0x1F61E), listOf("disappointed"), false),
    GoogleCompatEmoji(intArrayOf(0x1F613), listOf("sweat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F629), listOf("weary"), false),
    GoogleCompatEmoji(intArrayOf(0x1F62B), listOf("tired_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F971), listOf("yawning_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F624), listOf("triumph"), false),
    GoogleCompatEmoji(intArrayOf(0x1F621), listOf("rage"), false),
    GoogleCompatEmoji(intArrayOf(0x1F620), listOf("angry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F92C), listOf("face_with_symbols_on_mouth", "serious_face_with_symbols_covering_mouth"), false),
    GoogleCompatEmoji(intArrayOf(0x1F608), listOf("smiling_imp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F47F), listOf("imp"), false),
    GoogleCompatEmoji(intArrayOf(0x1F480), listOf("skull"), false),
    GoogleCompatEmoji(intArrayOf(0x2620, 0xFE0F), listOf("skull_and_crossbones"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4A9), listOf("hankey", "poop", "shit"), false),
    GoogleCompatEmoji(intArrayOf(0x1F921), listOf("clown_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F479), listOf("japanese_ogre"), false),
    GoogleCompatEmoji(intArrayOf(0x1F47A), listOf("japanese_goblin"), false),
    GoogleCompatEmoji(intArrayOf(0x1F47B), listOf("ghost"), false),
    GoogleCompatEmoji(intArrayOf(0x1F47D), listOf("alien"), false),
    GoogleCompatEmoji(intArrayOf(0x1F47E), listOf("space_invader"), false),
    GoogleCompatEmoji(intArrayOf(0x1F916), listOf("robot_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63A), listOf("smiley_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F638), listOf("smile_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F639), listOf("joy_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63B), listOf("heart_eyes_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63C), listOf("smirk_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63D), listOf("kissing_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F640), listOf("scream_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63F), listOf("crying_cat_face"), false),
    GoogleCompatEmoji(intArrayOf(0x1F63E), listOf("pouting_cat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F648), listOf("see_no_evil"), false),
    GoogleCompatEmoji(intArrayOf(0x1F649), listOf("hear_no_evil"), false),
    GoogleCompatEmoji(intArrayOf(0x1F64A), listOf("speak_no_evil"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48B), listOf("kiss"), false),
    GoogleCompatEmoji(intArrayOf(0x1F48C), listOf("love_letter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F498), listOf("cupid"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49D), listOf("gift_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F496), listOf("sparkling_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F497), listOf("heartpulse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F493), listOf("heartbeat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49E), listOf("revolving_hearts"), false),
    GoogleCompatEmoji(intArrayOf(0x1F495), listOf("two_hearts"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49F), listOf("heart_decoration"), false),
    GoogleCompatEmoji(intArrayOf(0x2763, 0xFE0F), listOf("heavy_heart_exclamation_mark_ornament"), false),
    GoogleCompatEmoji(intArrayOf(0x1F494), listOf("broken_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1F525), listOf("heart_on_fire"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F, 0x200D, 0x1FA79), listOf("mending_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x2764, 0xFE0F), listOf("heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9E1), listOf("orange_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49B), listOf("yellow_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49A), listOf("green_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F499), listOf("blue_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F49C), listOf("purple_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F90E), listOf("brown_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5A4), listOf("black_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F90D), listOf("white_heart"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4AF), listOf("100"), false),
  )
}
