/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SymbolsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F3E7), 0, 1), listOf("atm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AE), 0, 1), listOf("put_litter_in_its_place"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B0), 0, 1), listOf("potable_water"), false),
    GoogleCompatEmoji(String(intArrayOf(0x267F), 0, 1), listOf("wheelchair"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B9), 0, 1), listOf("mens"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BA), 0, 1), listOf("womens"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BB), 0, 1), listOf("restroom"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BC), 0, 1), listOf("baby_symbol"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BE), 0, 1), listOf("wc"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C2), 0, 1), listOf("passport_control"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C3), 0, 1), listOf("customs"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C4), 0, 1), listOf("baggage_claim"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C5), 0, 1), listOf("left_luggage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26A0, 0xFE0F), 0, 2), listOf("warning"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B8), 0, 1), listOf("children_crossing"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26D4), 0, 1), listOf("no_entry"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AB), 0, 1), listOf("no_entry_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B3), 0, 1), listOf("no_bicycles"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AD), 0, 1), listOf("no_smoking"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AF), 0, 1), listOf("do_not_litter"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B1), 0, 1), listOf("non-potable_water"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6B7), 0, 1), listOf("no_pedestrians"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4F5), 0, 1), listOf("no_mobile_phones"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51E), 0, 1), listOf("underage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2622, 0xFE0F), 0, 2), listOf("radioactive_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2623, 0xFE0F), 0, 2), listOf("biohazard_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B06, 0xFE0F), 0, 2), listOf("arrow_up"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2197, 0xFE0F), 0, 2), listOf("arrow_upper_right"), false),
    GoogleCompatEmoji(String(intArrayOf(0x27A1, 0xFE0F), 0, 2), listOf("arrow_right"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2198, 0xFE0F), 0, 2), listOf("arrow_lower_right"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B07, 0xFE0F), 0, 2), listOf("arrow_down"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2199, 0xFE0F), 0, 2), listOf("arrow_lower_left"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B05, 0xFE0F), 0, 2), listOf("arrow_left"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2196, 0xFE0F), 0, 2), listOf("arrow_upper_left"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2195, 0xFE0F), 0, 2), listOf("arrow_up_down"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2194, 0xFE0F), 0, 2), listOf("left_right_arrow"), false),
    GoogleCompatEmoji(String(intArrayOf(0x21A9, 0xFE0F), 0, 2), listOf("leftwards_arrow_with_hook"), false),
    GoogleCompatEmoji(String(intArrayOf(0x21AA, 0xFE0F), 0, 2), listOf("arrow_right_hook"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2934, 0xFE0F), 0, 2), listOf("arrow_heading_up"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2935, 0xFE0F), 0, 2), listOf("arrow_heading_down"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F503), 0, 1), listOf("arrows_clockwise"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F504), 0, 1), listOf("arrows_counterclockwise"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F519), 0, 1), listOf("back"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51A), 0, 1), listOf("end"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51B), 0, 1), listOf("on"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51C), 0, 1), listOf("soon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51D), 0, 1), listOf("top"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D0), 0, 1), listOf("place_of_worship"), false),
    GoogleCompatEmoji(String(intArrayOf(0x269B, 0xFE0F), 0, 2), listOf("atom_symbol"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F549, 0xFE0F), 0, 2), listOf("om_symbol"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2721, 0xFE0F), 0, 2), listOf("star_of_david"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2638, 0xFE0F), 0, 2), listOf("wheel_of_dharma"), false),
    GoogleCompatEmoji(String(intArrayOf(0x262F, 0xFE0F), 0, 2), listOf("yin_yang"), false),
    GoogleCompatEmoji(String(intArrayOf(0x271D, 0xFE0F), 0, 2), listOf("latin_cross"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2626, 0xFE0F), 0, 2), listOf("orthodox_cross"), false),
    GoogleCompatEmoji(String(intArrayOf(0x262A, 0xFE0F), 0, 2), listOf("star_and_crescent"), false),
    GoogleCompatEmoji(String(intArrayOf(0x262E, 0xFE0F), 0, 2), listOf("peace_symbol"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F54E), 0, 1), listOf("menorah_with_nine_branches"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52F), 0, 1), listOf("six_pointed_star"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2648), 0, 1), listOf("aries"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2649), 0, 1), listOf("taurus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264A), 0, 1), listOf("gemini"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264B), 0, 1), listOf("cancer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264C), 0, 1), listOf("leo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264D), 0, 1), listOf("virgo"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264E), 0, 1), listOf("libra"), false),
    GoogleCompatEmoji(String(intArrayOf(0x264F), 0, 1), listOf("scorpius"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2650), 0, 1), listOf("sagittarius"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2651), 0, 1), listOf("capricorn"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2652), 0, 1), listOf("aquarius"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2653), 0, 1), listOf("pisces"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26CE), 0, 1), listOf("ophiuchus"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F500), 0, 1), listOf("twisted_rightwards_arrows"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F501), 0, 1), listOf("repeat"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F502), 0, 1), listOf("repeat_one"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25B6, 0xFE0F), 0, 2), listOf("arrow_forward"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23E9), 0, 1), listOf("fast_forward"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23ED, 0xFE0F), 0, 2), listOf("black_right_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23EF, 0xFE0F), 0, 2), listOf("black_right_pointing_triangle_with_double_vertical_bar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25C0, 0xFE0F), 0, 2), listOf("arrow_backward"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23EA), 0, 1), listOf("rewind"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23EE, 0xFE0F), 0, 2), listOf("black_left_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F53C), 0, 1), listOf("arrow_up_small"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23EB), 0, 1), listOf("arrow_double_up"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F53D), 0, 1), listOf("arrow_down_small"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23EC), 0, 1), listOf("arrow_double_down"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F8, 0xFE0F), 0, 2), listOf("double_vertical_bar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23F9, 0xFE0F), 0, 2), listOf("black_square_for_stop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23FA, 0xFE0F), 0, 2), listOf("black_circle_for_record"), false),
    GoogleCompatEmoji(String(intArrayOf(0x23CF, 0xFE0F), 0, 2), listOf("eject"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3A6), 0, 1), listOf("cinema"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F505), 0, 1), listOf("low_brightness"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F506), 0, 1), listOf("high_brightness"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4F6), 0, 1), listOf("signal_strength"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4F3), 0, 1), listOf("vibration_mode"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4F4), 0, 1), listOf("mobile_phone_off"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2640, 0xFE0F), 0, 2), listOf("female_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2642, 0xFE0F), 0, 2), listOf("male_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26A7, 0xFE0F), 0, 2), listOf("transgender_symbol"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2716, 0xFE0F), 0, 2), listOf("heavy_multiplication_x"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2795), 0, 1), listOf("heavy_plus_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2796), 0, 1), listOf("heavy_minus_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2797), 0, 1), listOf("heavy_division_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7F0), 0, 1), listOf("heavy_equals_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x267E, 0xFE0F), 0, 2), listOf("infinity"), false),
    GoogleCompatEmoji(String(intArrayOf(0x203C, 0xFE0F), 0, 2), listOf("bangbang"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2049, 0xFE0F), 0, 2), listOf("interrobang"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2753), 0, 1), listOf("question"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2754), 0, 1), listOf("grey_question"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2755), 0, 1), listOf("grey_exclamation"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2757), 0, 1), listOf("exclamation", "heavy_exclamation_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x3030, 0xFE0F), 0, 2), listOf("wavy_dash"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B1), 0, 1), listOf("currency_exchange"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B2), 0, 1), listOf("heavy_dollar_sign"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2695, 0xFE0F), 0, 2), listOf("medical_symbol", "staff_of_aesculapius"), false),
    GoogleCompatEmoji(String(intArrayOf(0x267B, 0xFE0F), 0, 2), listOf("recycle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x269C, 0xFE0F), 0, 2), listOf("fleur_de_lis"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F531), 0, 1), listOf("trident"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4DB), 0, 1), listOf("name_badge"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F530), 0, 1), listOf("beginner"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B55), 0, 1), listOf("o"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2705), 0, 1), listOf("white_check_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2611, 0xFE0F), 0, 2), listOf("ballot_box_with_check"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2714, 0xFE0F), 0, 2), listOf("heavy_check_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x274C), 0, 1), listOf("x"), false),
    GoogleCompatEmoji(String(intArrayOf(0x274E), 0, 1), listOf("negative_squared_cross_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x27B0), 0, 1), listOf("curly_loop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x27BF), 0, 1), listOf("loop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x303D, 0xFE0F), 0, 2), listOf("part_alternation_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2733, 0xFE0F), 0, 2), listOf("eight_spoked_asterisk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2734, 0xFE0F), 0, 2), listOf("eight_pointed_black_star"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2747, 0xFE0F), 0, 2), listOf("sparkle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x00A9, 0xFE0F), 0, 2), listOf("copyright"), false),
    GoogleCompatEmoji(String(intArrayOf(0x00AE, 0xFE0F), 0, 2), listOf("registered"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2122, 0xFE0F), 0, 2), listOf("tm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0023, 0xFE0F, 0x20E3), 0, 3), listOf("hash"), false),
    GoogleCompatEmoji(String(intArrayOf(0x002A, 0xFE0F, 0x20E3), 0, 3), listOf("keycap_star"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0030, 0xFE0F, 0x20E3), 0, 3), listOf("zero"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0031, 0xFE0F, 0x20E3), 0, 3), listOf("one"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0032, 0xFE0F, 0x20E3), 0, 3), listOf("two"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0033, 0xFE0F, 0x20E3), 0, 3), listOf("three"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0034, 0xFE0F, 0x20E3), 0, 3), listOf("four"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0035, 0xFE0F, 0x20E3), 0, 3), listOf("five"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0036, 0xFE0F, 0x20E3), 0, 3), listOf("six"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0037, 0xFE0F, 0x20E3), 0, 3), listOf("seven"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0038, 0xFE0F, 0x20E3), 0, 3), listOf("eight"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0039, 0xFE0F, 0x20E3), 0, 3), listOf("nine"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51F), 0, 1), listOf("keycap_ten"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F520), 0, 1), listOf("capital_abcd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F521), 0, 1), listOf("abcd"), false),
  )
}
