/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SymbolsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F3E7), arrayOf("atm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AE), arrayOf("put_litter_in_its_place"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B0), arrayOf("potable_water"), false),
    GoogleCompatEmoji(intArrayOf(0x267F), arrayOf("wheelchair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B9), arrayOf("mens"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BA), arrayOf("womens"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BB), arrayOf("restroom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BC), arrayOf("baby_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BE), arrayOf("wc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C2), arrayOf("passport_control"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C3), arrayOf("customs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C4), arrayOf("baggage_claim"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C5), arrayOf("left_luggage"), false),
    GoogleCompatEmoji(intArrayOf(0x26A0, 0xFE0F), arrayOf("warning"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B8), arrayOf("children_crossing"), false),
    GoogleCompatEmoji(intArrayOf(0x26D4), arrayOf("no_entry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AB), arrayOf("no_entry_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B3), arrayOf("no_bicycles"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AD), arrayOf("no_smoking"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AF), arrayOf("do_not_litter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B1), arrayOf("non-potable_water"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B7), arrayOf("no_pedestrians"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F5), arrayOf("no_mobile_phones"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51E), arrayOf("underage"), false),
    GoogleCompatEmoji(intArrayOf(0x2622, 0xFE0F), arrayOf("radioactive_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2623, 0xFE0F), arrayOf("biohazard_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2B06, 0xFE0F), arrayOf("arrow_up"), false),
    GoogleCompatEmoji(intArrayOf(0x2197, 0xFE0F), arrayOf("arrow_upper_right"), false),
    GoogleCompatEmoji(intArrayOf(0x27A1, 0xFE0F), arrayOf("arrow_right"), false),
    GoogleCompatEmoji(intArrayOf(0x2198, 0xFE0F), arrayOf("arrow_lower_right"), false),
    GoogleCompatEmoji(intArrayOf(0x2B07, 0xFE0F), arrayOf("arrow_down"), false),
    GoogleCompatEmoji(intArrayOf(0x2199, 0xFE0F), arrayOf("arrow_lower_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2B05, 0xFE0F), arrayOf("arrow_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2196, 0xFE0F), arrayOf("arrow_upper_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2195, 0xFE0F), arrayOf("arrow_up_down"), false),
    GoogleCompatEmoji(intArrayOf(0x2194, 0xFE0F), arrayOf("left_right_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x21A9, 0xFE0F), arrayOf("leftwards_arrow_with_hook"), false),
    GoogleCompatEmoji(intArrayOf(0x21AA, 0xFE0F), arrayOf("arrow_right_hook"), false),
    GoogleCompatEmoji(intArrayOf(0x2934, 0xFE0F), arrayOf("arrow_heading_up"), false),
    GoogleCompatEmoji(intArrayOf(0x2935, 0xFE0F), arrayOf("arrow_heading_down"), false),
    GoogleCompatEmoji(intArrayOf(0x1F503), arrayOf("arrows_clockwise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F504), arrayOf("arrows_counterclockwise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F519), arrayOf("back"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51A), arrayOf("end"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51B), arrayOf("on"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51C), arrayOf("soon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51D), arrayOf("top"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D0), arrayOf("place_of_worship"), false),
    GoogleCompatEmoji(intArrayOf(0x269B, 0xFE0F), arrayOf("atom_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F549, 0xFE0F), arrayOf("om_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x2721, 0xFE0F), arrayOf("star_of_david"), false),
    GoogleCompatEmoji(intArrayOf(0x2638, 0xFE0F), arrayOf("wheel_of_dharma"), false),
    GoogleCompatEmoji(intArrayOf(0x262F, 0xFE0F), arrayOf("yin_yang"), false),
    GoogleCompatEmoji(intArrayOf(0x271D, 0xFE0F), arrayOf("latin_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x2626, 0xFE0F), arrayOf("orthodox_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x262A, 0xFE0F), arrayOf("star_and_crescent"), false),
    GoogleCompatEmoji(intArrayOf(0x262E, 0xFE0F), arrayOf("peace_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54E), arrayOf("menorah_with_nine_branches"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52F), arrayOf("six_pointed_star"), false),
    GoogleCompatEmoji(intArrayOf(0x2648), arrayOf("aries"), false),
    GoogleCompatEmoji(intArrayOf(0x2649), arrayOf("taurus"), false),
    GoogleCompatEmoji(intArrayOf(0x264A), arrayOf("gemini"), false),
    GoogleCompatEmoji(intArrayOf(0x264B), arrayOf("cancer"), false),
    GoogleCompatEmoji(intArrayOf(0x264C), arrayOf("leo"), false),
    GoogleCompatEmoji(intArrayOf(0x264D), arrayOf("virgo"), false),
    GoogleCompatEmoji(intArrayOf(0x264E), arrayOf("libra"), false),
    GoogleCompatEmoji(intArrayOf(0x264F), arrayOf("scorpius"), false),
    GoogleCompatEmoji(intArrayOf(0x2650), arrayOf("sagittarius"), false),
    GoogleCompatEmoji(intArrayOf(0x2651), arrayOf("capricorn"), false),
    GoogleCompatEmoji(intArrayOf(0x2652), arrayOf("aquarius"), false),
    GoogleCompatEmoji(intArrayOf(0x2653), arrayOf("pisces"), false),
    GoogleCompatEmoji(intArrayOf(0x26CE), arrayOf("ophiuchus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F500), arrayOf("twisted_rightwards_arrows"), false),
    GoogleCompatEmoji(intArrayOf(0x1F501), arrayOf("repeat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F502), arrayOf("repeat_one"), false),
    GoogleCompatEmoji(intArrayOf(0x25B6, 0xFE0F), arrayOf("arrow_forward"), false),
    GoogleCompatEmoji(intArrayOf(0x23E9), arrayOf("fast_forward"), false),
    GoogleCompatEmoji(intArrayOf(0x23ED, 0xFE0F), arrayOf("black_right_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x23EF, 0xFE0F), arrayOf("black_right_pointing_triangle_with_double_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x25C0, 0xFE0F), arrayOf("arrow_backward"), false),
    GoogleCompatEmoji(intArrayOf(0x23EA), arrayOf("rewind"), false),
    GoogleCompatEmoji(intArrayOf(0x23EE, 0xFE0F), arrayOf("black_left_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F53C), arrayOf("arrow_up_small"), false),
    GoogleCompatEmoji(intArrayOf(0x23EB), arrayOf("arrow_double_up"), false),
    GoogleCompatEmoji(intArrayOf(0x1F53D), arrayOf("arrow_down_small"), false),
    GoogleCompatEmoji(intArrayOf(0x23EC), arrayOf("arrow_double_down"), false),
    GoogleCompatEmoji(intArrayOf(0x23F8, 0xFE0F), arrayOf("double_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x23F9, 0xFE0F), arrayOf("black_square_for_stop"), false),
    GoogleCompatEmoji(intArrayOf(0x23FA, 0xFE0F), arrayOf("black_circle_for_record"), false),
    GoogleCompatEmoji(intArrayOf(0x23CF, 0xFE0F), arrayOf("eject"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A6), arrayOf("cinema"), false),
    GoogleCompatEmoji(intArrayOf(0x1F505), arrayOf("low_brightness"), false),
    GoogleCompatEmoji(intArrayOf(0x1F506), arrayOf("high_brightness"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F6), arrayOf("signal_strength"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F3), arrayOf("vibration_mode"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F4), arrayOf("mobile_phone_off"), false),
    GoogleCompatEmoji(intArrayOf(0x2640, 0xFE0F), arrayOf("female_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2642, 0xFE0F), arrayOf("male_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x26A7, 0xFE0F), arrayOf("transgender_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x2716, 0xFE0F), arrayOf("heavy_multiplication_x"), false),
    GoogleCompatEmoji(intArrayOf(0x2795), arrayOf("heavy_plus_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2796), arrayOf("heavy_minus_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2797), arrayOf("heavy_division_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7F0), arrayOf("heavy_equals_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x267E, 0xFE0F), arrayOf("infinity"), false),
    GoogleCompatEmoji(intArrayOf(0x203C, 0xFE0F), arrayOf("bangbang"), false),
    GoogleCompatEmoji(intArrayOf(0x2049, 0xFE0F), arrayOf("interrobang"), false),
    GoogleCompatEmoji(intArrayOf(0x2753), arrayOf("question"), false),
    GoogleCompatEmoji(intArrayOf(0x2754), arrayOf("grey_question"), false),
    GoogleCompatEmoji(intArrayOf(0x2755), arrayOf("grey_exclamation"), false),
    GoogleCompatEmoji(intArrayOf(0x2757), arrayOf("exclamation", "heavy_exclamation_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x3030, 0xFE0F), arrayOf("wavy_dash"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B1), arrayOf("currency_exchange"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B2), arrayOf("heavy_dollar_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2695, 0xFE0F), arrayOf("medical_symbol", "staff_of_aesculapius"), false),
    GoogleCompatEmoji(intArrayOf(0x267B, 0xFE0F), arrayOf("recycle"), false),
    GoogleCompatEmoji(intArrayOf(0x269C, 0xFE0F), arrayOf("fleur_de_lis"), false),
    GoogleCompatEmoji(intArrayOf(0x1F531), arrayOf("trident"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DB), arrayOf("name_badge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F530), arrayOf("beginner"), false),
    GoogleCompatEmoji(intArrayOf(0x2B55), arrayOf("o"), false),
    GoogleCompatEmoji(intArrayOf(0x2705), arrayOf("white_check_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x2611, 0xFE0F), arrayOf("ballot_box_with_check"), false),
    GoogleCompatEmoji(intArrayOf(0x2714, 0xFE0F), arrayOf("heavy_check_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x274C), arrayOf("x"), false),
    GoogleCompatEmoji(intArrayOf(0x274E), arrayOf("negative_squared_cross_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x27B0), arrayOf("curly_loop"), false),
    GoogleCompatEmoji(intArrayOf(0x27BF), arrayOf("loop"), false),
    GoogleCompatEmoji(intArrayOf(0x303D, 0xFE0F), arrayOf("part_alternation_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x2733, 0xFE0F), arrayOf("eight_spoked_asterisk"), false),
    GoogleCompatEmoji(intArrayOf(0x2734, 0xFE0F), arrayOf("eight_pointed_black_star"), false),
    GoogleCompatEmoji(intArrayOf(0x2747, 0xFE0F), arrayOf("sparkle"), false),
    GoogleCompatEmoji(intArrayOf(0x00A9, 0xFE0F), arrayOf("copyright"), false),
    GoogleCompatEmoji(intArrayOf(0x00AE, 0xFE0F), arrayOf("registered"), false),
    GoogleCompatEmoji(intArrayOf(0x2122, 0xFE0F), arrayOf("tm"), false),
    GoogleCompatEmoji(intArrayOf(0x0023, 0xFE0F, 0x20E3), arrayOf("hash"), false),
    GoogleCompatEmoji(intArrayOf(0x002A, 0xFE0F, 0x20E3), arrayOf("keycap_star"), false),
    GoogleCompatEmoji(intArrayOf(0x0030, 0xFE0F, 0x20E3), arrayOf("zero"), false),
    GoogleCompatEmoji(intArrayOf(0x0031, 0xFE0F, 0x20E3), arrayOf("one"), false),
    GoogleCompatEmoji(intArrayOf(0x0032, 0xFE0F, 0x20E3), arrayOf("two"), false),
    GoogleCompatEmoji(intArrayOf(0x0033, 0xFE0F, 0x20E3), arrayOf("three"), false),
    GoogleCompatEmoji(intArrayOf(0x0034, 0xFE0F, 0x20E3), arrayOf("four"), false),
    GoogleCompatEmoji(intArrayOf(0x0035, 0xFE0F, 0x20E3), arrayOf("five"), false),
    GoogleCompatEmoji(intArrayOf(0x0036, 0xFE0F, 0x20E3), arrayOf("six"), false),
    GoogleCompatEmoji(intArrayOf(0x0037, 0xFE0F, 0x20E3), arrayOf("seven"), false),
    GoogleCompatEmoji(intArrayOf(0x0038, 0xFE0F, 0x20E3), arrayOf("eight"), false),
    GoogleCompatEmoji(intArrayOf(0x0039, 0xFE0F, 0x20E3), arrayOf("nine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51F), arrayOf("keycap_ten"), false),
    GoogleCompatEmoji(intArrayOf(0x1F520), arrayOf("capital_abcd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F521), arrayOf("abcd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F522), arrayOf("1234"), false),
    GoogleCompatEmoji(intArrayOf(0x1F523), arrayOf("symbols"), false),
    GoogleCompatEmoji(intArrayOf(0x1F524), arrayOf("abc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F170, 0xFE0F), arrayOf("a"), false),
    GoogleCompatEmoji(intArrayOf(0x1F18E), arrayOf("ab"), false),
    GoogleCompatEmoji(intArrayOf(0x1F171, 0xFE0F), arrayOf("b"), false),
    GoogleCompatEmoji(intArrayOf(0x1F191), arrayOf("cl"), false),
    GoogleCompatEmoji(intArrayOf(0x1F192), arrayOf("cool"), false),
    GoogleCompatEmoji(intArrayOf(0x1F193), arrayOf("free"), false),
    GoogleCompatEmoji(intArrayOf(0x2139, 0xFE0F), arrayOf("information_source"), false),
    GoogleCompatEmoji(intArrayOf(0x1F194), arrayOf("id"), false),
    GoogleCompatEmoji(intArrayOf(0x24C2, 0xFE0F), arrayOf("m"), false),
    GoogleCompatEmoji(intArrayOf(0x1F195), arrayOf("new"), false),
    GoogleCompatEmoji(intArrayOf(0x1F196), arrayOf("ng"), false),
    GoogleCompatEmoji(intArrayOf(0x1F17E, 0xFE0F), arrayOf("o2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F197), arrayOf("ok"), false),
    GoogleCompatEmoji(intArrayOf(0x1F17F, 0xFE0F), arrayOf("parking"), false),
    GoogleCompatEmoji(intArrayOf(0x1F198), arrayOf("sos"), false),
    GoogleCompatEmoji(intArrayOf(0x1F199), arrayOf("up"), false),
    GoogleCompatEmoji(intArrayOf(0x1F19A), arrayOf("vs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F201), arrayOf("koko"), false),
    GoogleCompatEmoji(intArrayOf(0x1F202, 0xFE0F), arrayOf("sa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F237, 0xFE0F), arrayOf("u6708"), false),
    GoogleCompatEmoji(intArrayOf(0x1F236), arrayOf("u6709"), false),
    GoogleCompatEmoji(intArrayOf(0x1F22F), arrayOf("u6307"), false),
    GoogleCompatEmoji(intArrayOf(0x1F250), arrayOf("ideograph_advantage"), false),
    GoogleCompatEmoji(intArrayOf(0x1F239), arrayOf("u5272"), false),
    GoogleCompatEmoji(intArrayOf(0x1F21A), arrayOf("u7121"), false),
    GoogleCompatEmoji(intArrayOf(0x1F232), arrayOf("u7981"), false),
    GoogleCompatEmoji(intArrayOf(0x1F251), arrayOf("accept"), false),
    GoogleCompatEmoji(intArrayOf(0x1F238), arrayOf("u7533"), false),
    GoogleCompatEmoji(intArrayOf(0x1F234), arrayOf("u5408"), false),
    GoogleCompatEmoji(intArrayOf(0x1F233), arrayOf("u7a7a"), false),
    GoogleCompatEmoji(intArrayOf(0x3297, 0xFE0F), arrayOf("congratulations"), false),
    GoogleCompatEmoji(intArrayOf(0x3299, 0xFE0F), arrayOf("secret"), false),
    GoogleCompatEmoji(intArrayOf(0x1F23A), arrayOf("u55b6"), false),
    GoogleCompatEmoji(intArrayOf(0x1F235), arrayOf("u6e80"), false),
    GoogleCompatEmoji(intArrayOf(0x1F534), arrayOf("red_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E0), arrayOf("large_orange_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E1), arrayOf("large_yellow_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E2), arrayOf("large_green_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F535), arrayOf("large_blue_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E3), arrayOf("large_purple_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E4), arrayOf("large_brown_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x26AB), arrayOf("black_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x26AA), arrayOf("white_circle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E5), arrayOf("large_red_square"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E7), arrayOf("large_orange_square"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E8), arrayOf("large_yellow_square"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7E9), arrayOf("large_green_square"), false),
  )
}
