/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SymbolsCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F3E7), listOf("atm"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AE), listOf("put_litter_in_its_place"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B0), listOf("potable_water"), false),
    GoogleCompatEmoji(intArrayOf(0x267F), listOf("wheelchair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B9), listOf("mens"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BA), listOf("womens"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BB), listOf("restroom"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BC), listOf("baby_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6BE), listOf("wc"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C2), listOf("passport_control"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C3), listOf("customs"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C4), listOf("baggage_claim"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6C5), listOf("left_luggage"), false),
    GoogleCompatEmoji(intArrayOf(0x26A0, 0xFE0F), listOf("warning"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B8), listOf("children_crossing"), false),
    GoogleCompatEmoji(intArrayOf(0x26D4), listOf("no_entry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AB), listOf("no_entry_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B3), listOf("no_bicycles"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AD), listOf("no_smoking"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6AF), listOf("do_not_litter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B1), listOf("non-potable_water"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B7), listOf("no_pedestrians"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F5), listOf("no_mobile_phones"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51E), listOf("underage"), false),
    GoogleCompatEmoji(intArrayOf(0x2622, 0xFE0F), listOf("radioactive_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2623, 0xFE0F), listOf("biohazard_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2B06, 0xFE0F), listOf("arrow_up"), false),
    GoogleCompatEmoji(intArrayOf(0x2197, 0xFE0F), listOf("arrow_upper_right"), false),
    GoogleCompatEmoji(intArrayOf(0x27A1, 0xFE0F), listOf("arrow_right"), false),
    GoogleCompatEmoji(intArrayOf(0x2198, 0xFE0F), listOf("arrow_lower_right"), false),
    GoogleCompatEmoji(intArrayOf(0x2B07, 0xFE0F), listOf("arrow_down"), false),
    GoogleCompatEmoji(intArrayOf(0x2199, 0xFE0F), listOf("arrow_lower_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2B05, 0xFE0F), listOf("arrow_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2196, 0xFE0F), listOf("arrow_upper_left"), false),
    GoogleCompatEmoji(intArrayOf(0x2195, 0xFE0F), listOf("arrow_up_down"), false),
    GoogleCompatEmoji(intArrayOf(0x2194, 0xFE0F), listOf("left_right_arrow"), false),
    GoogleCompatEmoji(intArrayOf(0x21A9, 0xFE0F), listOf("leftwards_arrow_with_hook"), false),
    GoogleCompatEmoji(intArrayOf(0x21AA, 0xFE0F), listOf("arrow_right_hook"), false),
    GoogleCompatEmoji(intArrayOf(0x2934, 0xFE0F), listOf("arrow_heading_up"), false),
    GoogleCompatEmoji(intArrayOf(0x2935, 0xFE0F), listOf("arrow_heading_down"), false),
    GoogleCompatEmoji(intArrayOf(0x1F503), listOf("arrows_clockwise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F504), listOf("arrows_counterclockwise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F519), listOf("back"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51A), listOf("end"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51B), listOf("on"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51C), listOf("soon"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51D), listOf("top"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D0), listOf("place_of_worship"), false),
    GoogleCompatEmoji(intArrayOf(0x269B, 0xFE0F), listOf("atom_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F549, 0xFE0F), listOf("om_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x2721, 0xFE0F), listOf("star_of_david"), false),
    GoogleCompatEmoji(intArrayOf(0x2638, 0xFE0F), listOf("wheel_of_dharma"), false),
    GoogleCompatEmoji(intArrayOf(0x262F, 0xFE0F), listOf("yin_yang"), false),
    GoogleCompatEmoji(intArrayOf(0x271D, 0xFE0F), listOf("latin_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x2626, 0xFE0F), listOf("orthodox_cross"), false),
    GoogleCompatEmoji(intArrayOf(0x262A, 0xFE0F), listOf("star_and_crescent"), false),
    GoogleCompatEmoji(intArrayOf(0x262E, 0xFE0F), listOf("peace_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54E), listOf("menorah_with_nine_branches"), false),
    GoogleCompatEmoji(intArrayOf(0x1F52F), listOf("six_pointed_star"), false),
    GoogleCompatEmoji(intArrayOf(0x2648), listOf("aries"), false),
    GoogleCompatEmoji(intArrayOf(0x2649), listOf("taurus"), false),
    GoogleCompatEmoji(intArrayOf(0x264A), listOf("gemini"), false),
    GoogleCompatEmoji(intArrayOf(0x264B), listOf("cancer"), false),
    GoogleCompatEmoji(intArrayOf(0x264C), listOf("leo"), false),
    GoogleCompatEmoji(intArrayOf(0x264D), listOf("virgo"), false),
    GoogleCompatEmoji(intArrayOf(0x264E), listOf("libra"), false),
    GoogleCompatEmoji(intArrayOf(0x264F), listOf("scorpius"), false),
    GoogleCompatEmoji(intArrayOf(0x2650), listOf("sagittarius"), false),
    GoogleCompatEmoji(intArrayOf(0x2651), listOf("capricorn"), false),
    GoogleCompatEmoji(intArrayOf(0x2652), listOf("aquarius"), false),
    GoogleCompatEmoji(intArrayOf(0x2653), listOf("pisces"), false),
    GoogleCompatEmoji(intArrayOf(0x26CE), listOf("ophiuchus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F500), listOf("twisted_rightwards_arrows"), false),
    GoogleCompatEmoji(intArrayOf(0x1F501), listOf("repeat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F502), listOf("repeat_one"), false),
    GoogleCompatEmoji(intArrayOf(0x25B6, 0xFE0F), listOf("arrow_forward"), false),
    GoogleCompatEmoji(intArrayOf(0x23E9), listOf("fast_forward"), false),
    GoogleCompatEmoji(intArrayOf(0x23ED, 0xFE0F), listOf("black_right_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x23EF, 0xFE0F), listOf("black_right_pointing_triangle_with_double_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x25C0, 0xFE0F), listOf("arrow_backward"), false),
    GoogleCompatEmoji(intArrayOf(0x23EA), listOf("rewind"), false),
    GoogleCompatEmoji(intArrayOf(0x23EE, 0xFE0F), listOf("black_left_pointing_double_triangle_with_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x1F53C), listOf("arrow_up_small"), false),
    GoogleCompatEmoji(intArrayOf(0x23EB), listOf("arrow_double_up"), false),
    GoogleCompatEmoji(intArrayOf(0x1F53D), listOf("arrow_down_small"), false),
    GoogleCompatEmoji(intArrayOf(0x23EC), listOf("arrow_double_down"), false),
    GoogleCompatEmoji(intArrayOf(0x23F8, 0xFE0F), listOf("double_vertical_bar"), false),
    GoogleCompatEmoji(intArrayOf(0x23F9, 0xFE0F), listOf("black_square_for_stop"), false),
    GoogleCompatEmoji(intArrayOf(0x23FA, 0xFE0F), listOf("black_circle_for_record"), false),
    GoogleCompatEmoji(intArrayOf(0x23CF, 0xFE0F), listOf("eject"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A6), listOf("cinema"), false),
    GoogleCompatEmoji(intArrayOf(0x1F505), listOf("low_brightness"), false),
    GoogleCompatEmoji(intArrayOf(0x1F506), listOf("high_brightness"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F6), listOf("signal_strength"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F3), listOf("vibration_mode"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4F4), listOf("mobile_phone_off"), false),
    GoogleCompatEmoji(intArrayOf(0x2640, 0xFE0F), listOf("female_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2642, 0xFE0F), listOf("male_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x26A7, 0xFE0F), listOf("transgender_symbol"), false),
    GoogleCompatEmoji(intArrayOf(0x2716, 0xFE0F), listOf("heavy_multiplication_x"), false),
    GoogleCompatEmoji(intArrayOf(0x2795), listOf("heavy_plus_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2796), listOf("heavy_minus_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2797), listOf("heavy_division_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x1F7F0), listOf("heavy_equals_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x267E, 0xFE0F), listOf("infinity"), false),
    GoogleCompatEmoji(intArrayOf(0x203C, 0xFE0F), listOf("bangbang"), false),
    GoogleCompatEmoji(intArrayOf(0x2049, 0xFE0F), listOf("interrobang"), false),
    GoogleCompatEmoji(intArrayOf(0x2753), listOf("question"), false),
    GoogleCompatEmoji(intArrayOf(0x2754), listOf("grey_question"), false),
    GoogleCompatEmoji(intArrayOf(0x2755), listOf("grey_exclamation"), false),
    GoogleCompatEmoji(intArrayOf(0x2757), listOf("exclamation", "heavy_exclamation_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x3030, 0xFE0F), listOf("wavy_dash"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B1), listOf("currency_exchange"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4B2), listOf("heavy_dollar_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x2695, 0xFE0F), listOf("medical_symbol", "staff_of_aesculapius"), false),
    GoogleCompatEmoji(intArrayOf(0x267B, 0xFE0F), listOf("recycle"), false),
    GoogleCompatEmoji(intArrayOf(0x269C, 0xFE0F), listOf("fleur_de_lis"), false),
    GoogleCompatEmoji(intArrayOf(0x1F531), listOf("trident"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4DB), listOf("name_badge"), false),
    GoogleCompatEmoji(intArrayOf(0x1F530), listOf("beginner"), false),
    GoogleCompatEmoji(intArrayOf(0x2B55), listOf("o"), false),
    GoogleCompatEmoji(intArrayOf(0x2705), listOf("white_check_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x2611, 0xFE0F), listOf("ballot_box_with_check"), false),
    GoogleCompatEmoji(intArrayOf(0x2714, 0xFE0F), listOf("heavy_check_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x274C), listOf("x"), false),
    GoogleCompatEmoji(intArrayOf(0x274E), listOf("negative_squared_cross_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x27B0), listOf("curly_loop"), false),
    GoogleCompatEmoji(intArrayOf(0x27BF), listOf("loop"), false),
    GoogleCompatEmoji(intArrayOf(0x303D, 0xFE0F), listOf("part_alternation_mark"), false),
    GoogleCompatEmoji(intArrayOf(0x2733, 0xFE0F), listOf("eight_spoked_asterisk"), false),
    GoogleCompatEmoji(intArrayOf(0x2734, 0xFE0F), listOf("eight_pointed_black_star"), false),
    GoogleCompatEmoji(intArrayOf(0x2747, 0xFE0F), listOf("sparkle"), false),
    GoogleCompatEmoji(intArrayOf(0x00A9, 0xFE0F), listOf("copyright"), false),
    GoogleCompatEmoji(intArrayOf(0x00AE, 0xFE0F), listOf("registered"), false),
    GoogleCompatEmoji(intArrayOf(0x2122, 0xFE0F), listOf("tm"), false),
    GoogleCompatEmoji(intArrayOf(0x0023, 0xFE0F, 0x20E3), listOf("hash"), false),
    GoogleCompatEmoji(intArrayOf(0x002A, 0xFE0F, 0x20E3), listOf("keycap_star"), false),
    GoogleCompatEmoji(intArrayOf(0x0030, 0xFE0F, 0x20E3), listOf("zero"), false),
    GoogleCompatEmoji(intArrayOf(0x0031, 0xFE0F, 0x20E3), listOf("one"), false),
    GoogleCompatEmoji(intArrayOf(0x0032, 0xFE0F, 0x20E3), listOf("two"), false),
    GoogleCompatEmoji(intArrayOf(0x0033, 0xFE0F, 0x20E3), listOf("three"), false),
    GoogleCompatEmoji(intArrayOf(0x0034, 0xFE0F, 0x20E3), listOf("four"), false),
    GoogleCompatEmoji(intArrayOf(0x0035, 0xFE0F, 0x20E3), listOf("five"), false),
    GoogleCompatEmoji(intArrayOf(0x0036, 0xFE0F, 0x20E3), listOf("six"), false),
    GoogleCompatEmoji(intArrayOf(0x0037, 0xFE0F, 0x20E3), listOf("seven"), false),
    GoogleCompatEmoji(intArrayOf(0x0038, 0xFE0F, 0x20E3), listOf("eight"), false),
    GoogleCompatEmoji(intArrayOf(0x0039, 0xFE0F, 0x20E3), listOf("nine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F51F), listOf("keycap_ten"), false),
    GoogleCompatEmoji(intArrayOf(0x1F520), listOf("capital_abcd"), false),
    GoogleCompatEmoji(intArrayOf(0x1F521), listOf("abcd"), false),
  )
}
