/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object TravelAndPlacesCategoryChunk0 {
  val EMOJIS: Array<GoogleCompatEmoji> = arrayOf(
    GoogleCompatEmoji(intArrayOf(0x1F30D), listOf("earth_africa"), false),
    GoogleCompatEmoji(intArrayOf(0x1F30E), listOf("earth_americas"), false),
    GoogleCompatEmoji(intArrayOf(0x1F30F), listOf("earth_asia"), false),
    GoogleCompatEmoji(intArrayOf(0x1F310), listOf("globe_with_meridians"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FA, 0xFE0F), listOf("world_map"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FE), listOf("japan"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9ED), listOf("compass"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D4, 0xFE0F), listOf("snow_capped_mountain"), false),
    GoogleCompatEmoji(intArrayOf(0x26F0, 0xFE0F), listOf("mountain"), false),
    GoogleCompatEmoji(intArrayOf(0x1F30B), listOf("volcano"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FB), listOf("mount_fuji"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D5, 0xFE0F), listOf("camping"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D6, 0xFE0F), listOf("beach_with_umbrella"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DC, 0xFE0F), listOf("desert"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DD, 0xFE0F), listOf("desert_island"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DE, 0xFE0F), listOf("national_park"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DF, 0xFE0F), listOf("stadium"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DB, 0xFE0F), listOf("classical_building"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D7, 0xFE0F), listOf("building_construction"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F1), listOf("bricks"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAA8), listOf("rock"), false),
    GoogleCompatEmoji(intArrayOf(0x1FAB5), listOf("wood"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D6), listOf("hut"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D8, 0xFE0F), listOf("house_buildings"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3DA, 0xFE0F), listOf("derelict_house_building"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E0), listOf("house"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E1), listOf("house_with_garden"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E2), listOf("office"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E3), listOf("post_office"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E4), listOf("european_post_office"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E5), listOf("hospital"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E6), listOf("bank"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E8), listOf("hotel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3E9), listOf("love_hotel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EA), listOf("convenience_store"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EB), listOf("school"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EC), listOf("department_store"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3ED), listOf("factory"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3EF), listOf("japanese_castle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3F0), listOf("european_castle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F492), listOf("wedding"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FC), listOf("tokyo_tower"), false),
    GoogleCompatEmoji(intArrayOf(0x1F5FD), listOf("statue_of_liberty"), false),
    GoogleCompatEmoji(intArrayOf(0x26EA), listOf("church"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54C), listOf("mosque"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D5), listOf("hindu_temple"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54D), listOf("synagogue"), false),
    GoogleCompatEmoji(intArrayOf(0x26E9, 0xFE0F), listOf("shinto_shrine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F54B), listOf("kaaba"), false),
    GoogleCompatEmoji(intArrayOf(0x26F2), listOf("fountain"), false),
    GoogleCompatEmoji(intArrayOf(0x26FA), listOf("tent"), false),
    GoogleCompatEmoji(intArrayOf(0x1F301), listOf("foggy"), false),
    GoogleCompatEmoji(intArrayOf(0x1F303), listOf("night_with_stars"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3D9, 0xFE0F), listOf("cityscape"), false),
    GoogleCompatEmoji(intArrayOf(0x1F304), listOf("sunrise_over_mountains"), false),
    GoogleCompatEmoji(intArrayOf(0x1F305), listOf("sunrise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F306), listOf("city_sunset"), false),
    GoogleCompatEmoji(intArrayOf(0x1F307), listOf("city_sunrise"), false),
    GoogleCompatEmoji(intArrayOf(0x1F309), listOf("bridge_at_night"), false),
    GoogleCompatEmoji(intArrayOf(0x2668, 0xFE0F), listOf("hotsprings"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A0), listOf("carousel_horse"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6DD), listOf("playground_slide"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A1), listOf("ferris_wheel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3A2), listOf("roller_coaster"), false),
    GoogleCompatEmoji(intArrayOf(0x1F488), listOf("barber"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3AA), listOf("circus_tent"), false),
    GoogleCompatEmoji(intArrayOf(0x1F682), listOf("steam_locomotive"), false),
    GoogleCompatEmoji(intArrayOf(0x1F683), listOf("railway_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F684), listOf("bullettrain_side"), false),
    GoogleCompatEmoji(intArrayOf(0x1F685), listOf("bullettrain_front"), false),
    GoogleCompatEmoji(intArrayOf(0x1F686), listOf("train2"), false),
    GoogleCompatEmoji(intArrayOf(0x1F687), listOf("metro"), false),
    GoogleCompatEmoji(intArrayOf(0x1F688), listOf("light_rail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F689), listOf("station"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68A), listOf("tram"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69D), listOf("monorail"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69E), listOf("mountain_railway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68B), listOf("train"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68C), listOf("bus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68D), listOf("oncoming_bus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68E), listOf("trolleybus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F690), listOf("minibus"), false),
    GoogleCompatEmoji(intArrayOf(0x1F691), listOf("ambulance"), false),
    GoogleCompatEmoji(intArrayOf(0x1F692), listOf("fire_engine"), false),
    GoogleCompatEmoji(intArrayOf(0x1F693), listOf("police_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F694), listOf("oncoming_police_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F695), listOf("taxi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F696), listOf("oncoming_taxi"), false),
    GoogleCompatEmoji(intArrayOf(0x1F697), listOf("car", "red_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F698), listOf("oncoming_automobile"), false),
    GoogleCompatEmoji(intArrayOf(0x1F699), listOf("blue_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6FB), listOf("pickup_truck"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69A), listOf("truck"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69B), listOf("articulated_lorry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69C), listOf("tractor"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3CE, 0xFE0F), listOf("racing_car"), false),
    GoogleCompatEmoji(intArrayOf(0x1F3CD, 0xFE0F), listOf("racing_motorcycle"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F5), listOf("motor_scooter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9BD), listOf("manual_wheelchair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9BC), listOf("motorized_wheelchair"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6FA), listOf("auto_rickshaw"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6B2), listOf("bike"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F4), listOf("scooter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F9), listOf("skateboard"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6FC), listOf("roller_skate"), false),
    GoogleCompatEmoji(intArrayOf(0x1F68F), listOf("busstop"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E3, 0xFE0F), listOf("motorway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E4, 0xFE0F), listOf("railway_track"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E2, 0xFE0F), listOf("oil_drum"), false),
    GoogleCompatEmoji(intArrayOf(0x26FD), listOf("fuelpump"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6DE), listOf("wheel"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A8), listOf("rotating_light"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A5), listOf("traffic_light"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A6), listOf("vertical_traffic_light"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6D1), listOf("octagonal_sign"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A7), listOf("construction"), false),
    GoogleCompatEmoji(intArrayOf(0x2693), listOf("anchor"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6DF), listOf("ring_buoy"), false),
    GoogleCompatEmoji(intArrayOf(0x26F5), listOf("boat", "sailboat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F6), listOf("canoe"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A4), listOf("speedboat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F3, 0xFE0F), listOf("passenger_ship"), false),
    GoogleCompatEmoji(intArrayOf(0x26F4, 0xFE0F), listOf("ferry"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E5, 0xFE0F), listOf("motor_boat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A2), listOf("ship"), false),
    GoogleCompatEmoji(intArrayOf(0x2708, 0xFE0F), listOf("airplane"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6E9, 0xFE0F), listOf("small_airplane"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6EB), listOf("airplane_departure"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6EC), listOf("airplane_arriving"), false),
    GoogleCompatEmoji(intArrayOf(0x1FA82), listOf("parachute"), false),
    GoogleCompatEmoji(intArrayOf(0x1F4BA), listOf("seat"), false),
    GoogleCompatEmoji(intArrayOf(0x1F681), listOf("helicopter"), false),
    GoogleCompatEmoji(intArrayOf(0x1F69F), listOf("suspension_railway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A0), listOf("mountain_cableway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6A1), listOf("aerial_tramway"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F0, 0xFE0F), listOf("satellite"), false),
    GoogleCompatEmoji(intArrayOf(0x1F680), listOf("rocket"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6F8), listOf("flying_saucer"), false),
    GoogleCompatEmoji(intArrayOf(0x1F6CE, 0xFE0F), listOf("bellhop_bell"), false),
    GoogleCompatEmoji(intArrayOf(0x1F9F3), listOf("luggage"), false),
    GoogleCompatEmoji(intArrayOf(0x231B), listOf("hourglass"), false),
    GoogleCompatEmoji(intArrayOf(0x23F3), listOf("hourglass_flowing_sand"), false),
    GoogleCompatEmoji(intArrayOf(0x231A), listOf("watch"), false),
    GoogleCompatEmoji(intArrayOf(0x23F0), listOf("alarm_clock"), false),
    GoogleCompatEmoji(intArrayOf(0x23F1, 0xFE0F), listOf("stopwatch"), false),
    GoogleCompatEmoji(intArrayOf(0x23F2, 0xFE0F), listOf("timer_clock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F570, 0xFE0F), listOf("mantelpiece_clock"), false),
    GoogleCompatEmoji(intArrayOf(0x1F55B), listOf("clock12"), false),
    GoogleCompatEmoji(intArrayOf(0x1F567), listOf("clock1230"), false),
    GoogleCompatEmoji(intArrayOf(0x1F550), listOf("clock1"), false),
  )
}
