/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.google.category

import com.vanniktech.emoji.google.GoogleEmoji

internal object ObjectsCategoryChunk1 {
  val EMOJIS: Array<GoogleEmoji> = arrayOf(
    GoogleEmoji(intArrayOf(0x1F58B, 0xFE0F), listOf("lower_left_fountain_pen"), 31, 34, false),
    GoogleEmoji(intArrayOf(0x1F58A, 0xFE0F), listOf("lower_left_ballpoint_pen"), 31, 33, false),
    GoogleEmoji(intArrayOf(0x1F58C, 0xFE0F), listOf("lower_left_paintbrush"), 31, 35, false),
    GoogleEmoji(intArrayOf(0x1F58D, 0xFE0F), listOf("lower_left_crayon"), 31, 36, false),
    GoogleEmoji(intArrayOf(0x1F4DD), listOf("memo", "pencil"), 28, 52, false),
    GoogleEmoji(intArrayOf(0x1F4BC), listOf("briefcase"), 28, 19, false),
    GoogleEmoji(intArrayOf(0x1F4C1), listOf("file_folder"), 28, 24, false),
    GoogleEmoji(intArrayOf(0x1F4C2), listOf("open_file_folder"), 28, 25, false),
    GoogleEmoji(intArrayOf(0x1F5C2, 0xFE0F), listOf("card_index_dividers"), 32, 0, false),
    GoogleEmoji(intArrayOf(0x1F4C5), listOf("date"), 28, 28, false),
    GoogleEmoji(intArrayOf(0x1F4C6), listOf("calendar"), 28, 29, false),
    GoogleEmoji(intArrayOf(0x1F5D2, 0xFE0F), listOf("spiral_note_pad"), 32, 4, false),
    GoogleEmoji(intArrayOf(0x1F5D3, 0xFE0F), listOf("spiral_calendar_pad"), 32, 5, false),
    GoogleEmoji(intArrayOf(0x1F4C7), listOf("card_index"), 28, 30, false),
    GoogleEmoji(intArrayOf(0x1F4C8), listOf("chart_with_upwards_trend"), 28, 31, false),
    GoogleEmoji(intArrayOf(0x1F4C9), listOf("chart_with_downwards_trend"), 28, 32, false),
    GoogleEmoji(intArrayOf(0x1F4CA), listOf("bar_chart"), 28, 33, false),
    GoogleEmoji(intArrayOf(0x1F4CB), listOf("clipboard"), 28, 34, false),
    GoogleEmoji(intArrayOf(0x1F4CC), listOf("pushpin"), 28, 35, false),
    GoogleEmoji(intArrayOf(0x1F4CD), listOf("round_pushpin"), 28, 36, false),
    GoogleEmoji(intArrayOf(0x1F4CE), listOf("paperclip"), 28, 37, false),
    GoogleEmoji(intArrayOf(0x1F587, 0xFE0F), listOf("linked_paperclips"), 31, 32, false),
    GoogleEmoji(intArrayOf(0x1F4CF), listOf("straight_ruler"), 28, 38, false),
    GoogleEmoji(intArrayOf(0x1F4D0), listOf("triangular_ruler"), 28, 39, false),
    GoogleEmoji(intArrayOf(0x2702, 0xFE0F), listOf("scissors"), 58, 23, false),
    GoogleEmoji(intArrayOf(0x1F5C3, 0xFE0F), listOf("card_file_box"), 32, 1, false),
    GoogleEmoji(intArrayOf(0x1F5C4, 0xFE0F), listOf("file_cabinet"), 32, 2, false),
    GoogleEmoji(intArrayOf(0x1F5D1, 0xFE0F), listOf("wastebasket"), 32, 3, false),
    GoogleEmoji(intArrayOf(0x1F512), listOf("lock"), 29, 43, false),
    GoogleEmoji(intArrayOf(0x1F513), listOf("unlock"), 29, 44, false),
    GoogleEmoji(intArrayOf(0x1F50F), listOf("lock_with_ink_pen"), 29, 40, false),
    GoogleEmoji(intArrayOf(0x1F510), listOf("closed_lock_with_key"), 29, 41, false),
    GoogleEmoji(intArrayOf(0x1F511), listOf("key"), 29, 42, false),
    GoogleEmoji(intArrayOf(0x1F5DD, 0xFE0F), listOf("old_key"), 32, 7, false),
    GoogleEmoji(intArrayOf(0x1F528), listOf("hammer"), 30, 4, false),
    GoogleEmoji(intArrayOf(0x1FA93), listOf("axe"), 54, 5, false),
    GoogleEmoji(intArrayOf(0x26CF, 0xFE0F), listOf("pick"), 57, 50, false),
    GoogleEmoji(intArrayOf(0x2692, 0xFE0F), listOf("hammer_and_pick"), 57, 28, false),
    GoogleEmoji(intArrayOf(0x1F6E0, 0xFE0F), listOf("hammer_and_wrench"), 38, 11, false),
    GoogleEmoji(intArrayOf(0x1F5E1, 0xFE0F), listOf("dagger_knife"), 32, 9, false),
    GoogleEmoji(intArrayOf(0x2694, 0xFE0F), listOf("crossed_swords"), 57, 30, false),
    GoogleEmoji(intArrayOf(0x1F52B), listOf("gun"), 30, 7, false),
    GoogleEmoji(intArrayOf(0x1FA83), listOf("boomerang"), 53, 59, false),
    GoogleEmoji(intArrayOf(0x1F3F9), listOf("bow_and_arrow"), 10, 39, false),
    GoogleEmoji(intArrayOf(0x1F6E1, 0xFE0F), listOf("shield"), 38, 12, false),
    GoogleEmoji(intArrayOf(0x1FA9A), listOf("carpentry_saw"), 54, 12, false),
    GoogleEmoji(intArrayOf(0x1F527), listOf("wrench"), 30, 3, false),
    GoogleEmoji(intArrayOf(0x1FA9B), listOf("screwdriver"), 54, 13, false),
    GoogleEmoji(intArrayOf(0x1F529), listOf("nut_and_bolt"), 30, 5, false),
    GoogleEmoji(intArrayOf(0x2699, 0xFE0F), listOf("gear"), 57, 34, false),
    GoogleEmoji(intArrayOf(0x1F5DC, 0xFE0F), listOf("compression"), 32, 6, false),
    GoogleEmoji(intArrayOf(0x2696, 0xFE0F), listOf("scales"), 57, 32, false),
    GoogleEmoji(intArrayOf(0x1F9AF), listOf("probing_cane"), 45, 4, false),
    GoogleEmoji(intArrayOf(0x1F517), listOf("link"), 29, 48, false),
    GoogleEmoji(intArrayOf(0x26D3, 0xFE0F), listOf("chains"), 57, 52, false),
    GoogleEmoji(intArrayOf(0x1FA9D), listOf("hook"), 54, 15, false),
    GoogleEmoji(intArrayOf(0x1F9F0), listOf("toolbox"), 53, 30, false),
    GoogleEmoji(intArrayOf(0x1F9F2), listOf("magnet"), 53, 32, false),
    GoogleEmoji(intArrayOf(0x1FA9C), listOf("ladder"), 54, 14, false),
    GoogleEmoji(intArrayOf(0x2697, 0xFE0F), listOf("alembic"), 57, 33, false),
    GoogleEmoji(intArrayOf(0x1F9EA), listOf("test_tube"), 53, 24, false),
    GoogleEmoji(intArrayOf(0x1F9EB), listOf("petri_dish"), 53, 25, false),
    GoogleEmoji(intArrayOf(0x1F9EC), listOf("dna"), 53, 26, false),
    GoogleEmoji(intArrayOf(0x1F52C), listOf("microscope"), 30, 8, false),
    GoogleEmoji(intArrayOf(0x1F52D), listOf("telescope"), 30, 9, false),
    GoogleEmoji(intArrayOf(0x1F4E1), listOf("satellite_antenna"), 28, 56, false),
    GoogleEmoji(intArrayOf(0x1F489), listOf("syringe"), 26, 35, false),
    GoogleEmoji(intArrayOf(0x1FA78), listOf("drop_of_blood"), 53, 51, false),
    GoogleEmoji(intArrayOf(0x1F48A), listOf("pill"), 26, 36, false),
    GoogleEmoji(intArrayOf(0x1FA79), listOf("adhesive_bandage"), 53, 52, false),
    GoogleEmoji(intArrayOf(0x1FA7C), listOf("crutch"), 53, 55, false),
    GoogleEmoji(intArrayOf(0x1FA7A), listOf("stethoscope"), 53, 53, false),
    GoogleEmoji(intArrayOf(0x1FA7B), listOf("x-ray"), 53, 54, false),
    GoogleEmoji(intArrayOf(0x1F6AA), listOf("door"), 36, 30, false),
    GoogleEmoji(intArrayOf(0x1F6D7), listOf("elevator"), 38, 7, false),
    GoogleEmoji(intArrayOf(0x1FA9E), listOf("mirror"), 54, 16, false),
    GoogleEmoji(intArrayOf(0x1FA9F), listOf("window"), 54, 17, false),
    GoogleEmoji(intArrayOf(0x1F6CF, 0xFE0F), listOf("bed"), 38, 1, false),
    GoogleEmoji(intArrayOf(0x1F6CB, 0xFE0F), listOf("couch_and_lamp"), 37, 53, false),
    GoogleEmoji(intArrayOf(0x1FA91), listOf("chair"), 54, 3, false),
    GoogleEmoji(intArrayOf(0x1F6BD), listOf("toilet"), 37, 39, false),
    GoogleEmoji(intArrayOf(0x1FAA0), listOf("plunger"), 54, 18, false),
    GoogleEmoji(intArrayOf(0x1F6BF), listOf("shower"), 37, 41, false),
    GoogleEmoji(intArrayOf(0x1F6C1), listOf("bathtub"), 37, 48, false),
    GoogleEmoji(intArrayOf(0x1FAA4), listOf("mouse_trap"), 54, 22, false),
    GoogleEmoji(intArrayOf(0x1FA92), listOf("razor"), 54, 4, false),
    GoogleEmoji(intArrayOf(0x1F9F4), listOf("lotion_bottle"), 53, 34, false),
    GoogleEmoji(intArrayOf(0x1F9F7), listOf("safety_pin"), 53, 37, false),
    GoogleEmoji(intArrayOf(0x1F9F9), listOf("broom"), 53, 39, false),
    GoogleEmoji(intArrayOf(0x1F9FA), listOf("basket"), 53, 40, false),
    GoogleEmoji(intArrayOf(0x1F9FB), listOf("roll_of_paper"), 53, 41, false),
    GoogleEmoji(intArrayOf(0x1FAA3), listOf("bucket"), 54, 21, false),
    GoogleEmoji(intArrayOf(0x1F9FC), listOf("soap"), 53, 42, false),
    GoogleEmoji(intArrayOf(0x1FAE7), listOf("bubbles"), 55, 19, false),
    GoogleEmoji(intArrayOf(0x1FAA5), listOf("toothbrush"), 54, 23, false),
    GoogleEmoji(intArrayOf(0x1F9FD), listOf("sponge"), 53, 43, false),
    GoogleEmoji(intArrayOf(0x1F9EF), listOf("fire_extinguisher"), 53, 29, false),
    GoogleEmoji(intArrayOf(0x1F6D2), listOf("shopping_trolley"), 38, 4, false),
    GoogleEmoji(intArrayOf(0x1F6AC), listOf("smoking"), 36, 32, false),
    GoogleEmoji(intArrayOf(0x26B0, 0xFE0F), listOf("coffin"), 57, 42, false),
    GoogleEmoji(intArrayOf(0x1FAA6), listOf("headstone"), 54, 24, false),
    GoogleEmoji(intArrayOf(0x26B1, 0xFE0F), listOf("funeral_urn"), 57, 43, false),
    GoogleEmoji(intArrayOf(0x1F5FF), listOf("moyai"), 32, 19, false),
    GoogleEmoji(intArrayOf(0x1FAA7), listOf("placard"), 54, 25, false),
    GoogleEmoji(intArrayOf(0x1FAAA), listOf("identification_card"), 54, 28, false),
  )
}
